In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.1)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.7.0-py3-none-any.whl (413 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 7.2 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.7.0

In [ ]:
import pandas as pd
import numpy as np
import optuna

from sklearn.model_selection import KFold
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    StackingRegressor
)
from sklearn.linear_model import Ridge
from xgboost import XGBRegressor

In [ ]:
targets = [
    'Soil EC (us/cm)', 'Soil pH', 'Sand (%)', 'Silt %', 'Clay (%)',
    'SOM%', 'SOC %', 'Ca+2 mg/L', 'Mg+2 mg/L',
    'K+1 mg/L', 'Na+1 mg/L', 'CEC meq/100g'
]
features = ['Mg', 'Al', 'Si', 'P', 'K FC', 'Ca FC', 'Ti FC', 'Mn FC', 'Fe FC','Cu FC', 'Zn FC','R', 'G', 'B']

In [ ]:
df=pd.read_csv('/content/Model_with_elevation_and_band_values.csv')

In [ ]:
df = df[features + targets].dropna()

df = df.apply(pd.to_numeric, errors="coerce")
df = df.dropna().reset_index(drop=True)

df.head()

,Mg,Al,Si,P,K FC,Ca FC,Ti FC,Mn FC,Fe FC,Cu FC,...,Sand (%),Silt %,Clay (%),SOM%,SOC %,Ca+2 mg/L,Mg+2 mg/L,K+1 mg/L,Na+1 mg/L,CEC meq/100g
0,1.752060,3.657063,12.734157,0.142943,0.341214,23.017163,0.265507,0.052525,1.827580,0.002138,...,64.0,28.0,8.0,5.678119,3.293309,123.077,9.076310,7.587645,0.962747,35.623229
1,1.995384,3.988689,14.970171,0.112586,0.366977,17.804501,0.268121,0.056804,2.269902,0.003256,...,62.0,26.0,12.0,4.853888,2.815255,145.737,8.454715,2.744110,1.362580,40.488104
2,2.358324,4.404116,17.743184,0.136088,0.388311,20.007585,0.301709,0.059697,2.365258,0.002851,...,64.4,27.6,8.0,4.487179,2.602564,122.565,7.143860,1.809530,0.692470,33.901898
3,2.808156,5.276980,19.529581,0.079509,0.521733,10.174229,0.428609,0.063371,3.869811,0.003916,...,50.4,31.6,18.0,3.017812,1.750331,123.208,10.290900,2.460310,0.726974,35.448138
4,2.219976,4.754541,17.918748,0.102381,0.437839,17.890691,0.347479,0.068640,2.607818,0.003186,...,58.4,27.6,14.0,4.687500,2.718750,127.556,8.807850,1.807330,0.575045,35.806063

In [ ]:
def select_features_model_based(X_train, y_train, top_k):
    selector = ExtraTreesRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    )

    selector.fit(X_train, y_train)

    importances = pd.Series(
        selector.feature_importances_,
        index=X_train.columns
    )

    return importances.sort_values(ascending=False).head(top_k).index.tolist()

In [ ]:
def get_stacking_model():
    base_models = [
        ("rf", RandomForestRegressor(
            n_estimators=300, max_depth=12, random_state=42)),
        ("gb", GradientBoostingRegressor(
            n_estimators=300, max_depth=4, learning_rate=0.05, random_state=42)),
        ("et", ExtraTreesRegressor(
            n_estimators=400, max_depth=15, random_state=42))
    ]

    meta_model = Ridge(alpha=1.0)

    return StackingRegressor(
        estimators=base_models,
        final_estimator=meta_model,
        cv=5,
        n_jobs=-1
    )

In [ ]:
def objective(trial, X, y):

    # -----------------------------
    # Hyperparameters to optimize
    # -----------------------------
    model_name = trial.suggest_categorical(
        "model", ["ET", "RF", "GB", "XGB"]
    )

    top_k = trial.suggest_int("top_k", 10, 30)

    # -----------------------------
    # Model definitions
    # -----------------------------
    if model_name == "ET":
        model = ExtraTreesRegressor(
            n_estimators=trial.suggest_int("n_estimators", 300, 700),
            max_depth=trial.suggest_int("max_depth", 8, 20),
            random_state=42,
            n_jobs=-1
        )

    elif model_name == "RF":
        model = RandomForestRegressor(
            n_estimators=trial.suggest_int("n_estimators", 300, 700),
            max_depth=trial.suggest_int("max_depth", 8, 20),
            random_state=42,
            n_jobs=-1
        )

    elif model_name == "GB":
        model = GradientBoostingRegressor(
            n_estimators=trial.suggest_int("n_estimators", 200, 500),
            learning_rate=trial.suggest_float("lr", 0.01, 0.1),
            max_depth=trial.suggest_int("max_depth", 2, 5),
            random_state=42
        )

    elif model_name == "XGB":
        model = XGBRegressor(
            n_estimators=trial.suggest_int("n_estimators", 300, 600),
            max_depth=trial.suggest_int("max_depth", 3, 6),
            learning_rate=trial.suggest_float("lr", 0.01, 0.1),
            subsample=trial.suggest_float("subsample", 0.7, 1.0),
            colsample_bytree=trial.suggest_float("colsample", 0.7, 1.0),
            objective="reg:squarederror",
            random_state=42,
            n_jobs=-1
        )



    # -----------------------------
    # Cross-validation
    # -----------------------------
    cv = KFold(n_splits=5, shuffle=True, random_state=42)
    scores = []

    for train_idx, test_idx in cv.split(X):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

        # Feature selection INSIDE fold (leak-free)
        selected_features = select_features_model_based(
            X_train, y_train, top_k
        )

        X_train = X_train[selected_features]
        X_test = X_test[selected_features]

        # Fit & evaluate
        model.fit(X_train, y_train)
        preds = model.predict(X_test)

        scores.append(r2_score(y_test, preds))

    return np.mean(scores)

In [ ]:
results = []

for target in targets:
    print(f"\n🔍 Optimizing for {target}")

    X = df[features]
    y = df[target]

    sampler = optuna.samplers.TPESampler(seed=42)

    study = optuna.create_study(
        direction="maximize",
        sampler=sampler
    )

    study.optimize(
        lambda trial: objective(trial, X, y),
        n_trials=40,
        show_progress_bar=True
    )

    results.append({
        "Target": target,
        "Best R2 (CV mean)": study.best_value,
        "Best Params": study.best_params
    })

[I 2026-01-31 13:02:49,511] A new study created in memory with name: no-name-e0bc4de6-a849-41f3-afaa-90b8b31aa537

🔍 Optimizing for Soil EC (us/cm)

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 13:02:58,637] Trial 0 finished with value: 0.3230903510359842 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.3230903510359842.
[I 2026-01-31 13:03:07,985] Trial 1 finished with value: 0.3604778832931609 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.3604778832931609.
[I 2026-01-31 13:03:12,824] Trial 2 finished with value: 0.24618953786756287 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.3604778832931609.
[I 2026-01-31 13:03:22,011] Trial 3 finished with value: 0.30759106482875354 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.3604778832931609.
[I 2026-01-31 13:03:25,798] Trial 4 finished with value: 0.1775577728964935 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.3604778832931609.
[I 2026-01-31 13:03:32,617] Trial 5 finished with value: 0.10477650093044119 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.3604778832931609.
[I 2026-01-31 13:03:46,562] Trial 6 finished with value: 0.3125225467732785 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.3604778832931609.
[I 2026-01-31 13:03:52,999] Trial 7 finished with value: 0.23126846867880196 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.3604778832931609.
[I 2026-01-31 13:03:57,900] Trial 8 finished with value: 0.15531557331582965 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.3604778832931609.
[I 2026-01-31 13:04:05,829] Trial 9 finished with value: 0.36121574887159885 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 9 with value: 0.36121574887159885.
[I 2026-01-31 13:04:15,241] Trial 10 finished with value: 0.3501013352957485 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 688, 'max_depth': 13}. Best is trial 9 with value: 0.36121574887159885.
[I 2026-01-31 13:04:24,191] Trial 11 finished with value: 0.3634601656958062 and parameters: {'model': 'ET', 'top_k': 29, 'n_estimators': 599, 'max_depth': 11}. Best is trial 11 with value: 0.3634601656958062.
[I 2026-01-31 13:04:31,621] Trial 12 finished with value: 0.3633806191177037 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 522, 'max_depth': 12}. Best is trial 11 with value: 0.3634601656958062.
[I 2026-01-31 13:04:39,732] Trial 13 finished with value: 0.3468328091403211 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 474, 'max_depth': 15}. Best is trial 11 with value: 0.3634601656958062.
[I 2026-01-31 13:04:48,576] Trial 14 finished with value: 0.3639431025414564 and parameters: {'model': 'ET', 'top_k': 24, 'n_estimators': 597, 'max_depth': 11}. Best is trial 14 with value: 0.3639431025414564.
[I 2026-01-31 13:04:53,168] Trial 15 finished with value: 0.180604618306074 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 234, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 14 with value: 0.3639431025414564.
[I 2026-01-31 13:05:02,161] Trial 16 finished with value: 0.3601359730529138 and parameters: {'model': 'ET', 'top_k': 25, 'n_estimators': 628, 'max_depth': 10}. Best is trial 14 with value: 0.3639431025414564.
[I 2026-01-31 13:05:10,645] Trial 17 finished with value: 0.3582633800821139 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 602, 'max_depth': 18}. Best is trial 14 with value: 0.3639431025414564.
[I 2026-01-31 13:05:18,402] Trial 18 finished with value: 0.362273437523061 and parameters: {'model': 'ET', 'top_k': 16, 'n_estimators': 473, 'max_depth': 10}. Best is trial 14 with value: 0.3639431025414564.
[I 2026-01-31 13:05:24,441] Trial 19 finished with value: -0.01784941206337749 and parameters: {'model': 'GB', 'top_k': 25, 'n_estimators': 422, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 14 with value: 0.3639431025414564.
[I 2026-01-31 13:05:33,392] Trial 20 finished with value: 0.3525690554209824 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 582, 'max_depth': 17}. Best is trial 14 with value: 0.3639431025414564.
[I 2026-01-31 13:05:41,784] Trial 21 finished with value: 0.36262823547940287 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 536, 'max_depth': 12}. Best is trial 14 with value: 0.3639431025414564.
[I 2026-01-31 13:05:51,416] Trial 22 finished with value: 0.3617929159781885 and parameters: {'model': 'ET', 'top_k': 27, 'n_estimators': 682, 'max_depth': 11}. Best is trial 14 with value: 0.3639431025414564.
[I 2026-01-31 13:05:58,915] Trial 23 finished with value: 0.3660693593213149 and parameters: {'model': 'ET', 'top_k': 24, 'n_estimators': 495, 'max_depth': 13}. Best is trial 23 with value: 0.3660693593213149.
[I 2026-01-31 13:06:07,966] Trial 24 finished with value: 0.35920634735326995 and parameters: {'model': 'ET', 'top_k': 24, 'n_estimators': 576, 'max_depth': 14}. Best is trial 23 with value: 0.3660693593213149.
[I 2026-01-31 13:06:16,008] Trial 25 finished with value: 0.3598253780113284 and parameters: {'model': 'ET', 'top_k': 20, 'n_estimators': 475, 'max_depth': 14}. Best is trial 23 with value: 0.3660693593213149.
[I 2026-01-31 13:06:24,823] Trial 26 finished with value: 0.36157504358090414 and parameters: {'model': 'ET', 'top_k': 22, 'n_estimators': 659, 'max_depth': 11}. Best is trial 23 with value: 0.3660693593213149.
[I 2026-01-31 13:06:33,470] Trial 27 finished with value: 0.19557163077228124 and parameters: {'model': 'GB', 'top_k': 16, 'n_estimators': 427, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 23 with value: 0.3660693593213149.
[I 2026-01-31 13:06:45,485] Trial 28 finished with value: 0.3081166844186892 and parameters: {'model': 'RF', 'top_k': 24, 'n_estimators': 501, 'max_depth': 16}. Best is trial 23 with value: 0.3660693593213149.
[I 2026-01-31 13:06:58,535] Trial 29 finished with value: 0.314522873959178 and parameters: {'model': 'RF', 'top_k': 17, 'n_estimators': 573, 'max_depth': 13}. Best is trial 23 with value: 0.3660693593213149.
[I 2026-01-31 13:07:07,381] Trial 30 finished with value: 0.35432553117548665 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 617, 'max_depth': 9}. Best is trial 23 with value: 0.3660693593213149.
[I 2026-01-31 13:07:14,696] Trial 31 finished with value: 0.36302304369789873 and parameters: {'model': 'ET', 'top_k': 29, 'n_estimators': 504, 'max_depth': 12}. Best is trial 23 with value: 0.3660693593213149.
[I 2026-01-31 13:07:23,065] Trial 32 finished with value: 0.36619047032480656 and parameters: {'model': 'ET', 'top_k': 27, 'n_estimators': 519, 'max_depth': 11}. Best is trial 32 with value: 0.36619047032480656.
[I 2026-01-31 13:07:32,376] Trial 33 finished with value: 0.3614097264411993 and parameters: {'model': 'ET', 'top_k': 26, 'n_estimators': 650, 'max_depth': 11}. Best is trial 32 with value: 0.36619047032480656.
[I 2026-01-31 13:07:38,977] Trial 34 finished with value: 0.3618957936511663 and parameters: {'model': 'ET', 'top_k': 27, 'n_estimators': 452, 'max_depth': 10}. Best is trial 32 with value: 0.36619047032480656.
[I 2026-01-31 13:07:47,232] Trial 35 finished with value: 0.35286880913932717 and parameters: {'model': 'ET', 'top_k': 24, 'n_estimators': 561, 'max_depth': 9}. Best is trial 32 with value: 0.36619047032480656.
[I 2026-01-31 13:07:52,830] Trial 36 finished with value: 0.10925416847672935 and parameters: {'model': 'XGB', 'top_k': 21, 'n_estimators': 500, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 32 with value: 0.36619047032480656.
[I 2026-01-31 13:08:06,207] Trial 37 finished with value: 0.31205068683846277 and parameters: {'model': 'RF', 'top_k': 27, 'n_estimators': 605, 'max_depth': 13}. Best is trial 32 with value: 0.36619047032480656.
[I 2026-01-31 13:08:14,132] Trial 38 finished with value: 0.35361662680740646 and parameters: {'model': 'ET', 'top_k': 25, 'n_estimators': 519, 'max_depth': 9}. Best is trial 32 with value: 0.36619047032480656.

[I 2026-01-31 13:08:19,703] A new study created in memory with name: no-name-6dfbcad8-343b-4581-b093-54e46ed126b9

[I 2026-01-31 13:08:19,692] Trial 39 finished with value: 0.16812151310797438 and parameters: {'model': 'XGB', 'top_k': 29, 'n_estimators': 564, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 32 with value: 0.36619047032480656.

🔍 Optimizing for Soil pH

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 13:08:28,655] Trial 0 finished with value: 0.6764735822812338 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.6764735822812338.
[I 2026-01-31 13:08:37,643] Trial 1 finished with value: 0.7053572937394437 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.7053572937394437.
[I 2026-01-31 13:08:42,344] Trial 2 finished with value: 0.6798242939525098 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.7053572937394437.
[I 2026-01-31 13:08:51,040] Trial 3 finished with value: 0.6761163381077785 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.7053572937394437.
[I 2026-01-31 13:08:54,722] Trial 4 finished with value: 0.6855866984005703 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.7053572937394437.
[I 2026-01-31 13:09:01,746] Trial 5 finished with value: 0.6579267945746705 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.7053572937394437.
[I 2026-01-31 13:09:13,768] Trial 6 finished with value: 0.6782405483723083 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.7053572937394437.
[I 2026-01-31 13:09:19,186] Trial 7 finished with value: 0.6760379169957023 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.7053572937394437.
[I 2026-01-31 13:09:24,042] Trial 8 finished with value: 0.6693914779957588 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.7053572937394437.
[I 2026-01-31 13:09:31,860] Trial 9 finished with value: 0.7064742600328506 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 9 with value: 0.7064742600328506.
[I 2026-01-31 13:09:41,280] Trial 10 finished with value: 0.7116084044059885 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 688, 'max_depth': 13}. Best is trial 10 with value: 0.7116084044059885.
[I 2026-01-31 13:09:50,772] Trial 11 finished with value: 0.7116849081005424 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 694, 'max_depth': 13}. Best is trial 11 with value: 0.7116849081005424.
[I 2026-01-31 13:09:59,521] Trial 12 finished with value: 0.7127776864875226 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 699, 'max_depth': 15}. Best is trial 12 with value: 0.7127776864875226.
[I 2026-01-31 13:10:09,781] Trial 13 finished with value: 0.7068048563901586 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 698, 'max_depth': 16}. Best is trial 12 with value: 0.7127776864875226.
[I 2026-01-31 13:10:18,890] Trial 14 finished with value: 0.7151832020289092 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 629, 'max_depth': 17}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:10:23,399] Trial 15 finished with value: 0.6715334055175519 and parameters: {'model': 'GB', 'top_k': 15, 'n_estimators': 231, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:10:32,397] Trial 16 finished with value: 0.7086754068287066 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 585, 'max_depth': 18}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:10:40,486] Trial 17 finished with value: 0.7114290907311865 and parameters: {'model': 'ET', 'top_k': 16, 'n_estimators': 467, 'max_depth': 17}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:10:49,218] Trial 18 finished with value: 0.7100164674543484 and parameters: {'model': 'ET', 'top_k': 17, 'n_estimators': 634, 'max_depth': 20}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:10:57,332] Trial 19 finished with value: 0.6468273970136915 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 441, 'lr': 0.09983831247079358, 'max_depth': 4}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:11:07,040] Trial 20 finished with value: 0.7087058672440171 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 629, 'max_depth': 15}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:11:15,366] Trial 21 finished with value: 0.7117028861672179 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 668, 'max_depth': 13}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:11:24,614] Trial 22 finished with value: 0.7137732811697639 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 658, 'max_depth': 14}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:11:33,746] Trial 23 finished with value: 0.7087519228055835 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 593, 'max_depth': 17}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:11:43,455] Trial 24 finished with value: 0.708077706364582 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 655, 'max_depth': 15}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:11:51,092] Trial 25 finished with value: 0.703660180930435 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 585, 'max_depth': 11}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:12:00,437] Trial 26 finished with value: 0.7062489661346043 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 610, 'max_depth': 14}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:12:06,884] Trial 27 finished with value: 0.6998345649817028 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 480, 'lr': 0.0399204177340166, 'max_depth': 2}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:12:18,176] Trial 28 finished with value: 0.6795642954549461 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 537, 'max_depth': 17}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:12:33,355] Trial 29 finished with value: 0.6808175293034182 and parameters: {'model': 'RF', 'top_k': 16, 'n_estimators': 660, 'max_depth': 16}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:12:41,402] Trial 30 finished with value: 0.7035928701679699 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 564, 'max_depth': 14}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:12:50,843] Trial 31 finished with value: 0.7117632277180969 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 667, 'max_depth': 13}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:13:00,268] Trial 32 finished with value: 0.7035376645304375 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 665, 'max_depth': 11}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:13:09,003] Trial 33 finished with value: 0.7050601897097348 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 626, 'max_depth': 14}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:13:18,591] Trial 34 finished with value: 0.7046482075168767 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 650, 'max_depth': 16}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:13:28,073] Trial 35 finished with value: 0.7130752170671751 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 678, 'max_depth': 12}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:13:32,756] Trial 36 finished with value: 0.668839439072868 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 569, 'max_depth': 4, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:13:45,795] Trial 37 finished with value: 0.6804360191600324 and parameters: {'model': 'RF', 'top_k': 20, 'n_estimators': 610, 'max_depth': 10}. Best is trial 14 with value: 0.7151832020289092.
[I 2026-01-31 13:13:54,283] Trial 38 finished with value: 0.7062847905769892 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 517, 'max_depth': 12}. Best is trial 14 with value: 0.7151832020289092.

[I 2026-01-31 13:14:01,355] A new study created in memory with name: no-name-ecc6ee46-a8db-4f8a-b056-b0a4e1d4228a

[I 2026-01-31 13:14:01,348] Trial 39 finished with value: 0.6920276399452218 and parameters: {'model': 'XGB', 'top_k': 24, 'n_estimators': 584, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 14 with value: 0.7151832020289092.

🔍 Optimizing for Sand (%)

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 13:14:09,216] Trial 0 finished with value: 0.46684120957449987 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.46684120957449987.
[I 2026-01-31 13:14:18,176] Trial 1 finished with value: 0.5053848785205675 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.5053848785205675.
[I 2026-01-31 13:14:22,942] Trial 2 finished with value: 0.4476664484069069 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.5053848785205675.
[I 2026-01-31 13:14:31,541] Trial 3 finished with value: 0.46747899391059206 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.5053848785205675.
[I 2026-01-31 13:14:35,185] Trial 4 finished with value: 0.43226312747224804 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.5053848785205675.
[I 2026-01-31 13:14:42,064] Trial 5 finished with value: 0.3812100019396228 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.5053848785205675.
[I 2026-01-31 13:14:53,868] Trial 6 finished with value: 0.46740309014206716 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.5053848785205675.
[I 2026-01-31 13:14:59,366] Trial 7 finished with value: 0.43127945171086407 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.5053848785205675.
[I 2026-01-31 13:15:04,453] Trial 8 finished with value: 0.40573836414892106 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.5053848785205675.
[I 2026-01-31 13:15:11,885] Trial 9 finished with value: 0.500193122981387 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 1 with value: 0.5053848785205675.
[I 2026-01-31 13:15:21,116] Trial 10 finished with value: 0.4912046662800596 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 688, 'max_depth': 12}. Best is trial 1 with value: 0.5053848785205675.
[I 2026-01-31 13:15:30,110] Trial 11 finished with value: 0.500213055144369 and parameters: {'model': 'ET', 'top_k': 29, 'n_estimators': 599, 'max_depth': 12}. Best is trial 1 with value: 0.5053848785205675.
[I 2026-01-31 13:15:38,405] Trial 12 finished with value: 0.5070628468957405 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 650, 'max_depth': 11}. Best is trial 12 with value: 0.5070628468957405.
[I 2026-01-31 13:15:47,806] Trial 13 finished with value: 0.5039391510816476 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 698, 'max_depth': 10}. Best is trial 12 with value: 0.5070628468957405.
[I 2026-01-31 13:15:57,163] Trial 14 finished with value: 0.5038065996149534 and parameters: {'model': 'ET', 'top_k': 23, 'n_estimators': 629, 'max_depth': 15}. Best is trial 12 with value: 0.5070628468957405.
[I 2026-01-31 13:16:03,116] Trial 15 finished with value: 0.3959265426909039 and parameters: {'model': 'GB', 'top_k': 16, 'n_estimators': 435, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 12 with value: 0.5070628468957405.
[I 2026-01-31 13:16:11,990] Trial 16 finished with value: 0.5049933264118375 and parameters: {'model': 'ET', 'top_k': 26, 'n_estimators': 635, 'max_depth': 10}. Best is trial 12 with value: 0.5070628468957405.
[I 2026-01-31 13:16:19,584] Trial 17 finished with value: 0.5047747840498594 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 477, 'max_depth': 10}. Best is trial 12 with value: 0.5070628468957405.
[I 2026-01-31 13:16:27,607] Trial 18 finished with value: 0.5025352192346065 and parameters: {'model': 'ET', 'top_k': 24, 'n_estimators': 574, 'max_depth': 17}. Best is trial 12 with value: 0.5070628468957405.
[I 2026-01-31 13:16:33,108] Trial 19 finished with value: 0.3948408683246639 and parameters: {'model': 'GB', 'top_k': 27, 'n_estimators': 258, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 12 with value: 0.5070628468957405.
[I 2026-01-31 13:16:41,697] Trial 20 finished with value: 0.5042796420059176 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 666, 'max_depth': 13}. Best is trial 12 with value: 0.5070628468957405.
[I 2026-01-31 13:16:50,614] Trial 21 finished with value: 0.504548862410265 and parameters: {'model': 'ET', 'top_k': 25, 'n_estimators': 641, 'max_depth': 10}. Best is trial 12 with value: 0.5070628468957405.
[I 2026-01-31 13:16:59,432] Trial 22 finished with value: 0.5079423775173241 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 619, 'max_depth': 11}. Best is trial 22 with value: 0.5079423775173241.
[I 2026-01-31 13:17:07,217] Trial 23 finished with value: 0.5085818877335612 and parameters: {'model': 'ET', 'top_k': 29, 'n_estimators': 597, 'max_depth': 11}. Best is trial 23 with value: 0.5085818877335612.
[I 2026-01-31 13:17:16,134] Trial 24 finished with value: 0.50105333284668 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 594, 'max_depth': 14}. Best is trial 23 with value: 0.5085818877335612.
[I 2026-01-31 13:17:24,092] Trial 25 finished with value: 0.5077383035879193 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 510, 'max_depth': 11}. Best is trial 23 with value: 0.5085818877335612.
[I 2026-01-31 13:17:31,154] Trial 26 finished with value: 0.5056707256293345 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 492, 'max_depth': 13}. Best is trial 23 with value: 0.5085818877335612.
[I 2026-01-31 13:17:39,713] Trial 27 finished with value: 0.3908899018795471 and parameters: {'model': 'GB', 'top_k': 25, 'n_estimators': 464, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 23 with value: 0.5085818877335612.
[I 2026-01-31 13:17:51,081] Trial 28 finished with value: 0.4694322194354418 and parameters: {'model': 'RF', 'top_k': 15, 'n_estimators': 537, 'max_depth': 9}. Best is trial 23 with value: 0.5085818877335612.
[I 2026-01-31 13:18:02,282] Trial 29 finished with value: 0.46817022191768026 and parameters: {'model': 'RF', 'top_k': 27, 'n_estimators': 511, 'max_depth': 11}. Best is trial 23 with value: 0.5085818877335612.
[I 2026-01-31 13:18:09,463] Trial 30 finished with value: 0.5018995506458058 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 578, 'max_depth': 9}. Best is trial 23 with value: 0.5085818877335612.
[I 2026-01-31 13:18:18,699] Trial 31 finished with value: 0.5076929035365333 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 664, 'max_depth': 11}. Best is trial 23 with value: 0.5085818877335612.
[I 2026-01-31 13:18:27,717] Trial 32 finished with value: 0.5083701449476411 and parameters: {'model': 'ET', 'top_k': 29, 'n_estimators': 609, 'max_depth': 11}. Best is trial 23 with value: 0.5085818877335612.
[I 2026-01-31 13:18:36,521] Trial 33 finished with value: 0.5050668638625385 and parameters: {'model': 'ET', 'top_k': 29, 'n_estimators': 611, 'max_depth': 13}. Best is trial 23 with value: 0.5085818877335612.
[I 2026-01-31 13:18:44,309] Trial 34 finished with value: 0.5087123738166336 and parameters: {'model': 'ET', 'top_k': 29, 'n_estimators': 565, 'max_depth': 11}. Best is trial 34 with value: 0.5087123738166336.
[I 2026-01-31 13:18:52,494] Trial 35 finished with value: 0.5056553834716613 and parameters: {'model': 'ET', 'top_k': 27, 'n_estimators': 565, 'max_depth': 9}. Best is trial 34 with value: 0.5087123738166336.
[I 2026-01-31 13:18:58,021] Trial 36 finished with value: 0.39759881647942874 and parameters: {'model': 'XGB', 'top_k': 25, 'n_estimators': 557, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 34 with value: 0.5087123738166336.
[I 2026-01-31 13:19:10,683] Trial 37 finished with value: 0.46664401370148684 and parameters: {'model': 'RF', 'top_k': 29, 'n_estimators': 607, 'max_depth': 15}. Best is trial 34 with value: 0.5087123738166336.
[I 2026-01-31 13:19:19,014] Trial 38 finished with value: 0.5001832290283333 and parameters: {'model': 'ET', 'top_k': 22, 'n_estimators': 529, 'max_depth': 14}. Best is trial 34 with value: 0.5087123738166336.

[I 2026-01-31 13:19:24,217] A new study created in memory with name: no-name-d777293a-7dae-485f-8d1e-8ed141ace7ca

[I 2026-01-31 13:19:24,207] Trial 39 finished with value: 0.4497648744567423 and parameters: {'model': 'XGB', 'top_k': 20, 'n_estimators': 579, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 34 with value: 0.5087123738166336.

🔍 Optimizing for Silt %

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 13:19:32,867] Trial 0 finished with value: 0.4497971518744416 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.4497971518744416.
[I 2026-01-31 13:19:41,487] Trial 1 finished with value: 0.46077808673119147 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:19:46,098] Trial 2 finished with value: 0.387097780505735 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:19:54,438] Trial 3 finished with value: 0.4508235665978509 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:19:57,991] Trial 4 finished with value: 0.35653338811400015 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:20:04,703] Trial 5 finished with value: 0.37625880130177 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:20:15,588] Trial 6 finished with value: 0.45647183992846047 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:20:22,136] Trial 7 finished with value: 0.3515918578952991 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:20:25,722] Trial 8 finished with value: 0.33636679971144756 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:20:34,050] Trial 9 finished with value: 0.45482391869497657 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:20:43,166] Trial 10 finished with value: 0.45955628603831367 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 688, 'max_depth': 12}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:20:51,463] Trial 11 finished with value: 0.45973775118704036 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 695, 'max_depth': 12}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:21:00,884] Trial 12 finished with value: 0.4591524672125445 and parameters: {'model': 'ET', 'top_k': 16, 'n_estimators': 699, 'max_depth': 11}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:21:10,078] Trial 13 finished with value: 0.4541329218573595 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 621, 'max_depth': 15}. Best is trial 1 with value: 0.46077808673119147.
[I 2026-01-31 13:21:17,936] Trial 14 finished with value: 0.4706321164779519 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 629, 'max_depth': 10}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:21:23,143] Trial 15 finished with value: 0.45696200735419695 and parameters: {'model': 'GB', 'top_k': 15, 'n_estimators': 231, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:21:30,793] Trial 16 finished with value: 0.46098683507005 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 585, 'max_depth': 10}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:21:38,048] Trial 17 finished with value: 0.46440168395686365 and parameters: {'model': 'ET', 'top_k': 22, 'n_estimators': 467, 'max_depth': 9}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:21:45,966] Trial 18 finished with value: 0.44885147105479445 and parameters: {'model': 'ET', 'top_k': 24, 'n_estimators': 457, 'max_depth': 18}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:21:51,795] Trial 19 finished with value: 0.3047797306988751 and parameters: {'model': 'GB', 'top_k': 13, 'n_estimators': 440, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:21:59,366] Trial 20 finished with value: 0.46457382951738924 and parameters: {'model': 'ET', 'top_k': 17, 'n_estimators': 489, 'max_depth': 9}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:22:06,216] Trial 21 finished with value: 0.46509221840205794 and parameters: {'model': 'ET', 'top_k': 18, 'n_estimators': 507, 'max_depth': 9}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:22:14,088] Trial 22 finished with value: 0.4646671038635395 and parameters: {'model': 'ET', 'top_k': 17, 'n_estimators': 537, 'max_depth': 9}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:22:22,084] Trial 23 finished with value: 0.4500054312278913 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 544, 'max_depth': 14}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:22:29,326] Trial 24 finished with value: 0.4647960907901242 and parameters: {'model': 'ET', 'top_k': 20, 'n_estimators': 511, 'max_depth': 9}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:22:38,290] Trial 25 finished with value: 0.4590967529196014 and parameters: {'model': 'ET', 'top_k': 20, 'n_estimators': 642, 'max_depth': 11}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:22:45,429] Trial 26 finished with value: 0.4544600593767335 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 507, 'max_depth': 13}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:22:53,284] Trial 27 finished with value: 0.36757261810992803 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 421, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:23:05,401] Trial 28 finished with value: 0.45488674628432124 and parameters: {'model': 'RF', 'top_k': 19, 'n_estimators': 580, 'max_depth': 10}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:23:16,970] Trial 29 finished with value: 0.4543267968687529 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 590, 'max_depth': 9}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:23:24,234] Trial 30 finished with value: 0.4580693833684862 and parameters: {'model': 'ET', 'top_k': 24, 'n_estimators': 508, 'max_depth': 11}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:23:31,797] Trial 31 finished with value: 0.4645340666623382 and parameters: {'model': 'ET', 'top_k': 17, 'n_estimators': 522, 'max_depth': 9}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:23:39,462] Trial 32 finished with value: 0.4595797133855887 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 483, 'max_depth': 10}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:23:47,426] Trial 33 finished with value: 0.46551979241081265 and parameters: {'model': 'ET', 'top_k': 20, 'n_estimators': 650, 'max_depth': 9}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:23:56,881] Trial 34 finished with value: 0.4490550997823398 and parameters: {'model': 'ET', 'top_k': 20, 'n_estimators': 659, 'max_depth': 17}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:24:05,535] Trial 35 finished with value: 0.4607370926856678 and parameters: {'model': 'ET', 'top_k': 19, 'n_estimators': 614, 'max_depth': 10}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:24:10,901] Trial 36 finished with value: 0.3424909120438715 and parameters: {'model': 'XGB', 'top_k': 21, 'n_estimators': 558, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:24:24,145] Trial 37 finished with value: 0.45376604611792865 and parameters: {'model': 'RF', 'top_k': 23, 'n_estimators': 655, 'max_depth': 11}. Best is trial 14 with value: 0.4706321164779519.
[I 2026-01-31 13:24:33,103] Trial 38 finished with value: 0.46566612105689914 and parameters: {'model': 'ET', 'top_k': 18, 'n_estimators': 670, 'max_depth': 9}. Best is trial 14 with value: 0.4706321164779519.

[I 2026-01-31 13:24:38,444] A new study created in memory with name: no-name-44a72918-be05-4021-b499-c2a7bf0788f3

[I 2026-01-31 13:24:38,434] Trial 39 finished with value: 0.36480874605734054 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 583, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 14 with value: 0.4706321164779519.

🔍 Optimizing for Clay (%)

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 13:24:47,039] Trial 0 finished with value: 0.5151270243425987 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.5151270243425987.
[I 2026-01-31 13:24:55,477] Trial 1 finished with value: 0.5713695848661857 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.5713695848661857.
[I 2026-01-31 13:25:00,028] Trial 2 finished with value: 0.5314574689074714 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.5713695848661857.
[I 2026-01-31 13:25:08,739] Trial 3 finished with value: 0.5298275888446871 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.5713695848661857.
[I 2026-01-31 13:25:12,270] Trial 4 finished with value: 0.5031679240314997 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.5713695848661857.
[I 2026-01-31 13:25:18,903] Trial 5 finished with value: 0.473331812424355 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.5713695848661857.
[I 2026-01-31 13:25:30,922] Trial 6 finished with value: 0.5237706905928976 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.5713695848661857.
[I 2026-01-31 13:25:36,455] Trial 7 finished with value: 0.526135636139359 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.5713695848661857.
[I 2026-01-31 13:25:39,935] Trial 8 finished with value: 0.519488002886277 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.5713695848661857.
[I 2026-01-31 13:25:47,853] Trial 9 finished with value: 0.5755002221707148 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 9 with value: 0.5755002221707148.
[I 2026-01-31 13:25:56,785] Trial 10 finished with value: 0.5805682826721504 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 688, 'max_depth': 13}. Best is trial 10 with value: 0.5805682826721504.
[I 2026-01-31 13:26:04,972] Trial 11 finished with value: 0.5804388126162028 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 694, 'max_depth': 13}. Best is trial 10 with value: 0.5805682826721504.
[I 2026-01-31 13:26:14,111] Trial 12 finished with value: 0.582230546182312 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 699, 'max_depth': 15}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:26:23,651] Trial 13 finished with value: 0.5776715787836404 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 698, 'max_depth': 16}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:26:31,420] Trial 14 finished with value: 0.5813633890790786 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 629, 'max_depth': 17}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:26:36,603] Trial 15 finished with value: 0.4499757416343112 and parameters: {'model': 'GB', 'top_k': 15, 'n_estimators': 231, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:26:44,266] Trial 16 finished with value: 0.5790044491321118 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 585, 'max_depth': 18}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:26:51,739] Trial 17 finished with value: 0.5738857526919479 and parameters: {'model': 'ET', 'top_k': 16, 'n_estimators': 467, 'max_depth': 17}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:27:00,897] Trial 18 finished with value: 0.573870715607475 and parameters: {'model': 'ET', 'top_k': 17, 'n_estimators': 634, 'max_depth': 20}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:27:08,215] Trial 19 finished with value: 0.4577022282083737 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 441, 'lr': 0.09983831247079358, 'max_depth': 4}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:27:17,076] Trial 20 finished with value: 0.5749103943784022 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 629, 'max_depth': 15}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:27:25,951] Trial 21 finished with value: 0.5803877439343579 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 668, 'max_depth': 13}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:27:33,921] Trial 22 finished with value: 0.5789864323672707 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 661, 'max_depth': 14}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:27:42,510] Trial 23 finished with value: 0.5810035103378068 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 597, 'max_depth': 17}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:27:51,017] Trial 24 finished with value: 0.581014332855154 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 589, 'max_depth': 17}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:27:58,769] Trial 25 finished with value: 0.5752431467348587 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 595, 'max_depth': 17}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:28:07,070] Trial 26 finished with value: 0.5780131231288799 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 552, 'max_depth': 19}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:28:13,598] Trial 27 finished with value: 0.4533424487941769 and parameters: {'model': 'GB', 'top_k': 16, 'n_estimators': 463, 'lr': 0.0399204177340166, 'max_depth': 2}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:28:23,832] Trial 28 finished with value: 0.5295903987059889 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 501, 'max_depth': 16}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:28:37,497] Trial 29 finished with value: 0.5238769237817282 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 618, 'max_depth': 18}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:28:46,293] Trial 30 finished with value: 0.5786118110060139 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 655, 'max_depth': 15}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:28:54,779] Trial 31 finished with value: 0.5810035103378068 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 597, 'max_depth': 17}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:29:02,272] Trial 32 finished with value: 0.5810076587410953 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 579, 'max_depth': 16}. Best is trial 12 with value: 0.582230546182312.
[I 2026-01-31 13:29:10,396] Trial 33 finished with value: 0.5854856983786851 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 574, 'max_depth': 16}. Best is trial 33 with value: 0.5854856983786851.
[I 2026-01-31 13:29:17,837] Trial 34 finished with value: 0.5791225727230407 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 509, 'max_depth': 11}. Best is trial 33 with value: 0.5854856983786851.
[I 2026-01-31 13:29:25,592] Trial 35 finished with value: 0.5828018376554551 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 645, 'max_depth': 14}. Best is trial 33 with value: 0.5854856983786851.
[I 2026-01-31 13:29:32,420] Trial 36 finished with value: 0.4785010700814662 and parameters: {'model': 'XGB', 'top_k': 11, 'n_estimators': 570, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 33 with value: 0.5854856983786851.
[I 2026-01-31 13:29:45,854] Trial 37 finished with value: 0.523071316933003 and parameters: {'model': 'RF', 'top_k': 20, 'n_estimators': 645, 'max_depth': 14}. Best is trial 33 with value: 0.5854856983786851.
[I 2026-01-31 13:29:54,902] Trial 38 finished with value: 0.576092469439005 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 671, 'max_depth': 14}. Best is trial 33 with value: 0.5854856983786851.

[I 2026-01-31 13:29:59,986] A new study created in memory with name: no-name-29c5ec66-068e-4427-86db-2520da30f3d5

[I 2026-01-31 13:29:59,979] Trial 39 finished with value: 0.5335905096574034 and parameters: {'model': 'XGB', 'top_k': 24, 'n_estimators': 571, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 33 with value: 0.5854856983786851.

🔍 Optimizing for SOM%

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 13:30:08,893] Trial 0 finished with value: 0.8877142564974342 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.8877142564974342.
[I 2026-01-31 13:30:16,918] Trial 1 finished with value: 0.8939188294745231 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.8939188294745231.
[I 2026-01-31 13:30:23,261] Trial 2 finished with value: 0.8979670260565884 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 2 with value: 0.8979670260565884.
[I 2026-01-31 13:30:31,863] Trial 3 finished with value: 0.8865681394120918 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 2 with value: 0.8979670260565884.
[I 2026-01-31 13:30:35,864] Trial 4 finished with value: 0.8893060492619945 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 2 with value: 0.8979670260565884.
[I 2026-01-31 13:30:41,904] Trial 5 finished with value: 0.8828298915681845 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 2 with value: 0.8979670260565884.
[I 2026-01-31 13:30:54,181] Trial 6 finished with value: 0.8878966187966414 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 2 with value: 0.8979670260565884.
[I 2026-01-31 13:31:01,322] Trial 7 finished with value: 0.8972519386579684 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 2 with value: 0.8979670260565884.
[I 2026-01-31 13:31:05,120] Trial 8 finished with value: 0.8893101928084114 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 2 with value: 0.8979670260565884.
[I 2026-01-31 13:31:13,664] Trial 9 finished with value: 0.8962850228301742 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 2 with value: 0.8979670260565884.
[I 2026-01-31 13:31:18,001] Trial 10 finished with value: 0.8355154185572579 and parameters: {'model': 'GB', 'top_k': 16, 'n_estimators': 202, 'lr': 0.011616568805333773, 'max_depth': 2}. Best is trial 2 with value: 0.8979670260565884.
[I 2026-01-31 13:31:24,577] Trial 11 finished with value: 0.9003504067706188 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 429, 'max_depth': 5, 'lr': 0.021299767484188672, 'subsample': 0.7126544871577369, 'colsample': 0.822167520994149}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:31:29,488] Trial 12 finished with value: 0.8981552088315073 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 447, 'max_depth': 5, 'lr': 0.015250878171623922, 'subsample': 0.701413465894693, 'colsample': 0.7784808970757676}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:31:35,868] Trial 13 finished with value: 0.8922595755267487 and parameters: {'model': 'XGB', 'top_k': 11, 'n_estimators': 458, 'max_depth': 5, 'lr': 0.031037828471827168, 'subsample': 0.7043648866755684, 'colsample': 0.7720216291700391}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:31:40,957] Trial 14 finished with value: 0.8967188320946498 and parameters: {'model': 'XGB', 'top_k': 15, 'n_estimators': 454, 'max_depth': 5, 'lr': 0.01019744026249425, 'subsample': 0.7007216136940275, 'colsample': 0.8454749932457934}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:31:45,344] Trial 15 finished with value: 0.897962672344687 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 494, 'max_depth': 4, 'lr': 0.03959683693972151, 'subsample': 0.974080775782139, 'colsample': 0.7014317680401151}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:31:51,737] Trial 16 finished with value: 0.8873467417743693 and parameters: {'model': 'XGB', 'top_k': 10, 'n_estimators': 425, 'max_depth': 5, 'lr': 0.05450003077475484, 'subsample': 0.7504781866948144, 'colsample': 0.9887903085958019}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:31:59,566] Trial 17 finished with value: 0.8781711798983572 and parameters: {'model': 'GB', 'top_k': 15, 'n_estimators': 414, 'lr': 0.09844175411000243, 'max_depth': 4}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:32:07,827] Trial 18 finished with value: 0.8940333278807977 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 610, 'max_depth': 10}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:32:14,887] Trial 19 finished with value: 0.8970014281089232 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 489, 'max_depth': 5, 'lr': 0.022080707874765522, 'subsample': 0.7466496747749534, 'colsample': 0.794037454742461}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:32:19,542] Trial 20 finished with value: 0.8978032890515436 and parameters: {'model': 'XGB', 'top_k': 14, 'n_estimators': 488, 'max_depth': 4, 'lr': 0.024287496686717376, 'subsample': 0.8620285060340781, 'colsample': 0.8762202275624608}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:32:26,176] Trial 21 finished with value: 0.8985600835856478 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 425, 'max_depth': 5, 'lr': 0.02397796998235555, 'subsample': 0.7713274380075046, 'colsample': 0.8113524074176537}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:32:31,262] Trial 22 finished with value: 0.896745311695582 and parameters: {'model': 'XGB', 'top_k': 17, 'n_estimators': 429, 'max_depth': 5, 'lr': 0.034606179139150026, 'subsample': 0.7355367720628718, 'colsample': 0.8145241498808303}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:32:37,633] Trial 23 finished with value: 0.8962624991270502 and parameters: {'model': 'XGB', 'top_k': 20, 'n_estimators': 463, 'max_depth': 5, 'lr': 0.018830266021540552, 'subsample': 0.785308056055667, 'colsample': 0.7720057500854488}. Best is trial 11 with value: 0.9003504067706188.
[I 2026-01-31 13:32:44,102] Trial 24 finished with value: 0.9023313436894771 and parameters: {'model': 'XGB', 'top_k': 24, 'n_estimators': 519, 'max_depth': 6, 'lr': 0.04870401008492045, 'subsample': 0.7041101141856987, 'colsample': 0.8382924164576472}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:32:52,268] Trial 25 finished with value: 0.8983127939328508 and parameters: {'model': 'XGB', 'top_k': 24, 'n_estimators': 522, 'max_depth': 6, 'lr': 0.049379550141358655, 'subsample': 0.7470809179123455, 'colsample': 0.9006242916504189}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:32:57,356] Trial 26 finished with value: 0.8692305380566718 and parameters: {'model': 'GB', 'top_k': 24, 'n_estimators': 306, 'lr': 0.0692910796961594, 'max_depth': 2}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:33:05,702] Trial 27 finished with value: 0.8956000429189341 and parameters: {'model': 'ET', 'top_k': 20, 'n_estimators': 574, 'max_depth': 9}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:33:19,365] Trial 28 finished with value: 0.8882823496339363 and parameters: {'model': 'RF', 'top_k': 21, 'n_estimators': 689, 'max_depth': 9}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:33:32,120] Trial 29 finished with value: 0.8879717492690565 and parameters: {'model': 'RF', 'top_k': 17, 'n_estimators': 583, 'max_depth': 16}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:33:38,814] Trial 30 finished with value: 0.8958327800145888 and parameters: {'model': 'XGB', 'top_k': 25, 'n_estimators': 520, 'max_depth': 6, 'lr': 0.03055405170552506, 'subsample': 0.8241958625208106, 'colsample': 0.8327332448751373}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:33:46,642] Trial 31 finished with value: 0.8983318293449927 and parameters: {'model': 'XGB', 'top_k': 24, 'n_estimators': 515, 'max_depth': 6, 'lr': 0.050628496238105336, 'subsample': 0.7367022377750797, 'colsample': 0.9001008777930101}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:33:54,429] Trial 32 finished with value: 0.902110534881112 and parameters: {'model': 'XGB', 'top_k': 22, 'n_estimators': 509, 'max_depth': 6, 'lr': 0.06082175195615798, 'subsample': 0.7275800905055206, 'colsample': 0.9085052156779283}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:34:00,346] Trial 33 finished with value: 0.9002264710966464 and parameters: {'model': 'XGB', 'top_k': 22, 'n_estimators': 410, 'max_depth': 6, 'lr': 0.06504189135361436, 'subsample': 0.7224280973788512, 'colsample': 0.9427880293163925}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:34:08,720] Trial 34 finished with value: 0.8967801460793463 and parameters: {'model': 'XGB', 'top_k': 22, 'n_estimators': 477, 'max_depth': 6, 'lr': 0.06089428783727721, 'subsample': 0.724670387770022, 'colsample': 0.9498452799192316}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:34:14,619] Trial 35 finished with value: 0.8981815650938085 and parameters: {'model': 'XGB', 'top_k': 22, 'n_estimators': 408, 'max_depth': 6, 'lr': 0.06938163144732341, 'subsample': 0.7206107634739346, 'colsample': 0.9494695437270088}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:34:21,276] Trial 36 finished with value: 0.895980716725736 and parameters: {'model': 'ET', 'top_k': 27, 'n_estimators': 351, 'max_depth': 9}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:34:33,233] Trial 37 finished with value: 0.8880788107086138 and parameters: {'model': 'RF', 'top_k': 23, 'n_estimators': 540, 'max_depth': 12}. Best is trial 24 with value: 0.9023313436894771.
[I 2026-01-31 13:34:39,032] Trial 38 finished with value: 0.8939242969803247 and parameters: {'model': 'XGB', 'top_k': 21, 'n_estimators': 506, 'max_depth': 6, 'lr': 0.07821320201615238, 'subsample': 0.7645705314981579, 'colsample': 0.943159623236162}. Best is trial 24 with value: 0.9023313436894771.

[I 2026-01-31 13:34:46,497] A new study created in memory with name: no-name-c3e35a56-4d8b-4432-976c-3bdb3a3c58ca

[I 2026-01-31 13:34:46,490] Trial 39 finished with value: 0.8982963257677309 and parameters: {'model': 'XGB', 'top_k': 23, 'n_estimators': 396, 'max_depth': 6, 'lr': 0.06364337657999859, 'subsample': 0.7201154557508193, 'colsample': 0.9972253739072571}. Best is trial 24 with value: 0.9023313436894771.

🔍 Optimizing for SOC %

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 13:34:54,465] Trial 0 finished with value: 0.8881392369194572 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.8881392369194572.
[I 2026-01-31 13:35:03,332] Trial 1 finished with value: 0.8941776888659472 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.8941776888659472.
[I 2026-01-31 13:35:09,645] Trial 2 finished with value: 0.8988197668829351 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 2 with value: 0.8988197668829351.
[I 2026-01-31 13:35:17,257] Trial 3 finished with value: 0.8870739698562001 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 2 with value: 0.8988197668829351.
[I 2026-01-31 13:35:22,367] Trial 4 finished with value: 0.8908503814835962 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 2 with value: 0.8988197668829351.
[I 2026-01-31 13:35:28,366] Trial 5 finished with value: 0.8823366192606616 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 2 with value: 0.8988197668829351.
[I 2026-01-31 13:35:40,580] Trial 6 finished with value: 0.8885429297873829 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 2 with value: 0.8988197668829351.
[I 2026-01-31 13:35:47,705] Trial 7 finished with value: 0.8984219156796505 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 2 with value: 0.8988197668829351.
[I 2026-01-31 13:35:51,453] Trial 8 finished with value: 0.8897034502240837 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 2 with value: 0.8988197668829351.
[I 2026-01-31 13:35:59,902] Trial 9 finished with value: 0.8959443838286507 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 2 with value: 0.8988197668829351.
[I 2026-01-31 13:36:04,138] Trial 10 finished with value: 0.8355154185999298 and parameters: {'model': 'GB', 'top_k': 16, 'n_estimators': 202, 'lr': 0.011616568805333773, 'max_depth': 2}. Best is trial 2 with value: 0.8988197668829351.
[I 2026-01-31 13:36:09,101] Trial 11 finished with value: 0.8996529276968509 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 429, 'max_depth': 5, 'lr': 0.021299767484188672, 'subsample': 0.7126544871577369, 'colsample': 0.822167520994149}. Best is trial 11 with value: 0.8996529276968509.
[I 2026-01-31 13:36:15,378] Trial 12 finished with value: 0.8990841486591432 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 447, 'max_depth': 5, 'lr': 0.015250878171623922, 'subsample': 0.701413465894693, 'colsample': 0.7784808970757676}. Best is trial 11 with value: 0.8996529276968509.
[I 2026-01-31 13:36:20,204] Trial 13 finished with value: 0.8918745971379565 and parameters: {'model': 'XGB', 'top_k': 11, 'n_estimators': 458, 'max_depth': 5, 'lr': 0.031037828471827168, 'subsample': 0.7043648866755684, 'colsample': 0.7720216291700391}. Best is trial 11 with value: 0.8996529276968509.
[I 2026-01-31 13:36:26,993] Trial 14 finished with value: 0.897167440744794 and parameters: {'model': 'XGB', 'top_k': 15, 'n_estimators': 454, 'max_depth': 5, 'lr': 0.01019744026249425, 'subsample': 0.7007216136940275, 'colsample': 0.8454749932457934}. Best is trial 11 with value: 0.8996529276968509.
[I 2026-01-31 13:36:31,251] Trial 15 finished with value: 0.8981040808044221 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 494, 'max_depth': 4, 'lr': 0.03959683693972151, 'subsample': 0.974080775782139, 'colsample': 0.7014317680401151}. Best is trial 11 with value: 0.8996529276968509.
[I 2026-01-31 13:36:37,657] Trial 16 finished with value: 0.8846631957282772 and parameters: {'model': 'XGB', 'top_k': 10, 'n_estimators': 425, 'max_depth': 5, 'lr': 0.05450003077475484, 'subsample': 0.7504781866948144, 'colsample': 0.9887903085958019}. Best is trial 11 with value: 0.8996529276968509.
[I 2026-01-31 13:36:45,105] Trial 17 finished with value: 0.8780717613027917 and parameters: {'model': 'GB', 'top_k': 15, 'n_estimators': 414, 'lr': 0.09844175411000243, 'max_depth': 4}. Best is trial 11 with value: 0.8996529276968509.
[I 2026-01-31 13:36:53,936] Trial 18 finished with value: 0.894348071212743 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 610, 'max_depth': 10}. Best is trial 11 with value: 0.8996529276968509.
[I 2026-01-31 13:36:59,256] Trial 19 finished with value: 0.8975013546670019 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 489, 'max_depth': 5, 'lr': 0.022080707874765522, 'subsample': 0.7466496747749534, 'colsample': 0.794037454742461}. Best is trial 11 with value: 0.8996529276968509.
[I 2026-01-31 13:37:05,421] Trial 20 finished with value: 0.8982858221908098 and parameters: {'model': 'XGB', 'top_k': 14, 'n_estimators': 488, 'max_depth': 4, 'lr': 0.024287496686717376, 'subsample': 0.8620285060340781, 'colsample': 0.8762202275624608}. Best is trial 11 with value: 0.8996529276968509.
[I 2026-01-31 13:37:10,308] Trial 21 finished with value: 0.898131626526937 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 425, 'max_depth': 5, 'lr': 0.02397796998235555, 'subsample': 0.7713274380075046, 'colsample': 0.8113524074176537}. Best is trial 11 with value: 0.8996529276968509.
[I 2026-01-31 13:37:16,685] Trial 22 finished with value: 0.9011621585056411 and parameters: {'model': 'XGB', 'top_k': 24, 'n_estimators': 400, 'max_depth': 5, 'lr': 0.035254406226914836, 'subsample': 0.7036767753380551, 'colsample': 0.8106747055940192}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:37:21,667] Trial 23 finished with value: 0.8980834284128505 and parameters: {'model': 'XGB', 'top_k': 24, 'n_estimators': 464, 'max_depth': 5, 'lr': 0.036902455876124896, 'subsample': 0.7061812618954979, 'colsample': 0.7720057500854488}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:37:28,987] Trial 24 finished with value: 0.8953273805260981 and parameters: {'model': 'XGB', 'top_k': 20, 'n_estimators': 414, 'max_depth': 6, 'lr': 0.05180991564344288, 'subsample': 0.7395284725653957, 'colsample': 0.837663800564902}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:37:34,357] Trial 25 finished with value: 0.8977159885007522 and parameters: {'model': 'XGB', 'top_k': 24, 'n_estimators': 520, 'max_depth': 5, 'lr': 0.016369943615206974, 'subsample': 0.7273828681940361, 'colsample': 0.7572015663860014}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:37:42,599] Trial 26 finished with value: 0.8948357635812952 and parameters: {'model': 'ET', 'top_k': 16, 'n_estimators': 557, 'max_depth': 9}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:37:56,239] Trial 27 finished with value: 0.8884541607283737 and parameters: {'model': 'RF', 'top_k': 21, 'n_estimators': 696, 'max_depth': 9}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:38:01,408] Trial 28 finished with value: 0.8698524072846693 and parameters: {'model': 'GB', 'top_k': 26, 'n_estimators': 325, 'lr': 0.030246475074202608, 'max_depth': 2}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:38:10,563] Trial 29 finished with value: 0.8872518207809776 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 352, 'max_depth': 16}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:38:14,774] Trial 30 finished with value: 0.8873019117454971 and parameters: {'model': 'XGB', 'top_k': 10, 'n_estimators': 438, 'max_depth': 4, 'lr': 0.04437996506115839, 'subsample': 0.8241958625208106, 'colsample': 0.891251517657503}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:38:21,118] Trial 31 finished with value: 0.8976431602717211 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 391, 'max_depth': 5, 'lr': 0.019356460020996166, 'subsample': 0.792845070469449, 'colsample': 0.8125604131483616}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:38:25,885] Trial 32 finished with value: 0.897574695469608 and parameters: {'model': 'XGB', 'top_k': 17, 'n_estimators': 378, 'max_depth': 5, 'lr': 0.031612869062993626, 'subsample': 0.7341220529959236, 'colsample': 0.819504633044625}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:38:32,382] Trial 33 finished with value: 0.8978340883735795 and parameters: {'model': 'XGB', 'top_k': 22, 'n_estimators': 404, 'max_depth': 5, 'lr': 0.01699724347426226, 'subsample': 0.7680954321293225, 'colsample': 0.7964771601612846}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:38:37,511] Trial 34 finished with value: 0.8988198840906445 and parameters: {'model': 'XGB', 'top_k': 20, 'n_estimators': 472, 'max_depth': 5, 'lr': 0.028058825641462837, 'subsample': 0.7008486515168862, 'colsample': 0.7359542644015846}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:38:44,142] Trial 35 finished with value: 0.8982602573946734 and parameters: {'model': 'XGB', 'top_k': 20, 'n_estimators': 472, 'max_depth': 5, 'lr': 0.029573348508165058, 'subsample': 0.7013896333493522, 'colsample': 0.7259016930431414}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:38:51,223] Trial 36 finished with value: 0.8947131518836867 and parameters: {'model': 'ET', 'top_k': 23, 'n_estimators': 519, 'max_depth': 9}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:39:01,543] Trial 37 finished with value: 0.8877489411579749 and parameters: {'model': 'RF', 'top_k': 25, 'n_estimators': 435, 'max_depth': 12}. Best is trial 22 with value: 0.9011621585056411.
[I 2026-01-31 13:39:07,205] Trial 38 finished with value: 0.8941382553236487 and parameters: {'model': 'XGB', 'top_k': 28, 'n_estimators': 439, 'max_depth': 4, 'lr': 0.04820389138433619, 'subsample': 0.7280326649561261, 'colsample': 0.7507572251108771}. Best is trial 22 with value: 0.9011621585056411.

[I 2026-01-31 13:39:12,357] A new study created in memory with name: no-name-38e1c8c3-8032-4e63-8f8d-6d825e949f0e

[I 2026-01-31 13:39:12,341] Trial 39 finished with value: 0.8962833843606102 and parameters: {'model': 'XGB', 'top_k': 22, 'n_estimators': 471, 'max_depth': 5, 'lr': 0.03426785665254988, 'subsample': 0.7229435944312872, 'colsample': 0.7772337873509249}. Best is trial 22 with value: 0.9011621585056411.

🔍 Optimizing for Ca+2 mg/L

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 13:39:21,106] Trial 0 finished with value: 0.8513860012649452 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.8513860012649452.
[I 2026-01-31 13:39:29,181] Trial 1 finished with value: 0.8676614929677703 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.8676614929677703.
[I 2026-01-31 13:39:35,527] Trial 2 finished with value: 0.8618211779834969 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.8676614929677703.
[I 2026-01-31 13:39:43,397] Trial 3 finished with value: 0.8519292687102 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.8676614929677703.
[I 2026-01-31 13:39:47,950] Trial 4 finished with value: 0.852954236969485 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.8676614929677703.
[I 2026-01-31 13:39:53,967] Trial 5 finished with value: 0.8370781056641509 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.8676614929677703.
[I 2026-01-31 13:40:05,910] Trial 6 finished with value: 0.8501784445572721 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.8676614929677703.
[I 2026-01-31 13:40:12,865] Trial 7 finished with value: 0.8605214834724617 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.8676614929677703.
[I 2026-01-31 13:40:16,548] Trial 8 finished with value: 0.8526847346196285 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.8676614929677703.
[I 2026-01-31 13:40:25,096] Trial 9 finished with value: 0.8671834475077114 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 1 with value: 0.8676614929677703.
[I 2026-01-31 13:40:33,458] Trial 10 finished with value: 0.8732327875718818 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 688, 'max_depth': 12}. Best is trial 10 with value: 0.8732327875718818.
[I 2026-01-31 13:40:42,594] Trial 11 finished with value: 0.8731344736431443 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 695, 'max_depth': 12}. Best is trial 10 with value: 0.8732327875718818.
[I 2026-01-31 13:40:52,107] Trial 12 finished with value: 0.8731588951607527 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 699, 'max_depth': 15}. Best is trial 10 with value: 0.8732327875718818.
[I 2026-01-31 13:41:02,338] Trial 13 finished with value: 0.8671964019383356 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 698, 'max_depth': 16}. Best is trial 10 with value: 0.8732327875718818.
[I 2026-01-31 13:41:10,508] Trial 14 finished with value: 0.8738657067575396 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 629, 'max_depth': 17}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:41:15,737] Trial 15 finished with value: 0.8455269675431953 and parameters: {'model': 'GB', 'top_k': 15, 'n_estimators': 231, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:41:24,097] Trial 16 finished with value: 0.8731083391236585 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 585, 'max_depth': 18}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:41:33,085] Trial 17 finished with value: 0.8670292330371708 and parameters: {'model': 'ET', 'top_k': 16, 'n_estimators': 632, 'max_depth': 13}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:41:41,269] Trial 18 finished with value: 0.8667409263086607 and parameters: {'model': 'ET', 'top_k': 17, 'n_estimators': 485, 'max_depth': 17}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:41:48,794] Trial 19 finished with value: 0.8388632432228196 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 441, 'lr': 0.09983831247079358, 'max_depth': 4}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:41:58,176] Trial 20 finished with value: 0.8676460842982848 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 629, 'max_depth': 20}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:42:07,461] Trial 21 finished with value: 0.8735724831906557 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 668, 'max_depth': 14}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:42:16,589] Trial 22 finished with value: 0.8735289304411825 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 658, 'max_depth': 14}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:42:24,468] Trial 23 finished with value: 0.8730463548013742 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 593, 'max_depth': 14}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:42:34,241] Trial 24 finished with value: 0.8673578580542998 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 659, 'max_depth': 17}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:42:42,958] Trial 25 finished with value: 0.8722612199320438 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 585, 'max_depth': 14}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:42:52,192] Trial 26 finished with value: 0.8670916401094988 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 659, 'max_depth': 16}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:42:59,858] Trial 27 finished with value: 0.8351009426387261 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 465, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:43:11,400] Trial 28 finished with value: 0.8532091922587653 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 537, 'max_depth': 14}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:43:24,618] Trial 29 finished with value: 0.8496945864993419 and parameters: {'model': 'RF', 'top_k': 16, 'n_estimators': 660, 'max_depth': 10}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:43:33,554] Trial 30 finished with value: 0.8703914272990925 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 607, 'max_depth': 13}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:43:41,845] Trial 31 finished with value: 0.8734327798883715 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 674, 'max_depth': 11}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:43:50,797] Trial 32 finished with value: 0.8725382465310758 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 665, 'max_depth': 11}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:43:59,532] Trial 33 finished with value: 0.8701856875655712 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 617, 'max_depth': 10}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:44:08,952] Trial 34 finished with value: 0.8732022067219247 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 650, 'max_depth': 16}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:44:16,338] Trial 35 finished with value: 0.8688861037145232 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 571, 'max_depth': 9}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:44:23,273] Trial 36 finished with value: 0.8615125372213729 and parameters: {'model': 'XGB', 'top_k': 10, 'n_estimators': 565, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:44:37,372] Trial 37 finished with value: 0.8500490104792917 and parameters: {'model': 'RF', 'top_k': 20, 'n_estimators': 678, 'max_depth': 15}. Best is trial 14 with value: 0.8738657067575396.
[I 2026-01-31 13:44:46,613] Trial 38 finished with value: 0.8671540268316796 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 644, 'max_depth': 13}. Best is trial 14 with value: 0.8738657067575396.

[I 2026-01-31 13:44:51,654] A new study created in memory with name: no-name-83e5ef1a-556c-48d2-8d1d-27464b54e336

[I 2026-01-31 13:44:51,642] Trial 39 finished with value: 0.8597426635910821 and parameters: {'model': 'XGB', 'top_k': 24, 'n_estimators': 509, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 14 with value: 0.8738657067575396.

🔍 Optimizing for Mg+2 mg/L

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 13:45:00,491] Trial 0 finished with value: 0.4925872070638627 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.4925872070638627.
[I 2026-01-31 13:45:08,475] Trial 1 finished with value: 0.697517827951538 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.697517827951538.
[I 2026-01-31 13:45:14,769] Trial 2 finished with value: 0.456946662794793 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.697517827951538.
[I 2026-01-31 13:45:23,526] Trial 3 finished with value: 0.5069004649647864 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.697517827951538.
[I 2026-01-31 13:45:27,261] Trial 4 finished with value: 0.4521472455622305 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.697517827951538.
[I 2026-01-31 13:45:33,303] Trial 5 finished with value: 0.6007144093033957 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.697517827951538.
[I 2026-01-31 13:45:45,650] Trial 6 finished with value: 0.5081710922672472 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.697517827951538.
[I 2026-01-31 13:45:52,963] Trial 7 finished with value: 0.4461444071707442 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.697517827951538.
[I 2026-01-31 13:45:56,670] Trial 8 finished with value: 0.46740168559013695 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.697517827951538.
[I 2026-01-31 13:46:04,947] Trial 9 finished with value: 0.6895853284363321 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 1 with value: 0.697517827951538.
[I 2026-01-31 13:46:14,149] Trial 10 finished with value: 0.7151348203215365 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 688, 'max_depth': 12}. Best is trial 10 with value: 0.7151348203215365.
[I 2026-01-31 13:46:22,560] Trial 11 finished with value: 0.7144383042152127 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 695, 'max_depth': 12}. Best is trial 10 with value: 0.7151348203215365.
[I 2026-01-31 13:46:32,053] Trial 12 finished with value: 0.7126569075227656 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 699, 'max_depth': 15}. Best is trial 10 with value: 0.7151348203215365.
[I 2026-01-31 13:46:41,723] Trial 13 finished with value: 0.7007648643424528 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 698, 'max_depth': 13}. Best is trial 10 with value: 0.7151348203215365.
[I 2026-01-31 13:46:49,681] Trial 14 finished with value: 0.7191647751951435 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 629, 'max_depth': 11}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:46:54,768] Trial 15 finished with value: 0.5832635274863455 and parameters: {'model': 'GB', 'top_k': 15, 'n_estimators': 231, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:47:03,272] Trial 16 finished with value: 0.7101361913974642 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 585, 'max_depth': 17}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:47:11,646] Trial 17 finished with value: 0.6975246518102857 and parameters: {'model': 'ET', 'top_k': 16, 'n_estimators': 632, 'max_depth': 10}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:47:19,269] Trial 18 finished with value: 0.694116667700276 and parameters: {'model': 'ET', 'top_k': 17, 'n_estimators': 485, 'max_depth': 10}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:47:24,991] Trial 19 finished with value: 0.6103731829160717 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 441, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:47:34,431] Trial 20 finished with value: 0.6859137522040772 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 629, 'max_depth': 14}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:47:43,501] Trial 21 finished with value: 0.7161049155797053 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 667, 'max_depth': 12}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:47:51,615] Trial 22 finished with value: 0.7189748422128224 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 658, 'max_depth': 11}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:48:00,164] Trial 23 finished with value: 0.7084254516697188 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 593, 'max_depth': 11}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:48:09,076] Trial 24 finished with value: 0.6944608357850017 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 659, 'max_depth': 9}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:48:16,845] Trial 25 finished with value: 0.6990765064217408 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 585, 'max_depth': 13}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:48:26,106] Trial 26 finished with value: 0.6934163400058273 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 659, 'max_depth': 11}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:48:34,050] Trial 27 finished with value: 0.6574395864782238 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 465, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:48:45,755] Trial 28 finished with value: 0.5009176295691781 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 537, 'max_depth': 14}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:48:59,505] Trial 29 finished with value: 0.5085336019660813 and parameters: {'model': 'RF', 'top_k': 16, 'n_estimators': 660, 'max_depth': 11}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:49:07,130] Trial 30 finished with value: 0.6834543538163326 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 607, 'max_depth': 9}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:49:16,277] Trial 31 finished with value: 0.7159406344697004 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 674, 'max_depth': 12}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:49:25,532] Trial 32 finished with value: 0.7013984653576382 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 665, 'max_depth': 13}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:49:33,836] Trial 33 finished with value: 0.6917809991428794 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 617, 'max_depth': 11}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:49:42,281] Trial 34 finished with value: 0.7014244388064561 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 650, 'max_depth': 12}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:49:50,448] Trial 35 finished with value: 0.6852015643518767 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 570, 'max_depth': 9}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:49:55,378] Trial 36 finished with value: 0.5074263504496046 and parameters: {'model': 'XGB', 'top_k': 10, 'n_estimators': 565, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:50:09,219] Trial 37 finished with value: 0.5016434683928479 and parameters: {'model': 'RF', 'top_k': 20, 'n_estimators': 678, 'max_depth': 10}. Best is trial 14 with value: 0.7191647751951435.
[I 2026-01-31 13:50:18,722] Trial 38 finished with value: 0.6866335195962339 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 644, 'max_depth': 14}. Best is trial 14 with value: 0.7191647751951435.

[I 2026-01-31 13:50:25,444] A new study created in memory with name: no-name-040010bc-8bf7-4107-bf2b-fbe22981ba41

[I 2026-01-31 13:50:25,433] Trial 39 finished with value: 0.4885696115395753 and parameters: {'model': 'XGB', 'top_k': 24, 'n_estimators': 509, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 14 with value: 0.7191647751951435.

🔍 Optimizing for K+1 mg/L

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 13:50:33,197] Trial 0 finished with value: 0.4955575391406386 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.4955575391406386.
[I 2026-01-31 13:50:42,091] Trial 1 finished with value: 0.601463527100299 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:50:46,843] Trial 2 finished with value: 0.4666974683944535 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:50:55,679] Trial 3 finished with value: 0.500079191103336 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:50:59,346] Trial 4 finished with value: 0.35526434357578285 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:51:06,035] Trial 5 finished with value: 0.09657627426468836 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:51:18,399] Trial 6 finished with value: 0.4882820937170598 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:51:23,987] Trial 7 finished with value: 0.39742068308827944 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:51:29,000] Trial 8 finished with value: 0.27340473137903876 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:51:36,537] Trial 9 finished with value: 0.5914174849411343 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:51:45,812] Trial 10 finished with value: 0.5433488148564016 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 688, 'max_depth': 12}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:51:54,658] Trial 11 finished with value: 0.586238203615397 and parameters: {'model': 'ET', 'top_k': 29, 'n_estimators': 599, 'max_depth': 12}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:52:02,741] Trial 12 finished with value: 0.5992290316981461 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 623, 'max_depth': 11}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:52:11,982] Trial 13 finished with value: 0.6007484662887532 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 682, 'max_depth': 10}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:52:21,223] Trial 14 finished with value: 0.6010092715487614 and parameters: {'model': 'ET', 'top_k': 23, 'n_estimators': 685, 'max_depth': 10}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:52:27,067] Trial 15 finished with value: 0.39884661235967533 and parameters: {'model': 'GB', 'top_k': 16, 'n_estimators': 434, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:52:36,495] Trial 16 finished with value: 0.5963974217683354 and parameters: {'model': 'ET', 'top_k': 23, 'n_estimators': 635, 'max_depth': 15}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:52:43,942] Trial 17 finished with value: 0.6011232559719908 and parameters: {'model': 'ET', 'top_k': 25, 'n_estimators': 467, 'max_depth': 9}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:52:51,010] Trial 18 finished with value: 0.587432410046336 and parameters: {'model': 'ET', 'top_k': 26, 'n_estimators': 466, 'max_depth': 18}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:52:56,133] Trial 19 finished with value: 0.3654150921109857 and parameters: {'model': 'GB', 'top_k': 25, 'n_estimators': 204, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 1 with value: 0.601463527100299.
[I 2026-01-31 13:53:03,060] Trial 20 finished with value: 0.6022335243643565 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 507, 'max_depth': 9}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:53:10,799] Trial 21 finished with value: 0.6022335243643565 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 507, 'max_depth': 9}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:53:18,174] Trial 22 finished with value: 0.6016008598252327 and parameters: {'model': 'ET', 'top_k': 17, 'n_estimators': 537, 'max_depth': 9}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:53:25,950] Trial 23 finished with value: 0.6016636555106336 and parameters: {'model': 'ET', 'top_k': 16, 'n_estimators': 536, 'max_depth': 9}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:53:33,968] Trial 24 finished with value: 0.5938112799717346 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 498, 'max_depth': 13}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:53:41,347] Trial 25 finished with value: 0.6018362653780428 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 578, 'max_depth': 9}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:53:50,387] Trial 26 finished with value: 0.5873037999560995 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 580, 'max_depth': 17}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:53:58,589] Trial 27 finished with value: 0.20787551266634557 and parameters: {'model': 'GB', 'top_k': 20, 'n_estimators': 423, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:54:09,881] Trial 28 finished with value: 0.4900235663086219 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 501, 'max_depth': 11}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:54:21,048] Trial 29 finished with value: 0.4445000728434092 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 573, 'max_depth': 9}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:54:29,233] Trial 30 finished with value: 0.5979845634221129 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 512, 'max_depth': 14}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:54:36,708] Trial 31 finished with value: 0.6011232559719908 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 467, 'max_depth': 9}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:54:44,055] Trial 32 finished with value: 0.5987851159795953 and parameters: {'model': 'ET', 'top_k': 18, 'n_estimators': 521, 'max_depth': 11}. Best is trial 20 with value: 0.6022335243643565.
[I 2026-01-31 13:54:52,529] Trial 33 finished with value: 0.6058196290828116 and parameters: {'model': 'ET', 'top_k': 20, 'n_estimators': 558, 'max_depth': 10}. Best is trial 33 with value: 0.6058196290828116.
[I 2026-01-31 13:55:01,133] Trial 34 finished with value: 0.6049652249315306 and parameters: {'model': 'ET', 'top_k': 20, 'n_estimators': 569, 'max_depth': 10}. Best is trial 33 with value: 0.6058196290828116.
[I 2026-01-31 13:55:09,247] Trial 35 finished with value: 0.6003112227252538 and parameters: {'model': 'ET', 'top_k': 20, 'n_estimators': 608, 'max_depth': 10}. Best is trial 33 with value: 0.6058196290828116.
[I 2026-01-31 13:55:15,985] Trial 36 finished with value: 0.4012243924589719 and parameters: {'model': 'XGB', 'top_k': 21, 'n_estimators': 487, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 33 with value: 0.6058196290828116.
[I 2026-01-31 13:55:29,556] Trial 37 finished with value: 0.48840392429789636 and parameters: {'model': 'RF', 'top_k': 19, 'n_estimators': 645, 'max_depth': 11}. Best is trial 33 with value: 0.6058196290828116.
[I 2026-01-31 13:55:38,288] Trial 38 finished with value: 0.5825621453624763 and parameters: {'model': 'ET', 'top_k': 22, 'n_estimators': 567, 'max_depth': 13}. Best is trial 33 with value: 0.6058196290828116.

[I 2026-01-31 13:55:43,550] A new study created in memory with name: no-name-df3d74f2-0c14-4272-bd4e-b15572118c1d

[I 2026-01-31 13:55:43,544] Trial 39 finished with value: 0.46754532317486497 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 552, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 33 with value: 0.6058196290828116.

🔍 Optimizing for Na+1 mg/L

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 13:55:52,373] Trial 0 finished with value: 0.24031901697786937 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:56:00,315] Trial 1 finished with value: 0.2070452298627785 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:56:06,376] Trial 2 finished with value: 0.03055360849617863 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:56:15,457] Trial 3 finished with value: 0.2389487801204359 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:56:19,136] Trial 4 finished with value: 0.09039367474025073 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:56:25,125] Trial 5 finished with value: 0.1585165190689107 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:56:38,037] Trial 6 finished with value: 0.23214653166553045 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:56:44,914] Trial 7 finished with value: 0.024796766460838414 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:56:48,568] Trial 8 finished with value: 0.1171421004131872 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:56:56,849] Trial 9 finished with value: 0.15759246300188862 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:57:07,080] Trial 10 finished with value: 0.16891296126136224 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 472, 'max_depth': 10}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:57:14,964] Trial 11 finished with value: 0.22839857043723502 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 306, 'max_depth': 16}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:57:26,312] Trial 12 finished with value: 0.23591438567792805 and parameters: {'model': 'RF', 'top_k': 15, 'n_estimators': 449, 'max_depth': 15}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:57:37,661] Trial 13 finished with value: 0.2353983524360272 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 437, 'max_depth': 18}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:57:42,246] Trial 14 finished with value: 0.09660970075435009 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 213, 'lr': 0.011073188101939947, 'max_depth': 2}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:57:57,053] Trial 15 finished with value: 0.22876225990357382 and parameters: {'model': 'RF', 'top_k': 16, 'n_estimators': 649, 'max_depth': 13}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:58:05,316] Trial 16 finished with value: 0.23496492273505692 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 328, 'max_depth': 17}. Best is trial 0 with value: 0.24031901697786937.
[I 2026-01-31 13:58:16,655] Trial 17 finished with value: 0.24269331085913678 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 514, 'max_depth': 11}. Best is trial 17 with value: 0.24269331085913678.
[I 2026-01-31 13:58:24,821] Trial 18 finished with value: 0.19699153764650146 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 585, 'max_depth': 9}. Best is trial 17 with value: 0.24269331085913678.
[I 2026-01-31 13:58:30,349] Trial 19 finished with value: 0.18816896483263193 and parameters: {'model': 'GB', 'top_k': 13, 'n_estimators': 258, 'lr': 0.09983831247079358, 'max_depth': 4}. Best is trial 17 with value: 0.24269331085913678.
[I 2026-01-31 13:58:41,319] Trial 20 finished with value: 0.23537002295220702 and parameters: {'model': 'RF', 'top_k': 17, 'n_estimators': 498, 'max_depth': 9}. Best is trial 17 with value: 0.24269331085913678.
[I 2026-01-31 13:58:51,766] Trial 21 finished with value: 0.2386911427030876 and parameters: {'model': 'RF', 'top_k': 20, 'n_estimators': 418, 'max_depth': 12}. Best is trial 17 with value: 0.24269331085913678.
[I 2026-01-31 13:59:06,534] Trial 22 finished with value: 0.22391674933450387 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 691, 'max_depth': 14}. Best is trial 17 with value: 0.24269331085913678.
[I 2026-01-31 13:59:17,221] Trial 23 finished with value: 0.1353210294777103 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 494, 'max_depth': 11}. Best is trial 17 with value: 0.24269331085913678.
[I 2026-01-31 13:59:29,851] Trial 24 finished with value: 0.23171983969476778 and parameters: {'model': 'RF', 'top_k': 20, 'n_estimators': 547, 'max_depth': 14}. Best is trial 17 with value: 0.24269331085913678.
[I 2026-01-31 13:59:38,782] Trial 25 finished with value: 0.2442607321947805 and parameters: {'model': 'RF', 'top_k': 24, 'n_estimators': 357, 'max_depth': 9}. Best is trial 25 with value: 0.2442607321947805.
[I 2026-01-31 13:59:48,295] Trial 26 finished with value: 0.2396307126535609 and parameters: {'model': 'RF', 'top_k': 24, 'n_estimators': 410, 'max_depth': 9}. Best is trial 25 with value: 0.2442607321947805.
[I 2026-01-31 13:59:54,206] Trial 27 finished with value: 0.21464655744946964 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 359, 'max_depth': 10}. Best is trial 25 with value: 0.2442607321947805.
[I 2026-01-31 14:00:00,657] Trial 28 finished with value: 0.19181186491784757 and parameters: {'model': 'GB', 'top_k': 25, 'n_estimators': 273, 'lr': 0.041419357059636994, 'max_depth': 4}. Best is trial 25 with value: 0.2442607321947805.
[I 2026-01-31 14:00:08,792] Trial 29 finished with value: 0.17917803420103776 and parameters: {'model': 'ET', 'top_k': 29, 'n_estimators': 599, 'max_depth': 11}. Best is trial 25 with value: 0.2442607321947805.
[I 2026-01-31 14:00:19,111] Trial 30 finished with value: 0.2476549470608976 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 464, 'max_depth': 9}. Best is trial 30 with value: 0.2476549470608976.
[I 2026-01-31 14:00:29,375] Trial 31 finished with value: 0.2465023995173782 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 469, 'max_depth': 9}. Best is trial 30 with value: 0.2476549470608976.
[I 2026-01-31 14:00:40,341] Trial 32 finished with value: 0.24294017081841365 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 521, 'max_depth': 9}. Best is trial 30 with value: 0.2476549470608976.
[I 2026-01-31 14:00:49,495] Trial 33 finished with value: 0.2461176183891181 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 456, 'max_depth': 9}. Best is trial 30 with value: 0.2476549470608976.
[I 2026-01-31 14:01:00,051] Trial 34 finished with value: 0.23054126885077714 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 470, 'max_depth': 10}. Best is trial 30 with value: 0.2476549470608976.
[I 2026-01-31 14:01:09,929] Trial 35 finished with value: 0.139923406160885 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 462, 'max_depth': 9}. Best is trial 30 with value: 0.2476549470608976.
[I 2026-01-31 14:01:15,963] Trial 36 finished with value: 0.10049507644098161 and parameters: {'model': 'XGB', 'top_k': 17, 'n_estimators': 441, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 30 with value: 0.2476549470608976.
[I 2026-01-31 14:01:24,830] Trial 37 finished with value: 0.16300031111318808 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 406, 'max_depth': 12}. Best is trial 30 with value: 0.2476549470608976.
[I 2026-01-31 14:01:35,227] Trial 38 finished with value: 0.23792480782362757 and parameters: {'model': 'RF', 'top_k': 20, 'n_estimators': 426, 'max_depth': 11}. Best is trial 30 with value: 0.2476549470608976.

[I 2026-01-31 14:01:41,680] A new study created in memory with name: no-name-d46456f9-91f0-4c77-bac3-14114f344a59

[I 2026-01-31 14:01:41,668] Trial 39 finished with value: 0.14697203759883376 and parameters: {'model': 'XGB', 'top_k': 14, 'n_estimators': 488, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 30 with value: 0.2476549470608976.

🔍 Optimizing for CEC meq/100g

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-31 14:01:49,598] Trial 0 finished with value: 0.808535072937399 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.808535072937399.
[I 2026-01-31 14:01:58,446] Trial 1 finished with value: 0.8680844416536019 and parameters: {'model': 'ET', 'top_k': 30, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.8680844416536019.
[I 2026-01-31 14:02:03,179] Trial 2 finished with value: 0.8369688731404474 and parameters: {'model': 'XGB', 'top_k': 19, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.8680844416536019.
[I 2026-01-31 14:02:11,890] Trial 3 finished with value: 0.8081423275960358 and parameters: {'model': 'RF', 'top_k': 22, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.8680844416536019.
[I 2026-01-31 14:02:15,598] Trial 4 finished with value: 0.8294613525306822 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.8680844416536019.
[I 2026-01-31 14:02:22,408] Trial 5 finished with value: 0.8199825953931728 and parameters: {'model': 'GB', 'top_k': 23, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.8680844416536019.
[I 2026-01-31 14:02:34,546] Trial 6 finished with value: 0.8072321656659259 and parameters: {'model': 'RF', 'top_k': 28, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.8680844416536019.
[I 2026-01-31 14:02:40,013] Trial 7 finished with value: 0.8312719928199238 and parameters: {'model': 'XGB', 'top_k': 18, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.8680844416536019.
[I 2026-01-31 14:02:45,090] Trial 8 finished with value: 0.8262321407951043 and parameters: {'model': 'XGB', 'top_k': 26, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.8680844416536019.
[I 2026-01-31 14:02:52,627] Trial 9 finished with value: 0.8683875028930883 and parameters: {'model': 'ET', 'top_k': 28, 'n_estimators': 549, 'max_depth': 12}. Best is trial 9 with value: 0.8683875028930883.
[I 2026-01-31 14:03:01,840] Trial 10 finished with value: 0.8754678620356641 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 688, 'max_depth': 13}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:03:11,533] Trial 11 finished with value: 0.8753025368598124 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 694, 'max_depth': 13}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:03:20,327] Trial 12 finished with value: 0.8746000816110693 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 699, 'max_depth': 15}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:03:30,015] Trial 13 finished with value: 0.8674508103471901 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 698, 'max_depth': 13}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:03:39,028] Trial 14 finished with value: 0.872895646022911 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 629, 'max_depth': 17}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:03:45,040] Trial 15 finished with value: 0.826016879462778 and parameters: {'model': 'GB', 'top_k': 15, 'n_estimators': 444, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:03:53,786] Trial 16 finished with value: 0.8716281673944533 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 635, 'max_depth': 11}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:04:02,601] Trial 17 finished with value: 0.8678074792919986 and parameters: {'model': 'ET', 'top_k': 16, 'n_estimators': 583, 'max_depth': 14}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:04:09,884] Trial 18 finished with value: 0.867634978784538 and parameters: {'model': 'ET', 'top_k': 17, 'n_estimators': 485, 'max_depth': 17}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:04:15,301] Trial 19 finished with value: 0.8237416242151312 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 258, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:04:24,008] Trial 20 finished with value: 0.867851663082307 and parameters: {'model': 'ET', 'top_k': 21, 'n_estimators': 667, 'max_depth': 10}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:04:32,740] Trial 21 finished with value: 0.8747401445771494 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 680, 'max_depth': 15}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:04:41,509] Trial 22 finished with value: 0.8750834156121055 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 605, 'max_depth': 16}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:04:50,458] Trial 23 finished with value: 0.8701229820987095 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 594, 'max_depth': 17}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:04:58,758] Trial 24 finished with value: 0.8677338568320513 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 658, 'max_depth': 13}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:05:07,540] Trial 25 finished with value: 0.8739968043654518 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 597, 'max_depth': 20}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:05:17,120] Trial 26 finished with value: 0.8687447284984249 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 651, 'max_depth': 16}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:05:24,180] Trial 27 finished with value: 0.8132729727672586 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 463, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:05:36,077] Trial 28 finished with value: 0.8092511889123577 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 552, 'max_depth': 13}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:05:49,023] Trial 29 finished with value: 0.8074443023016349 and parameters: {'model': 'RF', 'top_k': 16, 'n_estimators': 609, 'max_depth': 12}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:05:58,532] Trial 30 finished with value: 0.8697137354218629 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 670, 'max_depth': 14}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:06:07,956] Trial 31 finished with value: 0.8749063119985656 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 684, 'max_depth': 15}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:06:16,667] Trial 32 finished with value: 0.8731206115310159 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 632, 'max_depth': 16}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:06:26,133] Trial 33 finished with value: 0.8691063762762807 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 698, 'max_depth': 18}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:06:34,832] Trial 34 finished with value: 0.8727115845974222 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 576, 'max_depth': 16}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:06:43,443] Trial 35 finished with value: 0.8735298105761633 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 618, 'max_depth': 12}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:06:48,717] Trial 36 finished with value: 0.8160644452830554 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 577, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:07:02,366] Trial 37 finished with value: 0.8074795303011653 and parameters: {'model': 'RF', 'top_k': 20, 'n_estimators': 648, 'max_depth': 14}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:07:12,071] Trial 38 finished with value: 0.8680659609537811 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 677, 'max_depth': 15}. Best is trial 10 with value: 0.8754678620356641.
[I 2026-01-31 14:07:17,121] Trial 39 finished with value: 0.8343759776233994 and parameters: {'model': 'XGB', 'top_k': 24, 'n_estimators': 518, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 10 with value: 0.8754678620356641.

In [ ]:
results_df = pd.DataFrame(results)
results_df

,Target,Best R2 (CV mean),Best Params
0,Soil EC (us/cm),0.366190,"{'model': 'ET', 'top_k': 27, 'n_estimators': 5..."
1,Soil pH,0.715183,"{'model': 'ET', 'top_k': 10, 'n_estimators': 6..."
2,Sand (%),0.508712,"{'model': 'ET', 'top_k': 29, 'n_estimators': 5..."
3,Silt %,0.470632,"{'model': 'ET', 'top_k': 10, 'n_estimators': 6..."
4,Clay (%),0.585486,"{'model': 'ET', 'top_k': 11, 'n_estimators': 5..."
5,SOM%,0.902331,"{'model': 'XGB', 'top_k': 24, 'n_estimators': ..."
6,SOC %,0.901162,"{'model': 'XGB', 'top_k': 24, 'n_estimators': ..."
7,Ca+2 mg/L,0.873866,"{'model': 'ET', 'top_k': 10, 'n_estimators': 6..."
8,Mg+2 mg/L,0.719165,"{'model': 'ET', 'top_k': 10, 'n_estimators': 6..."
9,K+1 mg/L,0.605820,"{'model': 'ET', 'top_k': 20, 'n_estimators': 5..."
10,Na+1 mg/L,0.247655,"{'model': 'RF', 'top_k': 12, 'n_estimators': 4..."
11,CEC meq/100g,0.875468,"{'model': 'ET', 'top_k': 10, 'n_estimators': 6..."

In [ ]:
results_df.to_csv('haiti_part1_models_hp_pxrf_nix.csv')