In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.1)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.45)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.7.0-py3-none-any.whl (413 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 8.5 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.7.0

In [ ]:
import pandas as pd
import numpy as np
import optuna

from sklearn.model_selection import KFold
from sklearn.metrics import r2_score

from sklearn.ensemble import (
    ExtraTreesRegressor,
    RandomForestRegressor,
    GradientBoostingRegressor,
    StackingRegressor
)
from sklearn.linear_model import Ridge
from xgboost import XGBRegressor

In [ ]:
targets = [
    'Mg ', 'Al ', 'Si ', 'P ', 'K FC', 'Ca FC', 'Ti FC',
    'Cr Concentration', 'Mn FC', 'Fe FC', 'Ni Concentration',
    'Cu FC', 'Zn FC', 'Rb Concentration', 'Sr Concentration',
    'Y Concentration', 'Zr Concentration'
]

features = [
    'R', 'G', 'B',
    'Lat', 'Lon', 'Elevation-1', 'Elevation-2',
    'Band 1', 'Band 2', 'Band 3', 'Band 4',
    'Band 5', 'Band 6', 'Band 7', 'Band 8'
]

In [ ]:
df = pd.read_csv("/content/Model_with_elevation_and_band_values.csv")
df = df[features + targets].dropna()

df = df.apply(pd.to_numeric, errors="coerce")
df = df.dropna().reset_index(drop=True)

df.head()

,R,G,B,Lat,Lon,Elevation-1,Elevation-2,Band 1,Band 2,Band 3,...,Cr Concentration,Mn FC,Fe FC,Ni Concentration,Cu FC,Zn FC,Rb Concentration,Sr Concentration,Y Concentration,Zr Concentration
0,19.0,14.0,15.0,18.814707,-72.521798,51,77,0.082626,0.065365,0.055144,...,0.00828,0.052525,1.827580,0.00449,0.002138,0.004831,0.00160,0.06060,0.00134,0.00506
1,7.0,5.0,11.0,18.816330,-72.522515,56,83,0.085026,0.067925,0.059044,...,0.01015,0.056804,2.269902,0.00521,0.003256,0.005386,0.00221,0.05897,0.00147,0.00578
2,24.0,17.0,16.0,18.816524,-72.522716,57,83,0.089026,0.075905,0.069465,...,0.01042,0.059697,2.365258,0.00509,0.002851,0.005482,0.00218,0.06392,0.00148,0.00637
3,18.0,13.0,14.0,18.816950,-72.523073,55,82,0.088246,0.073345,0.066365,...,0.01357,0.063371,3.869811,0.00657,0.003916,0.006908,0.00303,0.05255,0.00137,0.00816
4,15.0,12.0,14.0,18.817015,-72.523359,55,82,0.085146,0.069145,0.063084,...,0.00939,0.068640,2.607818,0.00522,0.003186,0.005685,0.00226,0.06173,0.00150,0.00714

In [ ]:
def select_features_model_based(X_train, y_train, top_k):
    selector = ExtraTreesRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    )
    selector.fit(X_train, y_train)

    importances = pd.Series(
        selector.feature_importances_, index=X_train.columns
    )

    return importances.sort_values(ascending=False).head(top_k).index.tolist()

In [ ]:
def objective(trial, X, y):

    model_name = trial.suggest_categorical(
        "model", ["ET", "RF", "GB", "XGB"]
    )

    top_k = trial.suggest_int("top_k", 5, len(X.columns))

    if model_name == "ET":
        model = ExtraTreesRegressor(
            n_estimators=trial.suggest_int("n_estimators", 300, 700),
            max_depth=trial.suggest_int("max_depth", 8, 20),
            random_state=42,
            n_jobs=-1
        )

    elif model_name == "RF":
        model = RandomForestRegressor(
            n_estimators=trial.suggest_int("n_estimators", 300, 700),
            max_depth=trial.suggest_int("max_depth", 8, 20),
            random_state=42,
            n_jobs=-1
        )

    elif model_name == "GB":
        model = GradientBoostingRegressor(
            n_estimators=trial.suggest_int("n_estimators", 200, 500),
            learning_rate=trial.suggest_float("lr", 0.01, 0.1),
            max_depth=trial.suggest_int("max_depth", 2, 5),
            random_state=42
        )

    elif model_name == "XGB":
        model = XGBRegressor(
            n_estimators=trial.suggest_int("n_estimators", 300, 600),
            max_depth=trial.suggest_int("max_depth", 3, 6),
            learning_rate=trial.suggest_float("lr", 0.01, 0.1),
            subsample=trial.suggest_float("subsample", 0.7, 1.0),
            colsample_bytree=trial.suggest_float("colsample", 0.7, 1.0),
            objective="reg:squarederror",
            random_state=42,
            n_jobs=-1
        )


    cv = KFold(n_splits=5, shuffle=True, random_state=42)
    scores = []

    for train_idx, test_idx in cv.split(X):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

        selected = select_features_model_based(
            X_train, y_train, top_k
        )

        X_train = X_train[selected]
        X_test = X_test[selected]

        model.fit(X_train, y_train)
        preds = model.predict(X_test)

        scores.append(r2_score(y_test, preds))

    return np.mean(scores)

In [ ]:
results = []

for target in targets:
    print(f"\n🔍 Optimizing for {target}")

    X = df[features]
    y = df[target]

    sampler = optuna.samplers.TPESampler(seed=42)

    study = optuna.create_study(
        direction="maximize",
        sampler=sampler
    )

    study.optimize(
        lambda trial: objective(trial, X, y),
        n_trials=50,
        show_progress_bar=True
    )

    results.append({
        "Target": target,
        "Best_CV_R2": study.best_value,
        "Best_Params": study.best_params
    })

[I 2026-01-22 08:14:43,452] A new study created in memory with name: no-name-73bc8ac5-558b-434f-80fc-f0216e8dd1aa

🔍 Optimizing for Mg

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 08:14:50,361] Trial 0 finished with value: 0.5083426980533401 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:14:59,745] Trial 1 finished with value: 0.46377185918402547 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:15:03,892] Trial 2 finished with value: 0.41736114482788966 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:15:12,326] Trial 3 finished with value: 0.49350741253836594 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:15:15,972] Trial 4 finished with value: 0.3734341619000078 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:15:22,799] Trial 5 finished with value: 0.35463401153684837 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:15:35,025] Trial 6 finished with value: 0.4974688174649343 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:15:39,706] Trial 7 finished with value: 0.38463582607195274 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:15:44,653] Trial 8 finished with value: 0.3656957693315976 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:15:52,694] Trial 9 finished with value: 0.46875270480373177 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:16:01,865] Trial 10 finished with value: 0.4889529380084935 and parameters: {'model': 'RF', 'top_k': 5, 'n_estimators': 472, 'max_depth': 10}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:16:11,424] Trial 11 finished with value: 0.4855619440789566 and parameters: {'model': 'RF', 'top_k': 5, 'n_estimators': 498, 'max_depth': 20}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:16:21,705] Trial 12 finished with value: 0.4850406079358014 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 588, 'max_depth': 20}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:16:30,708] Trial 13 finished with value: 0.4897953021348 and parameters: {'model': 'RF', 'top_k': 8, 'n_estimators': 444, 'max_depth': 17}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:16:35,509] Trial 14 finished with value: 0.4281126980786798 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 205, 'lr': 0.011073188101939947, 'max_depth': 2}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:16:46,432] Trial 15 finished with value: 0.4989103552641323 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 555, 'max_depth': 17}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:16:59,993] Trial 16 finished with value: 0.5011150091560136 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 699, 'max_depth': 16}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:17:11,401] Trial 17 finished with value: 0.5060954106573552 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 690, 'max_depth': 14}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:17:20,568] Trial 18 finished with value: 0.5073680175545288 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 700, 'max_depth': 13}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:17:29,144] Trial 19 finished with value: 0.4738198957335557 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 633, 'max_depth': 10}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:17:35,265] Trial 20 finished with value: 0.4908196554860934 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 439, 'max_depth': 12}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:17:44,583] Trial 21 finished with value: 0.5072148794039224 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 688, 'max_depth': 13}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:17:53,619] Trial 22 finished with value: 0.5071128179936994 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 650, 'max_depth': 13}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:18:01,249] Trial 23 finished with value: 0.49752201123403517 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 659, 'max_depth': 9}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:18:09,897] Trial 24 finished with value: 0.4936218879816587 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 601, 'max_depth': 12}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:18:19,061] Trial 25 finished with value: 0.49301141018023226 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 670, 'max_depth': 14}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:18:23,331] Trial 26 finished with value: 0.35735634906438385 and parameters: {'model': 'GB', 'top_k': 6, 'n_estimators': 210, 'lr': 0.09972439475103052, 'max_depth': 4}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:18:31,662] Trial 27 finished with value: 0.4753806174483799 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 604, 'max_depth': 9}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:18:38,818] Trial 28 finished with value: 0.48568758950478574 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 512, 'max_depth': 13}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:18:47,464] Trial 29 finished with value: 0.4955154860378963 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 635, 'max_depth': 11}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:18:51,641] Trial 30 finished with value: 0.4102764268069111 and parameters: {'model': 'GB', 'top_k': 6, 'n_estimators': 265, 'lr': 0.03725700829761253, 'max_depth': 2}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:19:00,655] Trial 31 finished with value: 0.5070249558443475 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 664, 'max_depth': 13}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:19:09,867] Trial 32 finished with value: 0.483495036054412 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 675, 'max_depth': 14}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:19:17,704] Trial 33 finished with value: 0.48368103986153554 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 649, 'max_depth': 15}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:19:26,463] Trial 34 finished with value: 0.48998778810464627 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 617, 'max_depth': 11}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:19:31,333] Trial 35 finished with value: 0.3490829135105956 and parameters: {'model': 'XGB', 'top_k': 6, 'n_estimators': 573, 'max_depth': 5, 'lr': 0.06509570176543007, 'subsample': 0.9831597406092863, 'colsample': 0.9908814591475331}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:19:40,802] Trial 36 finished with value: 0.48298459960714074 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 698, 'max_depth': 13}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:19:48,048] Trial 37 finished with value: 0.4830673747801605 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 413, 'max_depth': 15}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:19:52,154] Trial 38 finished with value: 0.37356362585543634 and parameters: {'model': 'XGB', 'top_k': 6, 'n_estimators': 574, 'max_depth': 5, 'lr': 0.09957421408547605, 'subsample': 0.7023096014702224, 'colsample': 0.704318176087983}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:19:59,272] Trial 39 finished with value: 0.3603645272851527 and parameters: {'model': 'GB', 'top_k': 9, 'n_estimators': 489, 'lr': 0.03926851385438454, 'max_depth': 3}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:20:05,884] Trial 40 finished with value: 0.5041365344850088 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 524, 'max_depth': 9}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:20:14,703] Trial 41 finished with value: 0.5070983911282695 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 645, 'max_depth': 13}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:20:22,934] Trial 42 finished with value: 0.5015032078077235 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 633, 'max_depth': 11}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:20:31,161] Trial 43 finished with value: 0.48480812433993103 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 680, 'max_depth': 13}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:20:42,870] Trial 44 finished with value: 0.4852385147671921 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 647, 'max_depth': 16}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:20:49,526] Trial 45 finished with value: 0.40263092579967913 and parameters: {'model': 'XGB', 'top_k': 15, 'n_estimators': 579, 'max_depth': 4, 'lr': 0.022094426759144213, 'subsample': 0.9875374045418589, 'colsample': 0.7877154314474568}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:20:57,832] Trial 46 finished with value: 0.49272911531067054 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 680, 'max_depth': 12}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:21:07,146] Trial 47 finished with value: 0.4929604181966997 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 370, 'max_depth': 18}. Best is trial 0 with value: 0.5083426980533401.
[I 2026-01-22 08:21:13,855] Trial 48 finished with value: 0.4871478933644802 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 342, 'max_depth': 15}. Best is trial 0 with value: 0.5083426980533401.

[I 2026-01-22 08:21:24,267] A new study created in memory with name: no-name-74b3e216-c698-4406-a7f6-78c172c886d5

[I 2026-01-22 08:21:24,254] Trial 49 finished with value: 0.48958187295436845 and parameters: {'model': 'RF', 'top_k': 5, 'n_estimators': 651, 'max_depth': 12}. Best is trial 0 with value: 0.5083426980533401.

🔍 Optimizing for Al

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 08:21:32,151] Trial 0 finished with value: 0.6277134765599238 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.6277134765599238.
[I 2026-01-22 08:21:41,478] Trial 1 finished with value: 0.6541100733522309 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.6541100733522309.
[I 2026-01-22 08:21:45,583] Trial 2 finished with value: 0.5632716675520394 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.6541100733522309.
[I 2026-01-22 08:21:53,897] Trial 3 finished with value: 0.5849174702670432 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.6541100733522309.
[I 2026-01-22 08:21:57,539] Trial 4 finished with value: 0.5688852847610247 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.6541100733522309.
[I 2026-01-22 08:22:03,966] Trial 5 finished with value: 0.5643076834245252 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.6541100733522309.
[I 2026-01-22 08:22:15,700] Trial 6 finished with value: 0.5758199671417239 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.6541100733522309.
[I 2026-01-22 08:22:21,117] Trial 7 finished with value: 0.5579018449475779 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.6541100733522309.
[I 2026-01-22 08:22:24,781] Trial 8 finished with value: 0.5737194690756022 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.6541100733522309.
[I 2026-01-22 08:22:33,572] Trial 9 finished with value: 0.6569103965580174 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:22:42,128] Trial 10 finished with value: 0.6116318895303147 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 13}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:22:50,405] Trial 11 finished with value: 0.6536207227763183 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 11}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:22:59,777] Trial 12 finished with value: 0.6507125400036301 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 623, 'max_depth': 11}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:23:07,944] Trial 13 finished with value: 0.6490864587448056 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 489, 'max_depth': 11}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:23:15,201] Trial 14 finished with value: 0.6556139674344422 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 490, 'max_depth': 14}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:23:21,599] Trial 15 finished with value: 0.6092137351790334 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 434, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:23:28,522] Trial 16 finished with value: 0.6456114395474843 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 521, 'max_depth': 16}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:23:36,540] Trial 17 finished with value: 0.6554023189100142 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 467, 'max_depth': 17}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:23:44,027] Trial 18 finished with value: 0.65348551668413 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 565, 'max_depth': 13}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:23:49,066] Trial 19 finished with value: 0.5958729590909226 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 207, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:23:55,735] Trial 20 finished with value: 0.6557469542728961 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 451, 'max_depth': 14}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:24:03,455] Trial 21 finished with value: 0.6558783835551095 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 455, 'max_depth': 14}. Best is trial 9 with value: 0.6569103965580174.
[I 2026-01-22 08:24:10,490] Trial 22 finished with value: 0.6621981308989625 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 426, 'max_depth': 13}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:24:17,154] Trial 23 finished with value: 0.655432058726807 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 424, 'max_depth': 12}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:24:25,522] Trial 24 finished with value: 0.6620209733160403 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 531, 'max_depth': 17}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:24:32,820] Trial 25 finished with value: 0.6563779200263222 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 552, 'max_depth': 20}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:24:41,657] Trial 26 finished with value: 0.6611434185898157 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 576, 'max_depth': 18}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:24:48,616] Trial 27 finished with value: 0.5672564687176501 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 415, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:24:59,412] Trial 28 finished with value: 0.5864118569491614 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 584, 'max_depth': 18}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:25:11,119] Trial 29 finished with value: 0.6124039305625587 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 671, 'max_depth': 17}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:25:19,251] Trial 30 finished with value: 0.6601592202217647 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 527, 'max_depth': 16}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:25:27,162] Trial 31 finished with value: 0.6608587736431845 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 515, 'max_depth': 16}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:25:34,940] Trial 32 finished with value: 0.6516385737831902 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 590, 'max_depth': 18}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:25:42,673] Trial 33 finished with value: 0.6460191829598506 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 502, 'max_depth': 16}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:25:49,731] Trial 34 finished with value: 0.6572874841181969 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 511, 'max_depth': 15}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:25:58,659] Trial 35 finished with value: 0.6571395790364691 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 635, 'max_depth': 18}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:26:02,612] Trial 36 finished with value: 0.5323424752710748 and parameters: {'model': 'XGB', 'top_k': 6, 'n_estimators': 485, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:26:14,441] Trial 37 finished with value: 0.5828921643102605 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 565, 'max_depth': 19}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:26:23,533] Trial 38 finished with value: 0.6513828151150654 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 646, 'max_depth': 17}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:26:28,127] Trial 39 finished with value: 0.5705021045417741 and parameters: {'model': 'XGB', 'top_k': 10, 'n_estimators': 527, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:26:35,617] Trial 40 finished with value: 0.5623146955641534 and parameters: {'model': 'GB', 'top_k': 9, 'n_estimators': 471, 'lr': 0.032894255032331704, 'max_depth': 4}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:26:43,830] Trial 41 finished with value: 0.6606506238936339 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 536, 'max_depth': 16}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:26:51,297] Trial 42 finished with value: 0.6524387317302576 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 615, 'max_depth': 15}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:26:59,722] Trial 43 finished with value: 0.6557781003055257 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 572, 'max_depth': 15}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:27:06,893] Trial 44 finished with value: 0.6033605950428867 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 540, 'max_depth': 19}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:27:15,374] Trial 45 finished with value: 0.6508767836402662 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 603, 'max_depth': 17}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:27:22,690] Trial 46 finished with value: 0.6597649894787638 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 400, 'max_depth': 16}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:27:27,984] Trial 47 finished with value: 0.5067246782249489 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 554, 'max_depth': 5, 'lr': 0.012035429732013193, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 22 with value: 0.6621981308989625.
[I 2026-01-22 08:27:34,554] Trial 48 finished with value: 0.647041326407849 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 342, 'max_depth': 13}. Best is trial 22 with value: 0.6621981308989625.

[I 2026-01-22 08:27:44,628] A new study created in memory with name: no-name-598a27d9-001f-4fec-beb4-eb9235dd1ed7

[I 2026-01-22 08:27:44,618] Trial 49 finished with value: 0.5817933737285637 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 518, 'max_depth': 20}. Best is trial 22 with value: 0.6621981308989625.

🔍 Optimizing for Si

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 08:27:52,250] Trial 0 finished with value: 0.2624333343286033 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.2624333343286033.
[I 2026-01-22 08:28:01,290] Trial 1 finished with value: 0.2905787218836029 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.2905787218836029.
[I 2026-01-22 08:28:05,436] Trial 2 finished with value: 0.2194145397695461 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.2905787218836029.
[I 2026-01-22 08:28:13,900] Trial 3 finished with value: 0.31984470899718254 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 3 with value: 0.31984470899718254.
[I 2026-01-22 08:28:17,579] Trial 4 finished with value: 0.13134478482912848 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 3 with value: 0.31984470899718254.
[I 2026-01-22 08:28:23,977] Trial 5 finished with value: 0.1485359451081371 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 3 with value: 0.31984470899718254.
[I 2026-01-22 08:28:35,894] Trial 6 finished with value: 0.3166302587161993 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 3 with value: 0.31984470899718254.
[I 2026-01-22 08:28:41,144] Trial 7 finished with value: 0.2010143943253757 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 3 with value: 0.31984470899718254.
[I 2026-01-22 08:28:44,842] Trial 8 finished with value: 0.12131218425124742 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 3 with value: 0.31984470899718254.
[I 2026-01-22 08:28:53,511] Trial 9 finished with value: 0.2917807801669291 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 3 with value: 0.31984470899718254.
[I 2026-01-22 08:29:02,842] Trial 10 finished with value: 0.2583533348620409 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 472, 'max_depth': 16}. Best is trial 3 with value: 0.31984470899718254.
[I 2026-01-22 08:29:13,520] Trial 11 finished with value: 0.3208788214663284 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 546, 'max_depth': 20}. Best is trial 11 with value: 0.3208788214663284.
[I 2026-01-22 08:29:27,479] Trial 12 finished with value: 0.32015180212377226 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 691, 'max_depth': 20}. Best is trial 11 with value: 0.3208788214663284.
[I 2026-01-22 08:29:40,938] Trial 13 finished with value: 0.3238492722034902 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 695, 'max_depth': 20}. Best is trial 13 with value: 0.3238492722034902.
[I 2026-01-22 08:29:44,953] Trial 14 finished with value: 0.2459621555994989 and parameters: {'model': 'GB', 'top_k': 8, 'n_estimators': 210, 'lr': 0.011073188101939947, 'max_depth': 2}. Best is trial 13 with value: 0.3238492722034902.
[I 2026-01-22 08:29:56,651] Trial 15 finished with value: 0.30160663661831416 and parameters: {'model': 'RF', 'top_k': 8, 'n_estimators': 620, 'max_depth': 18}. Best is trial 13 with value: 0.3238492722034902.
[I 2026-01-22 08:30:09,915] Trial 16 finished with value: 0.32479042884763115 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 699, 'max_depth': 17}. Best is trial 16 with value: 0.32479042884763115.
[I 2026-01-22 08:30:23,192] Trial 17 finished with value: 0.3244869161138981 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 695, 'max_depth': 17}. Best is trial 16 with value: 0.32479042884763115.
[I 2026-01-22 08:30:32,044] Trial 18 finished with value: 0.2567811561152674 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 634, 'max_depth': 17}. Best is trial 16 with value: 0.32479042884763115.
[I 2026-01-22 08:30:36,107] Trial 19 finished with value: 0.18315061559523177 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 203, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 16 with value: 0.32479042884763115.
[I 2026-01-22 08:30:47,649] Trial 20 finished with value: 0.31481265550590176 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 597, 'max_depth': 13}. Best is trial 16 with value: 0.32479042884763115.
[I 2026-01-22 08:31:00,581] Trial 21 finished with value: 0.32504394059601405 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 680, 'max_depth': 18}. Best is trial 21 with value: 0.32504394059601405.
[I 2026-01-22 08:31:14,183] Trial 22 finished with value: 0.32659715386657223 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 665, 'max_depth': 17}. Best is trial 22 with value: 0.32659715386657223.
[I 2026-01-22 08:31:27,800] Trial 23 finished with value: 0.3266353520636408 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 663, 'max_depth': 15}. Best is trial 23 with value: 0.3266353520636408.
[I 2026-01-22 08:31:41,191] Trial 24 finished with value: 0.32674950674836045 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 659, 'max_depth': 15}. Best is trial 24 with value: 0.32674950674836045.
[I 2026-01-22 08:31:53,651] Trial 25 finished with value: 0.3260864269152859 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 587, 'max_depth': 14}. Best is trial 24 with value: 0.32674950674836045.
[I 2026-01-22 08:32:07,144] Trial 26 finished with value: 0.3267495067483605 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 659, 'max_depth': 15}. Best is trial 26 with value: 0.3267495067483605.
[I 2026-01-22 08:32:16,951] Trial 27 finished with value: 0.297596987362381 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 653, 'max_depth': 15}. Best is trial 26 with value: 0.3267495067483605.
[I 2026-01-22 08:32:25,951] Trial 28 finished with value: 0.12569113261885076 and parameters: {'model': 'GB', 'top_k': 14, 'n_estimators': 480, 'lr': 0.041419357059636994, 'max_depth': 4}. Best is trial 26 with value: 0.3267495067483605.
[I 2026-01-22 08:32:39,136] Trial 29 finished with value: 0.319049735161253 and parameters: {'model': 'RF', 'top_k': 15, 'n_estimators': 591, 'max_depth': 12}. Best is trial 26 with value: 0.3267495067483605.
[I 2026-01-22 08:32:52,454] Trial 30 finished with value: 0.3256945247688224 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 654, 'max_depth': 14}. Best is trial 26 with value: 0.3267495067483605.
[I 2026-01-22 08:33:05,984] Trial 31 finished with value: 0.3264135773041124 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 664, 'max_depth': 15}. Best is trial 26 with value: 0.3267495067483605.
[I 2026-01-22 08:33:19,193] Trial 32 finished with value: 0.32639414344319523 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 616, 'max_depth': 16}. Best is trial 26 with value: 0.3267495067483605.
[I 2026-01-22 08:33:31,817] Trial 33 finished with value: 0.32065084405501815 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 640, 'max_depth': 13}. Best is trial 26 with value: 0.3267495067483605.
[I 2026-01-22 08:33:45,401] Trial 34 finished with value: 0.32765382385758907 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 662, 'max_depth': 16}. Best is trial 34 with value: 0.32765382385758907.
[I 2026-01-22 08:33:52,691] Trial 35 finished with value: 0.14245685929795715 and parameters: {'model': 'XGB', 'top_k': 14, 'n_estimators': 572, 'max_depth': 5, 'lr': 0.09850401020012867, 'subsample': 0.9831597406092863, 'colsample': 0.9908814591475331}. Best is trial 34 with value: 0.32765382385758907.
[I 2026-01-22 08:34:01,047] Trial 36 finished with value: 0.2890949539672742 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 613, 'max_depth': 16}. Best is trial 34 with value: 0.32765382385758907.
[I 2026-01-22 08:34:11,624] Trial 37 finished with value: 0.32351356194952713 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 444, 'max_depth': 13}. Best is trial 34 with value: 0.32765382385758907.
[I 2026-01-22 08:34:23,075] Trial 38 finished with value: 0.32588802369134684 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 511, 'max_depth': 15}. Best is trial 34 with value: 0.32765382385758907.
[I 2026-01-22 08:34:28,546] Trial 39 finished with value: 0.1346632489698786 and parameters: {'model': 'XGB', 'top_k': 15, 'n_estimators': 584, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 34 with value: 0.32765382385758907.
[I 2026-01-22 08:34:36,747] Trial 40 finished with value: 0.1454568205248982 and parameters: {'model': 'GB', 'top_k': 11, 'n_estimators': 487, 'lr': 0.032894255032331704, 'max_depth': 4}. Best is trial 34 with value: 0.32765382385758907.
[I 2026-01-22 08:34:51,229] Trial 41 finished with value: 0.3276633882141244 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 673, 'max_depth': 16}. Best is trial 41 with value: 0.3276633882141244.
[I 2026-01-22 08:35:05,213] Trial 42 finished with value: 0.32508424088815036 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 668, 'max_depth': 15}. Best is trial 41 with value: 0.3276633882141244.
[I 2026-01-22 08:35:18,471] Trial 43 finished with value: 0.32813889652336903 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 641, 'max_depth': 16}. Best is trial 43 with value: 0.32813889652336903.
[I 2026-01-22 08:35:31,933] Trial 44 finished with value: 0.3270478791208813 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 637, 'max_depth': 14}. Best is trial 43 with value: 0.32813889652336903.
[I 2026-01-22 08:35:46,367] Trial 45 finished with value: 0.3256200064811575 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 644, 'max_depth': 16}. Best is trial 43 with value: 0.32813889652336903.
[I 2026-01-22 08:35:58,401] Trial 46 finished with value: 0.31884845706175674 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 561, 'max_depth': 10}. Best is trial 43 with value: 0.32813889652336903.
[I 2026-01-22 08:36:04,971] Trial 47 finished with value: 0.1351965326973788 and parameters: {'model': 'XGB', 'top_k': 14, 'n_estimators': 572, 'max_depth': 5, 'lr': 0.07481880725872753, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 43 with value: 0.32813889652336903.
[I 2026-01-22 08:36:18,483] Trial 48 finished with value: 0.3273995903392285 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 624, 'max_depth': 18}. Best is trial 43 with value: 0.32813889652336903.

[I 2026-01-22 08:36:27,079] A new study created in memory with name: no-name-72e873e5-f431-4a9c-a168-e0c26b4cf5f8

[I 2026-01-22 08:36:27,073] Trial 49 finished with value: 0.24802064387891862 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 605, 'max_depth': 19}. Best is trial 43 with value: 0.32813889652336903.

🔍 Optimizing for P

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 08:36:34,065] Trial 0 finished with value: 0.5850311797769858 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.5850311797769858.
[I 2026-01-22 08:36:43,502] Trial 1 finished with value: 0.6014434836746065 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.6014434836746065.
[I 2026-01-22 08:36:47,654] Trial 2 finished with value: 0.5626725256265847 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.6014434836746065.
[I 2026-01-22 08:36:56,081] Trial 3 finished with value: 0.5706723986706898 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.6014434836746065.
[I 2026-01-22 08:36:59,717] Trial 4 finished with value: 0.5743563258515191 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.6014434836746065.
[I 2026-01-22 08:37:06,326] Trial 5 finished with value: 0.5231577525254179 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.6014434836746065.
[I 2026-01-22 08:37:18,897] Trial 6 finished with value: 0.5681324044967896 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.6014434836746065.
[I 2026-01-22 08:37:23,407] Trial 7 finished with value: 0.5519789261819897 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.6014434836746065.
[I 2026-01-22 08:37:28,532] Trial 8 finished with value: 0.552692016738559 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.6014434836746065.
[I 2026-01-22 08:37:36,264] Trial 9 finished with value: 0.6036242433861927 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 9 with value: 0.6036242433861927.
[I 2026-01-22 08:37:45,409] Trial 10 finished with value: 0.5353193567004009 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 13}. Best is trial 9 with value: 0.6036242433861927.
[I 2026-01-22 08:37:54,678] Trial 11 finished with value: 0.6112749624750642 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 11}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:38:02,319] Trial 12 finished with value: 0.603821718174029 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 522, 'max_depth': 12}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:38:10,915] Trial 13 finished with value: 0.6089791989573108 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 474, 'max_depth': 15}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:38:19,077] Trial 14 finished with value: 0.5996576479678406 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 460, 'max_depth': 16}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:38:25,416] Trial 15 finished with value: 0.5285746205039938 and parameters: {'model': 'GB', 'top_k': 15, 'n_estimators': 434, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:38:34,152] Trial 16 finished with value: 0.5662834698316968 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 585, 'max_depth': 17}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:38:41,417] Trial 17 finished with value: 0.5987385311099203 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 474, 'max_depth': 14}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:38:50,690] Trial 18 finished with value: 0.5873411483828035 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 605, 'max_depth': 18}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:38:56,473] Trial 19 finished with value: 0.49996431442034855 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 209, 'lr': 0.09983831247079358, 'max_depth': 4}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:39:05,032] Trial 20 finished with value: 0.6039356817757087 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 659, 'max_depth': 10}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:39:14,915] Trial 21 finished with value: 0.6043462630598668 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 675, 'max_depth': 10}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:39:24,894] Trial 22 finished with value: 0.6023793192546435 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 700, 'max_depth': 10}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:39:33,629] Trial 23 finished with value: 0.6107297098545013 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 604, 'max_depth': 11}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:39:41,971] Trial 24 finished with value: 0.5966542854469559 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 589, 'max_depth': 12}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:39:50,605] Trial 25 finished with value: 0.5976431557238502 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 503, 'max_depth': 14}. Best is trial 11 with value: 0.6112749624750642.
[I 2026-01-22 08:39:58,990] Trial 26 finished with value: 0.6119727164529329 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 561, 'max_depth': 11}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:40:05,185] Trial 27 finished with value: 0.4619297680621779 and parameters: {'model': 'GB', 'top_k': 11, 'n_estimators': 442, 'lr': 0.0399204177340166, 'max_depth': 2}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:40:18,743] Trial 28 finished with value: 0.5690468479071783 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 629, 'max_depth': 11}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:40:29,537] Trial 29 finished with value: 0.5950639625656285 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 563, 'max_depth': 11}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:40:38,432] Trial 30 finished with value: 0.5991907112844923 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 631, 'max_depth': 9}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:40:46,065] Trial 31 finished with value: 0.596213078101272 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 508, 'max_depth': 13}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:40:55,332] Trial 32 finished with value: 0.6012440106420545 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 562, 'max_depth': 15}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:41:04,165] Trial 33 finished with value: 0.5978902702531557 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 595, 'max_depth': 9}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:41:12,559] Trial 34 finished with value: 0.5960064349854836 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 651, 'max_depth': 11}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:41:20,969] Trial 35 finished with value: 0.6051117252950104 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 482, 'max_depth': 13}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:41:25,471] Trial 36 finished with value: 0.5079646668596355 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 569, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:41:40,278] Trial 37 finished with value: 0.5695616869458868 and parameters: {'model': 'RF', 'top_k': 15, 'n_estimators': 622, 'max_depth': 15}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:41:47,985] Trial 38 finished with value: 0.5621757759549153 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 534, 'max_depth': 14}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:41:53,793] Trial 39 finished with value: 0.5925832356602798 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 418, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:42:02,289] Trial 40 finished with value: 0.5529359557599464 and parameters: {'model': 'GB', 'top_k': 14, 'n_estimators': 476, 'lr': 0.032894255032331704, 'max_depth': 4}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:42:10,763] Trial 41 finished with value: 0.6051503274489847 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 483, 'max_depth': 13}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:42:19,364] Trial 42 finished with value: 0.5974879645257308 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 521, 'max_depth': 12}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:42:28,096] Trial 43 finished with value: 0.6064843050793102 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 606, 'max_depth': 20}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:42:37,980] Trial 44 finished with value: 0.6064956562582258 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 617, 'max_depth': 20}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:42:47,230] Trial 45 finished with value: 0.60560342887568 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 547, 'max_depth': 20}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:42:56,968] Trial 46 finished with value: 0.6010649362314553 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 649, 'max_depth': 18}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:43:03,252] Trial 47 finished with value: 0.5002812967970949 and parameters: {'model': 'XGB', 'top_k': 15, 'n_estimators': 576, 'max_depth': 5, 'lr': 0.012035429732013193, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 26 with value: 0.6119727164529329.
[I 2026-01-22 08:43:16,433] Trial 48 finished with value: 0.5673919020203066 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 609, 'max_depth': 16}. Best is trial 26 with value: 0.6119727164529329.

[I 2026-01-22 08:43:26,270] A new study created in memory with name: no-name-4489c0bb-6b8c-4dca-9c09-ecfaf1959f08

[I 2026-01-22 08:43:26,263] Trial 49 finished with value: 0.599460417032659 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 669, 'max_depth': 19}. Best is trial 26 with value: 0.6119727164529329.

🔍 Optimizing for K FC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 08:43:33,375] Trial 0 finished with value: 0.5131654980680901 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:43:42,560] Trial 1 finished with value: 0.4790776382044598 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:43:48,407] Trial 2 finished with value: 0.4482421302849084 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:43:55,735] Trial 3 finished with value: 0.4791958335421372 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:44:00,880] Trial 4 finished with value: 0.3761671757777851 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:44:06,732] Trial 5 finished with value: 0.4376886444097419 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:44:18,934] Trial 6 finished with value: 0.4758121883477938 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:44:24,908] Trial 7 finished with value: 0.44245023055019805 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:44:28,932] Trial 8 finished with value: 0.36460038728297955 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:44:37,378] Trial 9 finished with value: 0.47997481432648437 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:44:45,935] Trial 10 finished with value: 0.5013606496712285 and parameters: {'model': 'RF', 'top_k': 5, 'n_estimators': 472, 'max_depth': 10}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:44:55,106] Trial 11 finished with value: 0.5011972443498462 and parameters: {'model': 'RF', 'top_k': 5, 'n_estimators': 465, 'max_depth': 10}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:45:04,201] Trial 12 finished with value: 0.49868318030922065 and parameters: {'model': 'RF', 'top_k': 5, 'n_estimators': 469, 'max_depth': 9}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:45:12,293] Trial 13 finished with value: 0.5035259498252842 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 437, 'max_depth': 13}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:45:17,308] Trial 14 finished with value: 0.4987928562396817 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 218, 'lr': 0.011073188101939947, 'max_depth': 2}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:45:25,426] Trial 15 finished with value: 0.50343553077394 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 434, 'max_depth': 16}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:45:37,777] Trial 16 finished with value: 0.505016490068774 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 699, 'max_depth': 13}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:45:50,682] Trial 17 finished with value: 0.49020452619450994 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 690, 'max_depth': 18}. Best is trial 0 with value: 0.5131654980680901.
[I 2026-01-22 08:45:59,348] Trial 18 finished with value: 0.5249217985242705 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 612, 'max_depth': 17}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:46:07,977] Trial 19 finished with value: 0.5190343752776814 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 608, 'max_depth': 17}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:46:15,703] Trial 20 finished with value: 0.497176117428376 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 604, 'max_depth': 17}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:46:24,262] Trial 21 finished with value: 0.5185275867993312 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 606, 'max_depth': 20}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:46:32,768] Trial 22 finished with value: 0.5182483328914238 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 601, 'max_depth': 20}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:46:40,597] Trial 23 finished with value: 0.519017672046292 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 641, 'max_depth': 20}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:46:49,943] Trial 24 finished with value: 0.4986330740477182 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 655, 'max_depth': 18}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:46:58,503] Trial 25 finished with value: 0.484597119933068 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 540, 'max_depth': 16}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:47:06,644] Trial 26 finished with value: 0.49897502297488006 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 649, 'max_depth': 18}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:47:15,091] Trial 27 finished with value: 0.5215947406122966 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 569, 'max_depth': 19}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:47:23,165] Trial 28 finished with value: 0.5036167720638606 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 555, 'max_depth': 16}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:47:29,314] Trial 29 finished with value: 0.5054179824242305 and parameters: {'model': 'GB', 'top_k': 6, 'n_estimators': 477, 'lr': 0.09594485157627552, 'max_depth': 4}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:47:38,275] Trial 30 finished with value: 0.49152367528649876 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 578, 'max_depth': 17}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:47:46,818] Trial 31 finished with value: 0.51986947439538 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 669, 'max_depth': 19}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:47:55,400] Trial 32 finished with value: 0.5199449199474506 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 676, 'max_depth': 19}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:48:04,572] Trial 33 finished with value: 0.5225235245047827 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 672, 'max_depth': 19}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:48:13,977] Trial 34 finished with value: 0.4980331749973933 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 681, 'max_depth': 19}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:48:21,827] Trial 35 finished with value: 0.5222984939190302 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 627, 'max_depth': 19}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:48:29,716] Trial 36 finished with value: 0.5232088886200975 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 514, 'max_depth': 15}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:48:35,588] Trial 37 finished with value: 0.42555987173678267 and parameters: {'model': 'GB', 'top_k': 11, 'n_estimators': 486, 'lr': 0.03910066877119639, 'max_depth': 2}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:48:41,721] Trial 38 finished with value: 0.37088462827259355 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 514, 'max_depth': 5, 'lr': 0.06614933800731443, 'subsample': 0.9997880431251318, 'colsample': 0.9870028556379348}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:48:49,449] Trial 39 finished with value: 0.5229827247957315 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 626, 'max_depth': 15}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:48:57,220] Trial 40 finished with value: 0.49786612721509893 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 515, 'max_depth': 15}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:49:05,939] Trial 41 finished with value: 0.522996130003481 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 624, 'max_depth': 15}. Best is trial 18 with value: 0.5249217985242705.
[I 2026-01-22 08:49:13,681] Trial 42 finished with value: 0.525634363820142 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 627, 'max_depth': 14}. Best is trial 42 with value: 0.525634363820142.
[I 2026-01-22 08:49:22,589] Trial 43 finished with value: 0.5027969425159814 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 628, 'max_depth': 14}. Best is trial 42 with value: 0.525634363820142.
[I 2026-01-22 08:49:27,278] Trial 44 finished with value: 0.4626602191783249 and parameters: {'model': 'XGB', 'top_k': 7, 'n_estimators': 581, 'max_depth': 5, 'lr': 0.0345209591055414, 'subsample': 0.7029833018565541, 'colsample': 0.7330632070857459}. Best is trial 42 with value: 0.525634363820142.
[I 2026-01-22 08:49:36,168] Trial 45 finished with value: 0.4962308650204738 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 626, 'max_depth': 15}. Best is trial 42 with value: 0.525634363820142.
[I 2026-01-22 08:49:44,947] Trial 46 finished with value: 0.48551575785599643 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 592, 'max_depth': 14}. Best is trial 42 with value: 0.525634363820142.
[I 2026-01-22 08:49:51,436] Trial 47 finished with value: 0.48327632022780354 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 491, 'lr': 0.09858846597029682, 'max_depth': 4}. Best is trial 42 with value: 0.525634363820142.
[I 2026-01-22 08:49:59,114] Trial 48 finished with value: 0.5083548356079445 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 521, 'max_depth': 14}. Best is trial 42 with value: 0.525634363820142.

[I 2026-01-22 08:50:03,790] A new study created in memory with name: no-name-49e22b64-c751-4ee6-8b89-575731911dca

[I 2026-01-22 08:50:03,784] Trial 49 finished with value: 0.4295885023850296 and parameters: {'model': 'XGB', 'top_k': 8, 'n_estimators': 567, 'max_depth': 5, 'lr': 0.056741680604706225, 'subsample': 0.9930266321380657, 'colsample': 0.9922251880791185}. Best is trial 42 with value: 0.525634363820142.

🔍 Optimizing for Ca FC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 08:50:11,645] Trial 0 finished with value: 0.6557067428000434 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.6557067428000434.
[I 2026-01-22 08:50:21,040] Trial 1 finished with value: 0.6703040903023133 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:50:25,176] Trial 2 finished with value: 0.6401744708993224 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:50:33,559] Trial 3 finished with value: 0.6644731152282936 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:50:37,193] Trial 4 finished with value: 0.6636802154208391 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:50:42,932] Trial 5 finished with value: 0.6419362863001072 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:50:55,150] Trial 6 finished with value: 0.6636363211529565 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:51:01,314] Trial 7 finished with value: 0.6337085723633816 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:51:05,010] Trial 8 finished with value: 0.6625214857464041 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:51:13,820] Trial 9 finished with value: 0.6658663727604761 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:51:22,291] Trial 10 finished with value: 0.6605067308299993 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 12}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:51:30,837] Trial 11 finished with value: 0.6657399346231183 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 12}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:51:40,288] Trial 12 finished with value: 0.664322172964426 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 623, 'max_depth': 11}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:51:48,997] Trial 13 finished with value: 0.6606946999480976 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 489, 'max_depth': 15}. Best is trial 1 with value: 0.6703040903023133.
[I 2026-01-22 08:51:55,814] Trial 14 finished with value: 0.6790591895424152 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 490, 'max_depth': 10}. Best is trial 14 with value: 0.6790591895424152.
[I 2026-01-22 08:52:01,909] Trial 15 finished with value: 0.6718266964629332 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 427, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 14 with value: 0.6790591895424152.
[I 2026-01-22 08:52:07,147] Trial 16 finished with value: 0.6733375539943202 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 414, 'lr': 0.01706161464701026, 'max_depth': 2}. Best is trial 14 with value: 0.6790591895424152.
[I 2026-01-22 08:52:11,336] Trial 17 finished with value: 0.6628537798783775 and parameters: {'model': 'GB', 'top_k': 8, 'n_estimators': 207, 'lr': 0.03966251243642311, 'max_depth': 2}. Best is trial 14 with value: 0.6790591895424152.
[I 2026-01-22 08:52:17,929] Trial 18 finished with value: 0.6705496927890264 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 430, 'lr': 0.012325135613954308, 'max_depth': 2}. Best is trial 14 with value: 0.6790591895424152.
[I 2026-01-22 08:52:23,865] Trial 19 finished with value: 0.6623166301705574 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 430, 'lr': 0.03557784851054671, 'max_depth': 3}. Best is trial 14 with value: 0.6790591895424152.
[I 2026-01-22 08:52:30,766] Trial 20 finished with value: 0.6239873016783701 and parameters: {'model': 'GB', 'top_k': 11, 'n_estimators': 442, 'lr': 0.09438050434294204, 'max_depth': 2}. Best is trial 14 with value: 0.6790591895424152.
[I 2026-01-22 08:52:36,280] Trial 21 finished with value: 0.6711033654771897 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 451, 'lr': 0.013856917948271673, 'max_depth': 2}. Best is trial 14 with value: 0.6790591895424152.
[I 2026-01-22 08:52:42,577] Trial 22 finished with value: 0.6904686617904756 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 407, 'lr': 0.028069497573521514, 'max_depth': 2}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:52:47,516] Trial 23 finished with value: 0.6783507863282516 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 307, 'lr': 0.029195500206801017, 'max_depth': 3}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:52:53,292] Trial 24 finished with value: 0.6769327191238286 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 286, 'lr': 0.03099044621080714, 'max_depth': 3}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:52:58,463] Trial 25 finished with value: 0.6391047260842102 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 326, 'lr': 0.05506510139345073, 'max_depth': 4}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:53:06,242] Trial 26 finished with value: 0.6637132976619339 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 485, 'max_depth': 9}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:53:17,714] Trial 27 finished with value: 0.6616419556236295 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 540, 'max_depth': 18}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:53:22,098] Trial 28 finished with value: 0.6734884279227784 and parameters: {'model': 'GB', 'top_k': 6, 'n_estimators': 225, 'lr': 0.027622904275607332, 'max_depth': 3}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:53:32,544] Trial 29 finished with value: 0.6659187197986209 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 473, 'max_depth': 9}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:53:39,951] Trial 30 finished with value: 0.669535645536673 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 507, 'max_depth': 17}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:53:45,501] Trial 31 finished with value: 0.6793724641057144 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 270, 'lr': 0.03172701721912126, 'max_depth': 3}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:53:50,547] Trial 32 finished with value: 0.6233650431661618 and parameters: {'model': 'GB', 'top_k': 6, 'n_estimators': 252, 'lr': 0.0487117992001088, 'max_depth': 4}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:53:56,089] Trial 33 finished with value: 0.6765375247520927 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 269, 'lr': 0.027397893663737447, 'max_depth': 3}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:54:03,251] Trial 34 finished with value: 0.623337899133636 and parameters: {'model': 'GB', 'top_k': 6, 'n_estimators': 341, 'lr': 0.04440710549163908, 'max_depth': 4}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:54:08,746] Trial 35 finished with value: 0.6163377995650257 and parameters: {'model': 'XGB', 'top_k': 8, 'n_estimators': 349, 'max_depth': 4, 'lr': 0.06314366690152008, 'subsample': 0.9870028556379348, 'colsample': 0.9985807136182534}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:54:13,516] Trial 36 finished with value: 0.6662151351944209 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 313, 'lr': 0.0341634904116786, 'max_depth': 3}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:54:22,524] Trial 37 finished with value: 0.6550090188069329 and parameters: {'model': 'RF', 'top_k': 8, 'n_estimators': 385, 'max_depth': 9}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:54:28,567] Trial 38 finished with value: 0.6440588396401435 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 399, 'max_depth': 14}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:54:34,629] Trial 39 finished with value: 0.6587245523867706 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 331, 'max_depth': 5, 'lr': 0.024138466694361427, 'subsample': 0.704169267453705, 'colsample': 0.7062978450033099}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:54:40,177] Trial 40 finished with value: 0.6716597157888551 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.050875920783349515, 'max_depth': 3}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:54:45,511] Trial 41 finished with value: 0.6735099569905784 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 277, 'lr': 0.03262691737691803, 'max_depth': 3}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:54:50,239] Trial 42 finished with value: 0.6780385951099949 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 304, 'lr': 0.03184119137080745, 'max_depth': 3}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:54:55,113] Trial 43 finished with value: 0.6684353365786151 and parameters: {'model': 'GB', 'top_k': 6, 'n_estimators': 313, 'lr': 0.021971348349295622, 'max_depth': 3}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:55:00,652] Trial 44 finished with value: 0.6540796430469593 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 253, 'lr': 0.038919619876627315, 'max_depth': 4}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:55:06,457] Trial 45 finished with value: 0.683338113234265 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 373, 'max_depth': 9}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:55:13,882] Trial 46 finished with value: 0.6788391927840338 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 368, 'max_depth': 10}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:55:20,059] Trial 47 finished with value: 0.680323018036941 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 373, 'max_depth': 11}. Best is trial 22 with value: 0.6904686617904756.
[I 2026-01-22 08:55:29,161] Trial 48 finished with value: 0.6778945875840605 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 571, 'max_depth': 11}. Best is trial 22 with value: 0.6904686617904756.

[I 2026-01-22 08:55:36,954] A new study created in memory with name: no-name-a3a8838f-7965-4af2-ac37-8c4563bab97b

[I 2026-01-22 08:55:36,947] Trial 49 finished with value: 0.6721980638613444 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 404, 'max_depth': 13}. Best is trial 22 with value: 0.6904686617904756.

🔍 Optimizing for Ti FC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 08:55:44,023] Trial 0 finished with value: 0.22733021315640745 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.22733021315640745.
[I 2026-01-22 08:55:53,473] Trial 1 finished with value: 0.3591704370960602 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.3591704370960602.
[I 2026-01-22 08:55:57,644] Trial 2 finished with value: 0.2618589152470858 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.3591704370960602.
[I 2026-01-22 08:56:06,226] Trial 3 finished with value: 0.3115333403111278 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.3591704370960602.
[I 2026-01-22 08:56:09,946] Trial 4 finished with value: 0.3074304031885909 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.3591704370960602.
[I 2026-01-22 08:56:16,856] Trial 5 finished with value: 0.22518764688414236 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.3591704370960602.
[I 2026-01-22 08:56:29,448] Trial 6 finished with value: 0.31537413946299864 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.3591704370960602.
[I 2026-01-22 08:56:34,029] Trial 7 finished with value: 0.2695400479124296 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.3591704370960602.
[I 2026-01-22 08:56:38,976] Trial 8 finished with value: 0.3146868570101986 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.3591704370960602.
[I 2026-01-22 08:56:47,203] Trial 9 finished with value: 0.3543835091401076 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 1 with value: 0.3591704370960602.
[I 2026-01-22 08:56:56,453] Trial 10 finished with value: 0.2874340550519941 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 12}. Best is trial 1 with value: 0.3591704370960602.
[I 2026-01-22 08:57:05,822] Trial 11 finished with value: 0.3545830325606686 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 12}. Best is trial 1 with value: 0.3591704370960602.
[I 2026-01-22 08:57:14,641] Trial 12 finished with value: 0.35965097117304945 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 650, 'max_depth': 11}. Best is trial 12 with value: 0.35965097117304945.
[I 2026-01-22 08:57:24,888] Trial 13 finished with value: 0.35829941846890545 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 698, 'max_depth': 10}. Best is trial 12 with value: 0.35965097117304945.
[I 2026-01-22 08:57:34,899] Trial 14 finished with value: 0.3583060720985362 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 629, 'max_depth': 15}. Best is trial 12 with value: 0.35965097117304945.
[I 2026-01-22 08:57:40,296] Trial 15 finished with value: 0.26899705065337703 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 435, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 12 with value: 0.35965097117304945.
[I 2026-01-22 08:57:48,852] Trial 16 finished with value: 0.3574071023875243 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 635, 'max_depth': 10}. Best is trial 12 with value: 0.35965097117304945.
[I 2026-01-22 08:57:56,649] Trial 17 finished with value: 0.35436422243128335 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 477, 'max_depth': 10}. Best is trial 12 with value: 0.35965097117304945.
[I 2026-01-22 08:58:04,849] Trial 18 finished with value: 0.36083152184841366 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 574, 'max_depth': 17}. Best is trial 18 with value: 0.36083152184841366.
[I 2026-01-22 08:58:10,007] Trial 19 finished with value: 0.2174739051279646 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 203, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 18 with value: 0.36083152184841366.
[I 2026-01-22 08:58:17,448] Trial 20 finished with value: 0.33970526901881837 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 571, 'max_depth': 18}. Best is trial 18 with value: 0.36083152184841366.
[I 2026-01-22 08:58:27,528] Trial 21 finished with value: 0.3560107498506774 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 651, 'max_depth': 16}. Best is trial 18 with value: 0.36083152184841366.
[I 2026-01-22 08:58:37,109] Trial 22 finished with value: 0.3597154819442105 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 599, 'max_depth': 17}. Best is trial 18 with value: 0.36083152184841366.
[I 2026-01-22 08:58:45,468] Trial 23 finished with value: 0.3491057813365003 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 512, 'max_depth': 17}. Best is trial 18 with value: 0.36083152184841366.
[I 2026-01-22 08:58:53,979] Trial 24 finished with value: 0.3576716169365346 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 589, 'max_depth': 20}. Best is trial 18 with value: 0.36083152184841366.
[I 2026-01-22 08:59:03,867] Trial 25 finished with value: 0.3440856061808928 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 660, 'max_depth': 14}. Best is trial 18 with value: 0.36083152184841366.
[I 2026-01-22 08:59:12,847] Trial 26 finished with value: 0.361910404938909 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 598, 'max_depth': 17}. Best is trial 26 with value: 0.361910404938909.
[I 2026-01-22 08:59:19,866] Trial 27 finished with value: 0.21728113554159306 and parameters: {'model': 'GB', 'top_k': 11, 'n_estimators': 463, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 26 with value: 0.361910404938909.
[I 2026-01-22 08:59:32,016] Trial 28 finished with value: 0.3052798992881711 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 603, 'max_depth': 17}. Best is trial 26 with value: 0.361910404938909.
[I 2026-01-22 08:59:41,843] Trial 29 finished with value: 0.22410569108910156 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 520, 'max_depth': 18}. Best is trial 26 with value: 0.361910404938909.
[I 2026-01-22 08:59:50,805] Trial 30 finished with value: 0.3522653553784507 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 558, 'max_depth': 20}. Best is trial 26 with value: 0.361910404938909.
[I 2026-01-22 08:59:59,185] Trial 31 finished with value: 0.36377797775099535 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 609, 'max_depth': 16}. Best is trial 31 with value: 0.36377797775099535.
[I 2026-01-22 09:00:08,414] Trial 32 finished with value: 0.36321394359055365 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 580, 'max_depth': 16}. Best is trial 31 with value: 0.36377797775099535.
[I 2026-01-22 09:00:17,719] Trial 33 finished with value: 0.3535358843838177 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 578, 'max_depth': 15}. Best is trial 31 with value: 0.36377797775099535.
[I 2026-01-22 09:00:26,319] Trial 34 finished with value: 0.35051273961124424 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 619, 'max_depth': 14}. Best is trial 31 with value: 0.36377797775099535.
[I 2026-01-22 09:00:34,383] Trial 35 finished with value: 0.36644308653950686 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 547, 'max_depth': 16}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:00:40,449] Trial 36 finished with value: 0.2962894472001647 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 536, 'max_depth': 6, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:00:50,023] Trial 37 finished with value: 0.30562696322962124 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 483, 'max_depth': 16}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:00:59,202] Trial 38 finished with value: 0.3608115891921967 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 670, 'max_depth': 16}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:01:05,964] Trial 39 finished with value: 0.24285373495942725 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 564, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:01:12,743] Trial 40 finished with value: 0.28364899328154436 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 486, 'lr': 0.032894255032331704, 'max_depth': 3}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:01:22,377] Trial 41 finished with value: 0.364467327900529 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 617, 'max_depth': 18}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:01:31,658] Trial 42 finished with value: 0.3542108528362141 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 609, 'max_depth': 18}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:01:39,330] Trial 43 finished with value: 0.3574688932678769 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 526, 'max_depth': 19}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:01:49,073] Trial 44 finished with value: 0.3634533323728459 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 635, 'max_depth': 16}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:01:58,965] Trial 45 finished with value: 0.3600626591581756 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 680, 'max_depth': 13}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:02:08,609] Trial 46 finished with value: 0.3539760476824495 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 633, 'max_depth': 15}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:02:14,425] Trial 47 finished with value: 0.32944367058494556 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 581, 'max_depth': 5, 'lr': 0.012035429732013193, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 35 with value: 0.36644308653950686.
[I 2026-01-22 09:02:23,247] Trial 48 finished with value: 0.36396988066802455 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 540, 'max_depth': 16}. Best is trial 35 with value: 0.36644308653950686.

[I 2026-01-22 09:02:35,339] A new study created in memory with name: no-name-32a456ed-0bd2-4cc9-bfef-39b445c4a968

[I 2026-01-22 09:02:35,332] Trial 49 finished with value: 0.3109451912724085 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 547, 'max_depth': 15}. Best is trial 35 with value: 0.36644308653950686.

🔍 Optimizing for Cr Concentration

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 09:02:42,169] Trial 0 finished with value: 0.20330903225139485 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.20330903225139485.
[I 2026-01-22 09:02:51,338] Trial 1 finished with value: 0.2837955124211148 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.2837955124211148.
[I 2026-01-22 09:02:55,474] Trial 2 finished with value: 0.17551264277493972 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.2837955124211148.
[I 2026-01-22 09:03:03,821] Trial 3 finished with value: 0.22835731943130289 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.2837955124211148.
[I 2026-01-22 09:03:07,422] Trial 4 finished with value: 0.18472035096807074 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.2837955124211148.
[I 2026-01-22 09:03:14,032] Trial 5 finished with value: 0.20080283890370537 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.2837955124211148.
[I 2026-01-22 09:03:26,390] Trial 6 finished with value: 0.23619034081670093 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.2837955124211148.
[I 2026-01-22 09:03:30,465] Trial 7 finished with value: 0.14850670271202263 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.2837955124211148.
[I 2026-01-22 09:03:35,020] Trial 8 finished with value: 0.1578933624417036 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.2837955124211148.
[I 2026-01-22 09:03:43,297] Trial 9 finished with value: 0.28902250059070134 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 9 with value: 0.28902250059070134.
[I 2026-01-22 09:03:52,206] Trial 10 finished with value: 0.1506229658108123 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 13}. Best is trial 9 with value: 0.28902250059070134.
[I 2026-01-22 09:04:00,874] Trial 11 finished with value: 0.2902319493423976 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 11}. Best is trial 11 with value: 0.2902319493423976.
[I 2026-01-22 09:04:08,787] Trial 12 finished with value: 0.27781616969588663 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 522, 'max_depth': 12}. Best is trial 11 with value: 0.2902319493423976.
[I 2026-01-22 09:04:17,783] Trial 13 finished with value: 0.28561085790398943 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 597, 'max_depth': 15}. Best is trial 11 with value: 0.2902319493423976.
[I 2026-01-22 09:04:24,744] Trial 14 finished with value: 0.29151185835200666 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 462, 'max_depth': 11}. Best is trial 14 with value: 0.29151185835200666.
[I 2026-01-22 09:04:31,014] Trial 15 finished with value: 0.23862471487955447 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 432, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 14 with value: 0.29151185835200666.
[I 2026-01-22 09:04:38,550] Trial 16 finished with value: 0.3045941046400215 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 486, 'max_depth': 10}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:04:45,566] Trial 17 finished with value: 0.28621198737478926 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 467, 'max_depth': 10}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:04:53,662] Trial 18 finished with value: 0.2766242640031517 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 473, 'max_depth': 17}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:04:58,221] Trial 19 finished with value: 0.20928504080108884 and parameters: {'model': 'GB', 'top_k': 13, 'n_estimators': 258, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:05:05,532] Trial 20 finished with value: 0.3007704259670573 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 448, 'max_depth': 9}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:05:11,860] Trial 21 finished with value: 0.3007704259670573 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 448, 'max_depth': 9}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:05:19,085] Trial 22 finished with value: 0.3017901018907636 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 423, 'max_depth': 9}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:05:25,205] Trial 23 finished with value: 0.2889995920657802 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 421, 'max_depth': 9}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:05:32,746] Trial 24 finished with value: 0.23802316997442535 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 495, 'max_depth': 9}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:05:39,851] Trial 25 finished with value: 0.2919846974530412 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 501, 'max_depth': 10}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:05:47,347] Trial 26 finished with value: 0.2563712722083367 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 422, 'max_depth': 14}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:05:54,886] Trial 27 finished with value: 0.1823470387178891 and parameters: {'model': 'GB', 'top_k': 11, 'n_estimators': 419, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:06:05,100] Trial 28 finished with value: 0.23467592511081503 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 501, 'max_depth': 11}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:06:16,480] Trial 29 finished with value: 0.24113795715912198 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 573, 'max_depth': 9}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:06:24,144] Trial 30 finished with value: 0.2700552314464531 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 487, 'max_depth': 12}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:06:30,458] Trial 31 finished with value: 0.30102822267060625 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 445, 'max_depth': 9}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:06:37,944] Trial 32 finished with value: 0.27951397847568704 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 444, 'max_depth': 10}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:06:43,651] Trial 33 finished with value: 0.3012070797229903 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 358, 'max_depth': 9}. Best is trial 16 with value: 0.3045941046400215.
[I 2026-01-22 09:06:50,692] Trial 34 finished with value: 0.3108166310210295 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 355, 'max_depth': 11}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:06:56,586] Trial 35 finished with value: 0.31081304117952974 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 350, 'max_depth': 11}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:07:01,545] Trial 36 finished with value: 0.11386997351793486 and parameters: {'model': 'XGB', 'top_k': 15, 'n_estimators': 340, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:07:11,194] Trial 37 finished with value: 0.2313980660722706 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 396, 'max_depth': 13}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:07:17,177] Trial 38 finished with value: 0.2808612288416724 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 331, 'max_depth': 11}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:07:21,052] Trial 39 finished with value: 0.1806329751981971 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 398, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:07:27,364] Trial 40 finished with value: 0.19438801118062388 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 298, 'lr': 0.032894255032331704, 'max_depth': 3}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:07:33,230] Trial 41 finished with value: 0.3008540128033446 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 363, 'max_depth': 10}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:07:40,275] Trial 42 finished with value: 0.29556819903670917 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 365, 'max_depth': 11}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:07:46,524] Trial 43 finished with value: 0.27776630387956047 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 379, 'max_depth': 20}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:07:53,586] Trial 44 finished with value: 0.300260696514018 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 339, 'max_depth': 13}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:08:00,271] Trial 45 finished with value: 0.29055376805616706 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 402, 'max_depth': 12}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:08:06,854] Trial 46 finished with value: 0.28693585601850746 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 354, 'max_depth': 10}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:08:11,023] Trial 47 finished with value: 0.1647241208149101 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 378, 'max_depth': 4, 'lr': 0.012035429732013193, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 34 with value: 0.3108166310210295.
[I 2026-01-22 09:08:17,689] Trial 48 finished with value: 0.2940338560001485 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 319, 'max_depth': 15}. Best is trial 34 with value: 0.3108166310210295.

[I 2026-01-22 09:08:29,583] A new study created in memory with name: no-name-1bef7e1b-71cd-4b07-acac-8fd0f541b735

[I 2026-01-22 09:08:29,573] Trial 49 finished with value: 0.2408585103415896 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 520, 'max_depth': 11}. Best is trial 34 with value: 0.3108166310210295.

🔍 Optimizing for Mn FC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 09:08:36,538] Trial 0 finished with value: 0.4922943569189776 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.4922943569189776.
[I 2026-01-22 09:08:45,908] Trial 1 finished with value: 0.539716474677074 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.539716474677074.
[I 2026-01-22 09:08:50,053] Trial 2 finished with value: 0.5212532247787811 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.539716474677074.
[I 2026-01-22 09:08:58,575] Trial 3 finished with value: 0.5051270552744518 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.539716474677074.
[I 2026-01-22 09:09:02,330] Trial 4 finished with value: 0.5288985423954077 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.539716474677074.
[I 2026-01-22 09:09:09,113] Trial 5 finished with value: 0.47505837784880856 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.539716474677074.
[I 2026-01-22 09:09:21,719] Trial 6 finished with value: 0.5057340869470409 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.539716474677074.
[I 2026-01-22 09:09:26,239] Trial 7 finished with value: 0.5134749822107925 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.539716474677074.
[I 2026-01-22 09:09:31,493] Trial 8 finished with value: 0.5085463658939102 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.539716474677074.
[I 2026-01-22 09:09:39,334] Trial 9 finished with value: 0.5422086955303955 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 9 with value: 0.5422086955303955.
[I 2026-01-22 09:09:48,748] Trial 10 finished with value: 0.4947694555212097 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 13}. Best is trial 9 with value: 0.5422086955303955.
[I 2026-01-22 09:09:58,433] Trial 11 finished with value: 0.5385124972206821 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 11}. Best is trial 9 with value: 0.5422086955303955.
[I 2026-01-22 09:10:07,284] Trial 12 finished with value: 0.5378246115915378 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 623, 'max_depth': 11}. Best is trial 9 with value: 0.5422086955303955.
[I 2026-01-22 09:10:15,452] Trial 13 finished with value: 0.5342155474684707 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 489, 'max_depth': 11}. Best is trial 9 with value: 0.5422086955303955.
[I 2026-01-22 09:10:23,881] Trial 14 finished with value: 0.5405737675619713 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 490, 'max_depth': 14}. Best is trial 9 with value: 0.5422086955303955.
[I 2026-01-22 09:10:29,419] Trial 15 finished with value: 0.4817880239620472 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 434, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 9 with value: 0.5422086955303955.
[I 2026-01-22 09:10:37,543] Trial 16 finished with value: 0.5582059852749726 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 521, 'max_depth': 16}. Best is trial 16 with value: 0.5582059852749726.
[I 2026-01-22 09:10:44,944] Trial 17 finished with value: 0.5608801800737 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 545, 'max_depth': 17}. Best is trial 17 with value: 0.5608801800737.
[I 2026-01-22 09:10:52,461] Trial 18 finished with value: 0.5567738319168158 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 450, 'max_depth': 17}. Best is trial 17 with value: 0.5608801800737.
[I 2026-01-22 09:10:57,285] Trial 19 finished with value: 0.5843456527281872 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 258, 'lr': 0.09983831247079358, 'max_depth': 4}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:11:02,476] Trial 20 finished with value: 0.5223035391532527 and parameters: {'model': 'GB', 'top_k': 8, 'n_estimators': 227, 'lr': 0.09875121663184058, 'max_depth': 2}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:11:07,047] Trial 21 finished with value: 0.5562778258295867 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 227, 'lr': 0.09844175411000243, 'max_depth': 4}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:11:12,447] Trial 22 finished with value: 0.43459849563971564 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 267, 'lr': 0.04753132614308796, 'max_depth': 3}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:11:17,424] Trial 23 finished with value: 0.5602156559200578 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 264, 'lr': 0.07273644802724408, 'max_depth': 4}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:11:21,878] Trial 24 finished with value: 0.5212613340574339 and parameters: {'model': 'GB', 'top_k': 8, 'n_estimators': 201, 'lr': 0.07718039883393228, 'max_depth': 4}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:11:27,710] Trial 25 finished with value: 0.5069075804216231 and parameters: {'model': 'GB', 'top_k': 6, 'n_estimators': 267, 'lr': 0.06163205207550329, 'max_depth': 4}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:11:33,003] Trial 26 finished with value: 0.5121684363327544 and parameters: {'model': 'GB', 'top_k': 8, 'n_estimators': 324, 'lr': 0.08680766547638256, 'max_depth': 4}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:11:38,481] Trial 27 finished with value: 0.4769681454260882 and parameters: {'model': 'GB', 'top_k': 6, 'n_estimators': 265, 'lr': 0.06785754728273695, 'max_depth': 3}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:11:43,043] Trial 28 finished with value: 0.5025849883792175 and parameters: {'model': 'GB', 'top_k': 9, 'n_estimators': 294, 'lr': 0.08818812292328101, 'max_depth': 2}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:11:53,353] Trial 29 finished with value: 0.4886441796688502 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 568, 'max_depth': 9}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:12:00,531] Trial 30 finished with value: 0.5392085151675665 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 352, 'max_depth': 20}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:12:08,684] Trial 31 finished with value: 0.5606437176313632 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 517, 'max_depth': 17}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:12:16,110] Trial 32 finished with value: 0.521472365793586 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 460, 'max_depth': 18}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:12:23,790] Trial 33 finished with value: 0.5299986909551615 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 568, 'max_depth': 17}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:12:29,205] Trial 34 finished with value: 0.4283321531575999 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 240, 'lr': 0.040757520845189535, 'max_depth': 4}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:12:35,468] Trial 35 finished with value: 0.5540153215847955 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 408, 'max_depth': 15}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:12:41,413] Trial 36 finished with value: 0.4985737396313744 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 506, 'max_depth': 5, 'lr': 0.029743941788344032, 'subsample': 0.9870028556379348, 'colsample': 0.9985807136182534}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:12:52,085] Trial 37 finished with value: 0.503482577923449 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 590, 'max_depth': 9}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:12:58,547] Trial 38 finished with value: 0.5131993459625834 and parameters: {'model': 'GB', 'top_k': 8, 'n_estimators': 329, 'lr': 0.09311494461876985, 'max_depth': 4}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:13:02,522] Trial 39 finished with value: 0.5672703673086464 and parameters: {'model': 'XGB', 'top_k': 7, 'n_estimators': 477, 'max_depth': 5, 'lr': 0.07811332943122444, 'subsample': 0.7117451704166062, 'colsample': 0.7283304266532742}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:13:08,256] Trial 40 finished with value: 0.5378625067467229 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 530, 'max_depth': 5, 'lr': 0.08163500079116179, 'subsample': 0.7023111356225831, 'colsample': 0.7000786336914138}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:13:12,278] Trial 41 finished with value: 0.5338884525456903 and parameters: {'model': 'XGB', 'top_k': 7, 'n_estimators': 475, 'max_depth': 5, 'lr': 0.07069919871872378, 'subsample': 0.7075985785836707, 'colsample': 0.7877513776945342}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:13:16,044] Trial 42 finished with value: 0.5176884062011876 and parameters: {'model': 'XGB', 'top_k': 6, 'n_estimators': 427, 'max_depth': 5, 'lr': 0.07757155682237123, 'subsample': 0.8969849358674997, 'colsample': 0.7639164470775711}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:13:21,373] Trial 43 finished with value: 0.4805591788052001 and parameters: {'model': 'XGB', 'top_k': 5, 'n_estimators': 508, 'max_depth': 4, 'lr': 0.06188484155524772, 'subsample': 0.7503104628023365, 'colsample': 0.8572231916682164}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:13:25,353] Trial 44 finished with value: 0.5091483755386601 and parameters: {'model': 'XGB', 'top_k': 8, 'n_estimators': 545, 'max_depth': 5, 'lr': 0.09166986283917945, 'subsample': 0.8633750233646987, 'colsample': 0.9235797661596092}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:13:34,167] Trial 45 finished with value: 0.5159989337019493 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 670, 'max_depth': 9}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:13:39,829] Trial 46 finished with value: 0.5556044250827606 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 343, 'max_depth': 18}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:13:48,792] Trial 47 finished with value: 0.5091942596887253 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 389, 'max_depth': 15}. Best is trial 19 with value: 0.5843456527281872.
[I 2026-01-22 09:13:52,549] Trial 48 finished with value: 0.5137418605837973 and parameters: {'model': 'XGB', 'top_k': 6, 'n_estimators': 513, 'max_depth': 4, 'lr': 0.07571736741404522, 'subsample': 0.9709480467755791, 'colsample': 0.7076337532076513}. Best is trial 19 with value: 0.5843456527281872.

[I 2026-01-22 09:14:01,971] A new study created in memory with name: no-name-498dcb0b-7253-46c1-9bee-2d615aa65b58

[I 2026-01-22 09:14:01,964] Trial 49 finished with value: 0.5374087997500505 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 636, 'max_depth': 16}. Best is trial 19 with value: 0.5843456527281872.

🔍 Optimizing for Fe FC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 09:14:09,839] Trial 0 finished with value: 0.32846109212691144 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.32846109212691144.
[I 2026-01-22 09:14:18,191] Trial 1 finished with value: 0.4580476427933645 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.4580476427933645.
[I 2026-01-22 09:14:23,932] Trial 2 finished with value: 0.36637656214668457 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.4580476427933645.
[I 2026-01-22 09:14:31,145] Trial 3 finished with value: 0.39566741450117604 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.4580476427933645.
[I 2026-01-22 09:14:36,260] Trial 4 finished with value: 0.364285265922453 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.4580476427933645.
[I 2026-01-22 09:14:42,124] Trial 5 finished with value: 0.39240556383358005 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.4580476427933645.
[I 2026-01-22 09:14:54,468] Trial 6 finished with value: 0.40281660278873543 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.4580476427933645.
[I 2026-01-22 09:15:00,685] Trial 7 finished with value: 0.35927659154666347 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.4580476427933645.
[I 2026-01-22 09:15:04,504] Trial 8 finished with value: 0.38166753650537616 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.4580476427933645.
[I 2026-01-22 09:15:13,729] Trial 9 finished with value: 0.4615429276008764 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 9 with value: 0.4615429276008764.
[I 2026-01-22 09:15:21,811] Trial 10 finished with value: 0.3287008793979629 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 13}. Best is trial 9 with value: 0.4615429276008764.
[I 2026-01-22 09:15:30,995] Trial 11 finished with value: 0.4650456809828998 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 11}. Best is trial 11 with value: 0.4650456809828998.
[I 2026-01-22 09:15:39,725] Trial 12 finished with value: 0.46260533497626727 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 522, 'max_depth': 12}. Best is trial 11 with value: 0.4650456809828998.
[I 2026-01-22 09:15:47,045] Trial 13 finished with value: 0.4682479924257402 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 474, 'max_depth': 15}. Best is trial 13 with value: 0.4682479924257402.
[I 2026-01-22 09:15:54,986] Trial 14 finished with value: 0.46908218702316307 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 460, 'max_depth': 16}. Best is trial 14 with value: 0.46908218702316307.
[I 2026-01-22 09:16:00,073] Trial 15 finished with value: 0.375998491957652 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 432, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 14 with value: 0.46908218702316307.
[I 2026-01-22 09:16:08,282] Trial 16 finished with value: 0.4792415203477656 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 486, 'max_depth': 16}. Best is trial 16 with value: 0.4792415203477656.
[I 2026-01-22 09:16:15,698] Trial 17 finished with value: 0.4796453562687649 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 467, 'max_depth': 18}. Best is trial 17 with value: 0.4796453562687649.
[I 2026-01-22 09:16:23,156] Trial 18 finished with value: 0.4436773790651786 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 490, 'max_depth': 18}. Best is trial 17 with value: 0.4796453562687649.
[I 2026-01-22 09:16:28,497] Trial 19 finished with value: 0.3856013718054173 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 211, 'lr': 0.09983831247079358, 'max_depth': 4}. Best is trial 17 with value: 0.4796453562687649.
[I 2026-01-22 09:16:36,839] Trial 20 finished with value: 0.48018009139017737 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 582, 'max_depth': 17}. Best is trial 20 with value: 0.48018009139017737.
[I 2026-01-22 09:16:45,814] Trial 21 finished with value: 0.480648149937836 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 594, 'max_depth': 17}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:16:54,770] Trial 22 finished with value: 0.45914277991141417 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 605, 'max_depth': 20}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:17:02,645] Trial 23 finished with value: 0.47246587506699883 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 569, 'max_depth': 18}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:17:11,959] Trial 24 finished with value: 0.4434852725977475 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 659, 'max_depth': 17}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:17:20,617] Trial 25 finished with value: 0.44154204071267794 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 577, 'max_depth': 20}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:17:28,014] Trial 26 finished with value: 0.45518934326158067 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 514, 'max_depth': 18}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:17:34,325] Trial 27 finished with value: 0.4114308257098342 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 440, 'lr': 0.0399204177340166, 'max_depth': 2}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:17:47,055] Trial 28 finished with value: 0.404250680505589 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 632, 'max_depth': 17}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:17:59,214] Trial 29 finished with value: 0.36424645796387817 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 695, 'max_depth': 14}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:18:06,665] Trial 30 finished with value: 0.460859669145257 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 566, 'max_depth': 19}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:18:14,771] Trial 31 finished with value: 0.47948654493771115 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 498, 'max_depth': 16}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:18:23,799] Trial 32 finished with value: 0.47271196657872394 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 605, 'max_depth': 16}. Best is trial 21 with value: 0.480648149937836.
[I 2026-01-22 09:18:30,897] Trial 33 finished with value: 0.4830170536514113 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 514, 'max_depth': 17}. Best is trial 33 with value: 0.4830170536514113.
[I 2026-01-22 09:18:39,345] Trial 34 finished with value: 0.46852869177538103 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 531, 'max_depth': 17}. Best is trial 33 with value: 0.4830170536514113.
[I 2026-01-22 09:18:47,988] Trial 35 finished with value: 0.4649921233382067 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 634, 'max_depth': 19}. Best is trial 33 with value: 0.4830170536514113.
[I 2026-01-22 09:18:53,187] Trial 36 finished with value: 0.35327474053731656 and parameters: {'model': 'XGB', 'top_k': 10, 'n_estimators': 550, 'max_depth': 6, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 33 with value: 0.4830170536514113.
[I 2026-01-22 09:19:02,082] Trial 37 finished with value: 0.3664617500644963 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 429, 'max_depth': 15}. Best is trial 33 with value: 0.4830170536514113.
[I 2026-01-22 09:19:10,131] Trial 38 finished with value: 0.45545574681771184 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 588, 'max_depth': 18}. Best is trial 33 with value: 0.4830170536514113.
[I 2026-01-22 09:19:15,505] Trial 39 finished with value: 0.3144580856926167 and parameters: {'model': 'XGB', 'top_k': 8, 'n_estimators': 411, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 33 with value: 0.4830170536514113.
[I 2026-01-22 09:19:22,529] Trial 40 finished with value: 0.3492372905090978 and parameters: {'model': 'GB', 'top_k': 11, 'n_estimators': 464, 'lr': 0.032894255032331704, 'max_depth': 4}. Best is trial 33 with value: 0.4830170536514113.
[I 2026-01-22 09:19:30,668] Trial 41 finished with value: 0.48307798311298233 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 507, 'max_depth': 17}. Best is trial 41 with value: 0.48307798311298233.
[I 2026-01-22 09:19:38,300] Trial 42 finished with value: 0.48321330126223794 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 510, 'max_depth': 17}. Best is trial 42 with value: 0.48321330126223794.
[I 2026-01-22 09:19:46,153] Trial 43 finished with value: 0.4610533141565501 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 555, 'max_depth': 17}. Best is trial 42 with value: 0.48321330126223794.
[I 2026-01-22 09:19:54,208] Trial 44 finished with value: 0.4659522138796664 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 508, 'max_depth': 15}. Best is trial 42 with value: 0.48321330126223794.
[I 2026-01-22 09:20:01,407] Trial 45 finished with value: 0.475331413653133 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 533, 'max_depth': 14}. Best is trial 42 with value: 0.48321330126223794.
[I 2026-01-22 09:20:10,666] Trial 46 finished with value: 0.46909517384074206 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 633, 'max_depth': 17}. Best is trial 42 with value: 0.48321330126223794.
[I 2026-01-22 09:20:17,925] Trial 47 finished with value: 0.3651853613426089 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 545, 'max_depth': 5, 'lr': 0.012035429732013193, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 42 with value: 0.48321330126223794.
[I 2026-01-22 09:20:25,706] Trial 48 finished with value: 0.47829694284747537 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 587, 'max_depth': 19}. Best is trial 42 with value: 0.48321330126223794.

[I 2026-01-22 09:20:36,771] A new study created in memory with name: no-name-fc8257cf-c2b5-4034-b708-a301dcbee8bb

[I 2026-01-22 09:20:36,764] Trial 49 finished with value: 0.40079774608725954 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 519, 'max_depth': 15}. Best is trial 42 with value: 0.48321330126223794.

🔍 Optimizing for Ni Concentration

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 09:20:44,525] Trial 0 finished with value: 0.20924518713819634 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.20924518713819634.
[I 2026-01-22 09:20:52,855] Trial 1 finished with value: 0.3191826201922705 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:20:57,954] Trial 2 finished with value: 0.13072449914457346 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:21:05,115] Trial 3 finished with value: 0.24508211683404876 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:21:09,937] Trial 4 finished with value: 0.12045573230165844 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:21:15,539] Trial 5 finished with value: 0.10951029101907132 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:21:27,656] Trial 6 finished with value: 0.2431855749229494 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:21:32,360] Trial 7 finished with value: 0.10992391518597266 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:21:36,186] Trial 8 finished with value: 0.14572686640269464 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:21:44,143] Trial 9 finished with value: 0.307804792599219 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:21:52,598] Trial 10 finished with value: 0.2865388702434224 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 12}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:22:01,710] Trial 11 finished with value: 0.31026269859900935 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 12}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:22:11,164] Trial 12 finished with value: 0.3175977937013402 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 650, 'max_depth': 11}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:22:19,759] Trial 13 finished with value: 0.3189011425465803 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 698, 'max_depth': 10}. Best is trial 1 with value: 0.3191826201922705.
[I 2026-01-22 09:22:29,371] Trial 14 finished with value: 0.31919155538557464 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 687, 'max_depth': 10}. Best is trial 14 with value: 0.31919155538557464.
[I 2026-01-22 09:22:35,407] Trial 15 finished with value: 0.1833965802884318 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 443, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 14 with value: 0.31919155538557464.
[I 2026-01-22 09:22:43,467] Trial 16 finished with value: 0.272789744620488 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 635, 'max_depth': 15}. Best is trial 14 with value: 0.31919155538557464.
[I 2026-01-22 09:22:51,890] Trial 17 finished with value: 0.29810056111641325 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 591, 'max_depth': 9}. Best is trial 14 with value: 0.31919155538557464.
[I 2026-01-22 09:22:59,309] Trial 18 finished with value: 0.31372493406573654 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 485, 'max_depth': 14}. Best is trial 14 with value: 0.31919155538557464.
[I 2026-01-22 09:23:04,644] Trial 19 finished with value: 0.14564629967741388 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 258, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 14 with value: 0.31919155538557464.
[I 2026-01-22 09:23:13,017] Trial 20 finished with value: 0.2932500024656943 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 634, 'max_depth': 19}. Best is trial 14 with value: 0.31919155538557464.
[I 2026-01-22 09:23:22,049] Trial 21 finished with value: 0.3194919750135835 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 679, 'max_depth': 10}. Best is trial 21 with value: 0.3194919750135835.
[I 2026-01-22 09:23:31,586] Trial 22 finished with value: 0.3198435258523401 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 670, 'max_depth': 10}. Best is trial 22 with value: 0.3198435258523401.
[I 2026-01-22 09:23:41,289] Trial 23 finished with value: 0.3069385334593819 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 672, 'max_depth': 13}. Best is trial 22 with value: 0.3198435258523401.
[I 2026-01-22 09:23:48,925] Trial 24 finished with value: 0.31454317536330434 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 591, 'max_depth': 9}. Best is trial 22 with value: 0.3198435258523401.
[I 2026-01-22 09:23:59,108] Trial 25 finished with value: 0.32056453517022704 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 668, 'max_depth': 17}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:24:07,780] Trial 26 finished with value: 0.2969206542566437 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 561, 'max_depth': 17}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:24:15,627] Trial 27 finished with value: 0.12032883094201526 and parameters: {'model': 'GB', 'top_k': 13, 'n_estimators': 472, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:24:30,663] Trial 28 finished with value: 0.24202029230491268 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 661, 'max_depth': 17}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:24:42,762] Trial 29 finished with value: 0.2461401452694329 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 610, 'max_depth': 17}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:24:50,483] Trial 30 finished with value: 0.31401309022379986 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 515, 'max_depth': 20}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:25:00,140] Trial 31 finished with value: 0.31927541685031635 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 697, 'max_depth': 10}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:25:09,703] Trial 32 finished with value: 0.30357986070836607 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 668, 'max_depth': 11}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:25:18,137] Trial 33 finished with value: 0.31381744520933497 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 698, 'max_depth': 9}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:25:27,423] Trial 34 finished with value: 0.3172924752608547 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 617, 'max_depth': 11}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:25:37,121] Trial 35 finished with value: 0.30725421606337017 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 646, 'max_depth': 13}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:25:40,856] Trial 36 finished with value: 0.030374325188444563 and parameters: {'model': 'XGB', 'top_k': 14, 'n_estimators': 576, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:25:53,916] Trial 37 finished with value: 0.24703949546261503 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 670, 'max_depth': 10}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:26:03,617] Trial 38 finished with value: 0.3100400096130526 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 629, 'max_depth': 16}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:26:07,638] Trial 39 finished with value: 0.12611252965216238 and parameters: {'model': 'XGB', 'top_k': 15, 'n_estimators': 582, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:26:16,388] Trial 40 finished with value: 0.1457230003572541 and parameters: {'model': 'GB', 'top_k': 13, 'n_estimators': 487, 'lr': 0.032894255032331704, 'max_depth': 4}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:26:26,026] Trial 41 finished with value: 0.3194919750135835 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 679, 'max_depth': 10}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:26:34,307] Trial 42 finished with value: 0.312783152549511 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 678, 'max_depth': 9}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:26:43,575] Trial 43 finished with value: 0.31618213550666935 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 656, 'max_depth': 10}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:26:53,082] Trial 44 finished with value: 0.31783258166500855 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 651, 'max_depth': 11}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:27:02,455] Trial 45 finished with value: 0.30767654992789956 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 617, 'max_depth': 13}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:27:11,280] Trial 46 finished with value: 0.3130890119724446 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 675, 'max_depth': 12}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:27:18,508] Trial 47 finished with value: 0.07233855283845583 and parameters: {'model': 'XGB', 'top_k': 15, 'n_estimators': 573, 'max_depth': 5, 'lr': 0.012035429732013193, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 25 with value: 0.32056453517022704.
[I 2026-01-22 09:27:27,341] Trial 48 finished with value: 0.30645773047574715 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 698, 'max_depth': 10}. Best is trial 25 with value: 0.32056453517022704.

[I 2026-01-22 09:27:35,559] A new study created in memory with name: no-name-c1b90037-ee1c-4eb8-8f42-3d025dd19560

[I 2026-01-22 09:27:35,551] Trial 49 finished with value: 0.24234909860831647 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 435, 'max_depth': 9}. Best is trial 25 with value: 0.32056453517022704.

🔍 Optimizing for Cu FC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 09:27:43,289] Trial 0 finished with value: 0.6494536443799585 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.6494536443799585.
[I 2026-01-22 09:27:52,484] Trial 1 finished with value: 0.669687094663523 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:27:56,106] Trial 2 finished with value: 0.6406545669645431 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:28:03,700] Trial 3 finished with value: 0.64115624388266 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:28:07,751] Trial 4 finished with value: 0.6398747855711457 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:28:13,372] Trial 5 finished with value: 0.6320071338543662 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:28:25,383] Trial 6 finished with value: 0.6369567444634289 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:28:29,862] Trial 7 finished with value: 0.6474331884983633 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:28:33,583] Trial 8 finished with value: 0.6358505538160838 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:28:41,623] Trial 9 finished with value: 0.6648749464520488 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:28:50,179] Trial 10 finished with value: 0.6284239356742647 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 12}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:28:59,432] Trial 11 finished with value: 0.6646697511335813 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 12}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:29:08,766] Trial 12 finished with value: 0.6650026867088186 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 623, 'max_depth': 11}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:29:17,305] Trial 13 finished with value: 0.6693330624503215 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 682, 'max_depth': 10}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:29:26,994] Trial 14 finished with value: 0.6693691652555371 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 685, 'max_depth': 10}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:29:32,903] Trial 15 finished with value: 0.6253238982999052 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 434, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:29:41,142] Trial 16 finished with value: 0.6539315972614876 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 635, 'max_depth': 15}. Best is trial 1 with value: 0.669687094663523.
[I 2026-01-22 09:29:48,784] Trial 17 finished with value: 0.6735533587360265 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 467, 'max_depth': 9}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:29:55,798] Trial 18 finished with value: 0.6705974037608505 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 466, 'max_depth': 18}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:30:01,069] Trial 19 finished with value: 0.6250468351209159 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 211, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:30:08,125] Trial 20 finished with value: 0.669817885390982 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 481, 'max_depth': 19}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:30:15,956] Trial 21 finished with value: 0.6713386889770117 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 459, 'max_depth': 20}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:30:23,363] Trial 22 finished with value: 0.6571813122398427 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 484, 'max_depth': 20}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:30:30,579] Trial 23 finished with value: 0.6668984839096487 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 442, 'max_depth': 17}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:30:38,046] Trial 24 finished with value: 0.6661865867573235 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 443, 'max_depth': 17}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:30:45,429] Trial 25 finished with value: 0.6684775616802019 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 522, 'max_depth': 17}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:30:53,310] Trial 26 finished with value: 0.6567539933025124 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 462, 'max_depth': 20}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:31:00,663] Trial 27 finished with value: 0.6433740315062362 and parameters: {'model': 'GB', 'top_k': 13, 'n_estimators': 419, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:31:11,419] Trial 28 finished with value: 0.6404706683196844 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 515, 'max_depth': 18}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:31:22,386] Trial 29 finished with value: 0.6344555379054009 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 573, 'max_depth': 18}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:31:30,457] Trial 30 finished with value: 0.6686419361065068 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 498, 'max_depth': 14}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:31:37,369] Trial 31 finished with value: 0.6693542835004344 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 469, 'max_depth': 19}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:31:45,340] Trial 32 finished with value: 0.6567687323821019 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 481, 'max_depth': 19}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:31:52,755] Trial 33 finished with value: 0.6671578182538312 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 411, 'max_depth': 16}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:32:00,029] Trial 34 finished with value: 0.6706702502070377 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 501, 'max_depth': 20}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:32:08,509] Trial 35 finished with value: 0.6647041669976004 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 509, 'max_depth': 20}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:32:11,783] Trial 36 finished with value: 0.6254516451802536 and parameters: {'model': 'XGB', 'top_k': 8, 'n_estimators': 459, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:32:22,441] Trial 37 finished with value: 0.6338897784586721 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 533, 'max_depth': 18}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:32:31,157] Trial 38 finished with value: 0.6701070496616286 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 556, 'max_depth': 20}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:32:34,544] Trial 39 finished with value: 0.6465111029724498 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 427, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:32:40,984] Trial 40 finished with value: 0.6340075223990838 and parameters: {'model': 'GB', 'top_k': 13, 'n_estimators': 337, 'lr': 0.032894255032331704, 'max_depth': 4}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:32:49,794] Trial 41 finished with value: 0.6701012448004466 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 563, 'max_depth': 20}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:32:57,247] Trial 42 finished with value: 0.6686792184881122 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 396, 'max_depth': 19}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:33:04,549] Trial 43 finished with value: 0.6696376383486513 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 498, 'max_depth': 14}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:33:13,519] Trial 44 finished with value: 0.6660036161654419 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 554, 'max_depth': 20}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:33:22,361] Trial 45 finished with value: 0.6693073639956661 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 592, 'max_depth': 13}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:33:29,492] Trial 46 finished with value: 0.6668805052660879 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 458, 'max_depth': 18}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:33:35,035] Trial 47 finished with value: 0.6215376133675937 and parameters: {'model': 'XGB', 'top_k': 10, 'n_estimators': 495, 'max_depth': 5, 'lr': 0.012035429732013193, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 17 with value: 0.6735533587360265.
[I 2026-01-22 09:33:42,421] Trial 48 finished with value: 0.6573714756434621 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 531, 'max_depth': 19}. Best is trial 17 with value: 0.6735533587360265.

[I 2026-01-22 09:33:54,072] A new study created in memory with name: no-name-4a8ecc81-30fa-460c-b56f-7ab9d7db7107

[I 2026-01-22 09:33:54,066] Trial 49 finished with value: 0.6404941835498124 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 583, 'max_depth': 9}. Best is trial 17 with value: 0.6735533587360265.

🔍 Optimizing for Zn FC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 09:34:01,977] Trial 0 finished with value: 0.6615408500829512 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.6615408500829512.
[I 2026-01-22 09:34:10,546] Trial 1 finished with value: 0.7136959051606164 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.7136959051606164.
[I 2026-01-22 09:34:15,473] Trial 2 finished with value: 0.6517924860221294 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.7136959051606164.
[I 2026-01-22 09:34:22,932] Trial 3 finished with value: 0.6728256696315336 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.7136959051606164.
[I 2026-01-22 09:34:27,630] Trial 4 finished with value: 0.6389393189357145 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.7136959051606164.
[I 2026-01-22 09:34:33,532] Trial 5 finished with value: 0.652872256475004 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.7136959051606164.
[I 2026-01-22 09:34:45,616] Trial 6 finished with value: 0.6708068520976449 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.7136959051606164.
[I 2026-01-22 09:34:50,884] Trial 7 finished with value: 0.6550877505723603 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.7136959051606164.
[I 2026-01-22 09:34:54,409] Trial 8 finished with value: 0.6389607462056965 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.7136959051606164.
[I 2026-01-22 09:35:03,183] Trial 9 finished with value: 0.7154412695717172 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:35:11,088] Trial 10 finished with value: 0.6419378748415322 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 13}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:35:20,136] Trial 11 finished with value: 0.71085931786535 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 11}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:35:29,656] Trial 12 finished with value: 0.7116792439894988 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 623, 'max_depth': 11}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:35:37,180] Trial 13 finished with value: 0.7106704495872105 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 489, 'max_depth': 11}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:35:45,360] Trial 14 finished with value: 0.698244615234346 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 490, 'max_depth': 14}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:35:50,094] Trial 15 finished with value: 0.6622994852006856 and parameters: {'model': 'GB', 'top_k': 15, 'n_estimators': 241, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:35:58,542] Trial 16 finished with value: 0.6886747344571275 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 561, 'max_depth': 16}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:36:08,157] Trial 17 finished with value: 0.7086513129380304 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 678, 'max_depth': 10}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:36:16,579] Trial 18 finished with value: 0.7038886482037823 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 638, 'max_depth': 13}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:36:23,633] Trial 19 finished with value: 0.5849136152468744 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 446, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:36:32,704] Trial 20 finished with value: 0.7106106267523222 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 551, 'max_depth': 17}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:36:40,886] Trial 21 finished with value: 0.7135283042154643 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 630, 'max_depth': 10}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:36:49,891] Trial 22 finished with value: 0.714146406239222 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 596, 'max_depth': 10}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:36:58,456] Trial 23 finished with value: 0.7151287185016153 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 567, 'max_depth': 9}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:37:05,977] Trial 24 finished with value: 0.7109587968087968 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 589, 'max_depth': 9}. Best is trial 9 with value: 0.7154412695717172.
[I 2026-01-22 09:37:14,646] Trial 25 finished with value: 0.7155600996228647 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 523, 'max_depth': 12}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:37:22,970] Trial 26 finished with value: 0.7117784169771669 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 516, 'max_depth': 12}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:37:30,598] Trial 27 finished with value: 0.6545565265064112 and parameters: {'model': 'GB', 'top_k': 14, 'n_estimators': 430, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:37:41,651] Trial 28 finished with value: 0.6755874875650594 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 516, 'max_depth': 13}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:37:51,246] Trial 29 finished with value: 0.6750096706025438 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 462, 'max_depth': 12}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:37:59,039] Trial 30 finished with value: 0.7107759227438016 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 561, 'max_depth': 9}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:38:07,229] Trial 31 finished with value: 0.7151502917795145 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 587, 'max_depth': 9}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:38:15,448] Trial 32 finished with value: 0.7140321671313509 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 526, 'max_depth': 9}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:38:23,322] Trial 33 finished with value: 0.710288885578085 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 573, 'max_depth': 12}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:38:33,262] Trial 34 finished with value: 0.7100799201261088 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 651, 'max_depth': 14}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:38:40,804] Trial 35 finished with value: 0.7126488133687985 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 483, 'max_depth': 9}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:38:44,473] Trial 36 finished with value: 0.6342074445227082 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 529, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:38:57,573] Trial 37 finished with value: 0.673319384682112 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 610, 'max_depth': 11}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:39:06,115] Trial 38 finished with value: 0.6993184082862637 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 576, 'max_depth': 15}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:39:09,979] Trial 39 finished with value: 0.6582638276207209 and parameters: {'model': 'XGB', 'top_k': 12, 'n_estimators': 545, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:39:19,329] Trial 40 finished with value: 0.6610177720675958 and parameters: {'model': 'GB', 'top_k': 15, 'n_estimators': 475, 'lr': 0.032894255032331704, 'max_depth': 4}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:39:27,682] Trial 41 finished with value: 0.7142019626426604 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 588, 'max_depth': 10}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:39:35,266] Trial 42 finished with value: 0.7143632533716808 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 509, 'max_depth': 9}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:39:44,051] Trial 43 finished with value: 0.7113295507880243 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 504, 'max_depth': 20}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:39:51,285] Trial 44 finished with value: 0.7094897673029633 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 540, 'max_depth': 9}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:39:59,709] Trial 45 finished with value: 0.7120710883025785 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 509, 'max_depth': 12}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:40:09,101] Trial 46 finished with value: 0.7112090460080601 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 612, 'max_depth': 11}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:40:14,814] Trial 47 finished with value: 0.6466032640670993 and parameters: {'model': 'XGB', 'top_k': 14, 'n_estimators': 557, 'max_depth': 5, 'lr': 0.012035429732013193, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 25 with value: 0.7155600996228647.
[I 2026-01-22 09:40:24,901] Trial 48 finished with value: 0.6757003302290685 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 416, 'max_depth': 10}. Best is trial 25 with value: 0.7155600996228647.

[I 2026-01-22 09:40:34,780] A new study created in memory with name: no-name-912d3889-1a7b-4434-a987-418a1385966a

[I 2026-01-22 09:40:34,773] Trial 49 finished with value: 0.7120431604115556 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 661, 'max_depth': 11}. Best is trial 25 with value: 0.7155600996228647.

🔍 Optimizing for Rb Concentration

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 09:40:41,847] Trial 0 finished with value: 0.1852636960757013 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.1852636960757013.
[I 2026-01-22 09:40:51,158] Trial 1 finished with value: 0.2131732519235044 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.2131732519235044.
[I 2026-01-22 09:40:54,622] Trial 2 finished with value: 0.2025276941472091 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.2131732519235044.
[I 2026-01-22 09:41:03,340] Trial 3 finished with value: 0.22707743764546146 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 3 with value: 0.22707743764546146.
[I 2026-01-22 09:41:06,701] Trial 4 finished with value: 0.19805888092546606 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 3 with value: 0.22707743764546146.
[I 2026-01-22 09:41:13,591] Trial 5 finished with value: 0.13895651921759372 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 3 with value: 0.22707743764546146.
[I 2026-01-22 09:41:26,430] Trial 6 finished with value: 0.21331421356244737 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 3 with value: 0.22707743764546146.
[I 2026-01-22 09:41:29,720] Trial 7 finished with value: 0.19151614209767218 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 3 with value: 0.22707743764546146.
[I 2026-01-22 09:41:33,330] Trial 8 finished with value: 0.15657248675569846 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 3 with value: 0.22707743764546146.
[I 2026-01-22 09:41:41,956] Trial 9 finished with value: 0.22812821953871576 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 9 with value: 0.22812821953871576.
[I 2026-01-22 09:41:50,930] Trial 10 finished with value: 0.22342019154891313 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 13}. Best is trial 9 with value: 0.22812821953871576.
[I 2026-01-22 09:42:02,203] Trial 11 finished with value: 0.22950425617437858 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 511, 'max_depth': 15}. Best is trial 11 with value: 0.22950425617437858.
[I 2026-01-22 09:42:09,216] Trial 12 finished with value: 0.22818497206098282 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 502, 'max_depth': 14}. Best is trial 11 with value: 0.22950425617437858.
[I 2026-01-22 09:42:14,351] Trial 13 finished with value: 0.1816958116424316 and parameters: {'model': 'GB', 'top_k': 8, 'n_estimators': 220, 'lr': 0.013253584124164247, 'max_depth': 2}. Best is trial 11 with value: 0.22950425617437858.
[I 2026-01-22 09:42:21,118] Trial 14 finished with value: 0.23625840098017728 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 455, 'max_depth': 16}. Best is trial 14 with value: 0.23625840098017728.
[I 2026-01-22 09:42:30,704] Trial 15 finished with value: 0.2217320181981572 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 451, 'max_depth': 17}. Best is trial 14 with value: 0.23625840098017728.
[I 2026-01-22 09:42:41,056] Trial 16 finished with value: 0.23157524745116706 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 444, 'max_depth': 16}. Best is trial 14 with value: 0.23625840098017728.
[I 2026-01-22 09:42:47,785] Trial 17 finished with value: 0.22537315195124236 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 449, 'max_depth': 18}. Best is trial 14 with value: 0.23625840098017728.
[I 2026-01-22 09:42:54,002] Trial 18 finished with value: 0.23277169498687175 and parameters: {'model': 'GB', 'top_k': 8, 'n_estimators': 430, 'lr': 0.0976534055328193, 'max_depth': 2}. Best is trial 14 with value: 0.23625840098017728.
[I 2026-01-22 09:42:59,260] Trial 19 finished with value: 0.2248525712989608 and parameters: {'model': 'GB', 'top_k': 8, 'n_estimators': 419, 'lr': 0.09767024756700712, 'max_depth': 2}. Best is trial 14 with value: 0.23625840098017728.
[I 2026-01-22 09:43:05,138] Trial 20 finished with value: 0.152681993498082 and parameters: {'model': 'GB', 'top_k': 7, 'n_estimators': 315, 'lr': 0.0997547900738377, 'max_depth': 3}. Best is trial 14 with value: 0.23625840098017728.
[I 2026-01-22 09:43:10,721] Trial 21 finished with value: 0.1913854945152325 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 430, 'lr': 0.06301257511163616, 'max_depth': 2}. Best is trial 14 with value: 0.23625840098017728.
[I 2026-01-22 09:43:18,697] Trial 22 finished with value: 0.16460279435211145 and parameters: {'model': 'GB', 'top_k': 11, 'n_estimators': 413, 'lr': 0.037871735145094156, 'max_depth': 4}. Best is trial 14 with value: 0.23625840098017728.
[I 2026-01-22 09:43:29,074] Trial 23 finished with value: 0.23323424142195465 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 468, 'max_depth': 16}. Best is trial 14 with value: 0.23625840098017728.
[I 2026-01-22 09:43:35,776] Trial 24 finished with value: 0.24033580764424983 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 475, 'max_depth': 20}. Best is trial 24 with value: 0.24033580764424983.
[I 2026-01-22 09:43:43,786] Trial 25 finished with value: 0.2591707114035923 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 481, 'max_depth': 20}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:43:51,246] Trial 26 finished with value: 0.24184977099422786 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 577, 'max_depth': 20}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:43:59,622] Trial 27 finished with value: 0.2169677158473831 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 592, 'max_depth': 20}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:44:08,077] Trial 28 finished with value: 0.24184683016806777 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 582, 'max_depth': 20}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:44:15,610] Trial 29 finished with value: 0.2509291796039871 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 604, 'max_depth': 19}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:44:24,659] Trial 30 finished with value: 0.24712499332395002 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 635, 'max_depth': 18}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:44:33,900] Trial 31 finished with value: 0.24851504083902878 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 662, 'max_depth': 18}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:44:42,630] Trial 32 finished with value: 0.24842992274450112 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 661, 'max_depth': 18}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:44:51,743] Trial 33 finished with value: 0.24946321647901143 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 684, 'max_depth': 18}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:45:01,167] Trial 34 finished with value: 0.25062634351093466 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 697, 'max_depth': 19}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:45:10,331] Trial 35 finished with value: 0.21690770479114682 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 696, 'max_depth': 19}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:45:17,954] Trial 36 finished with value: 0.21775084180392143 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 612, 'max_depth': 19}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:45:27,028] Trial 37 finished with value: 0.25040723078706034 and parameters: {'model': 'ET', 'top_k': 6, 'n_estimators': 662, 'max_depth': 19}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:45:30,414] Trial 38 finished with value: 0.14141941766803232 and parameters: {'model': 'XGB', 'top_k': 6, 'n_estimators': 556, 'max_depth': 5, 'lr': 0.040721694217705856, 'subsample': 0.9961015867374993, 'colsample': 0.9872013764250163}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:45:39,361] Trial 39 finished with value: 0.24479666114734705 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 640, 'max_depth': 17}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:45:48,412] Trial 40 finished with value: 0.2571912540935963 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 612, 'max_depth': 19}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:45:56,776] Trial 41 finished with value: 0.2561560453698868 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 660, 'max_depth': 19}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:46:05,843] Trial 42 finished with value: 0.2566906680692148 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 616, 'max_depth': 19}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:46:14,849] Trial 43 finished with value: 0.2553101273370936 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 612, 'max_depth': 17}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:46:18,229] Trial 44 finished with value: 0.23613213688885715 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 556, 'max_depth': 5, 'lr': 0.07863092344547462, 'subsample': 0.7030302963915135, 'colsample': 0.7075985785836707}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:46:26,806] Trial 45 finished with value: 0.25239935275582315 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 528, 'max_depth': 17}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:46:35,260] Trial 46 finished with value: 0.2365027224943242 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 619, 'max_depth': 20}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:46:44,231] Trial 47 finished with value: 0.2572581929734793 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 639, 'max_depth': 11}. Best is trial 25 with value: 0.2591707114035923.
[I 2026-01-22 09:46:47,648] Trial 48 finished with value: 0.17403854346255748 and parameters: {'model': 'XGB', 'top_k': 8, 'n_estimators': 574, 'max_depth': 5, 'lr': 0.027907359399850933, 'subsample': 0.9883055568182034, 'colsample': 0.9797564284788186}. Best is trial 25 with value: 0.2591707114035923.

[I 2026-01-22 09:46:56,921] A new study created in memory with name: no-name-5b33cb32-6fb4-4fee-94c1-9ce185fde377

[I 2026-01-22 09:46:56,914] Trial 49 finished with value: 0.23941750601049555 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 647, 'max_depth': 10}. Best is trial 25 with value: 0.2591707114035923.

🔍 Optimizing for Sr Concentration

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 09:47:05,021] Trial 0 finished with value: 0.796489652359909 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.796489652359909.
[I 2026-01-22 09:47:13,512] Trial 1 finished with value: 0.7911577321351081 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 0 with value: 0.796489652359909.
[I 2026-01-22 09:47:18,984] Trial 2 finished with value: 0.7849356620547385 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 0 with value: 0.796489652359909.
[I 2026-01-22 09:47:26,832] Trial 3 finished with value: 0.8012040502757835 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 3 with value: 0.8012040502757835.
[I 2026-01-22 09:47:31,367] Trial 4 finished with value: 0.7599510035844281 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 3 with value: 0.8012040502757835.
[I 2026-01-22 09:47:37,221] Trial 5 finished with value: 0.761157930749828 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 3 with value: 0.8012040502757835.
[I 2026-01-22 09:47:49,717] Trial 6 finished with value: 0.7995796419971538 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 3 with value: 0.8012040502757835.
[I 2026-01-22 09:47:55,259] Trial 7 finished with value: 0.7861575721122084 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 3 with value: 0.8012040502757835.
[I 2026-01-22 09:47:59,022] Trial 8 finished with value: 0.7612024632407315 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 3 with value: 0.8012040502757835.
[I 2026-01-22 09:48:07,895] Trial 9 finished with value: 0.7874392326485609 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 3 with value: 0.8012040502757835.
[I 2026-01-22 09:48:16,243] Trial 10 finished with value: 0.7958343529525711 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 472, 'max_depth': 16}. Best is trial 3 with value: 0.8012040502757835.
[I 2026-01-22 09:48:28,029] Trial 11 finished with value: 0.8013646450974479 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 546, 'max_depth': 20}. Best is trial 11 with value: 0.8013646450974479.
[I 2026-01-22 09:48:41,801] Trial 12 finished with value: 0.802150802033848 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 691, 'max_depth': 20}. Best is trial 12 with value: 0.802150802033848.
[I 2026-01-22 09:48:55,586] Trial 13 finished with value: 0.8028405938378864 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 695, 'max_depth': 20}. Best is trial 13 with value: 0.8028405938378864.
[I 2026-01-22 09:49:00,205] Trial 14 finished with value: 0.7847630110294317 and parameters: {'model': 'GB', 'top_k': 8, 'n_estimators': 207, 'lr': 0.011073188101939947, 'max_depth': 2}. Best is trial 13 with value: 0.8028405938378864.
[I 2026-01-22 09:49:12,818] Trial 15 finished with value: 0.8029045398974771 and parameters: {'model': 'RF', 'top_k': 8, 'n_estimators': 683, 'max_depth': 18}. Best is trial 15 with value: 0.8029045398974771.
[I 2026-01-22 09:49:25,300] Trial 16 finished with value: 0.7996817941830614 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 699, 'max_depth': 17}. Best is trial 15 with value: 0.8029045398974771.
[I 2026-01-22 09:49:36,214] Trial 17 finished with value: 0.7972284383848404 and parameters: {'model': 'RF', 'top_k': 5, 'n_estimators': 632, 'max_depth': 18}. Best is trial 15 with value: 0.8029045398974771.
[I 2026-01-22 09:49:44,215] Trial 18 finished with value: 0.7866611358662775 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 632, 'max_depth': 14}. Best is trial 15 with value: 0.8029045398974771.
[I 2026-01-22 09:49:49,737] Trial 19 finished with value: 0.7909169271882545 and parameters: {'model': 'GB', 'top_k': 8, 'n_estimators': 203, 'lr': 0.09983831247079358, 'max_depth': 4}. Best is trial 15 with value: 0.8029045398974771.
[I 2026-01-22 09:50:01,994] Trial 20 finished with value: 0.8020971968520396 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 597, 'max_depth': 18}. Best is trial 15 with value: 0.8029045398974771.
[I 2026-01-22 09:50:15,489] Trial 21 finished with value: 0.8029086509040131 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 691, 'max_depth': 20}. Best is trial 21 with value: 0.8029086509040131.
[I 2026-01-22 09:50:28,297] Trial 22 finished with value: 0.8026556412703989 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 666, 'max_depth': 19}. Best is trial 21 with value: 0.8029086509040131.
[I 2026-01-22 09:50:40,561] Trial 23 finished with value: 0.8028578288582949 and parameters: {'model': 'RF', 'top_k': 8, 'n_estimators': 662, 'max_depth': 20}. Best is trial 21 with value: 0.8029086509040131.
[I 2026-01-22 09:50:51,653] Trial 24 finished with value: 0.7994292666080887 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 594, 'max_depth': 18}. Best is trial 21 with value: 0.8029086509040131.
[I 2026-01-22 09:51:03,839] Trial 25 finished with value: 0.8028398580858571 and parameters: {'model': 'RF', 'top_k': 8, 'n_estimators': 660, 'max_depth': 17}. Best is trial 21 with value: 0.8029086509040131.
[I 2026-01-22 09:51:14,150] Trial 26 finished with value: 0.7994290196652567 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 590, 'max_depth': 19}. Best is trial 21 with value: 0.8029086509040131.
[I 2026-01-22 09:51:23,032] Trial 27 finished with value: 0.7866393429249339 and parameters: {'model': 'ET', 'top_k': 9, 'n_estimators': 660, 'max_depth': 14}. Best is trial 21 with value: 0.8029086509040131.
[I 2026-01-22 09:51:29,666] Trial 28 finished with value: 0.7692729830557925 and parameters: {'model': 'GB', 'top_k': 5, 'n_estimators': 476, 'lr': 0.041419357059636994, 'max_depth': 4}. Best is trial 21 with value: 0.8029086509040131.
[I 2026-01-22 09:51:40,730] Trial 29 finished with value: 0.797098847483354 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 619, 'max_depth': 16}. Best is trial 21 with value: 0.8029086509040131.
[I 2026-01-22 09:51:52,485] Trial 30 finished with value: 0.802929070962515 and parameters: {'model': 'RF', 'top_k': 8, 'n_estimators': 669, 'max_depth': 20}. Best is trial 30 with value: 0.802929070962515.
[I 2026-01-22 09:52:03,831] Trial 31 finished with value: 0.8028609826827606 and parameters: {'model': 'RF', 'top_k': 8, 'n_estimators': 663, 'max_depth': 20}. Best is trial 30 with value: 0.802929070962515.
[I 2026-01-22 09:52:15,800] Trial 32 finished with value: 0.8029443486138887 and parameters: {'model': 'RF', 'top_k': 8, 'n_estimators': 669, 'max_depth': 19}. Best is trial 32 with value: 0.8029443486138887.
[I 2026-01-22 09:52:27,036] Trial 33 finished with value: 0.7995643213332194 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 614, 'max_depth': 19}. Best is trial 32 with value: 0.8029443486138887.
[I 2026-01-22 09:52:38,210] Trial 34 finished with value: 0.8033752050515769 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 572, 'max_depth': 17}. Best is trial 34 with value: 0.8033752050515769.
[I 2026-01-22 09:52:42,805] Trial 35 finished with value: 0.7804846471376583 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 567, 'max_depth': 6, 'lr': 0.09850401020012867, 'subsample': 0.9831597406092863, 'colsample': 0.9908814591475331}. Best is trial 34 with value: 0.8033752050515769.
[I 2026-01-22 09:52:50,661] Trial 36 finished with value: 0.7865125210202678 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 519, 'max_depth': 17}. Best is trial 34 with value: 0.8033752050515769.
[I 2026-01-22 09:53:03,912] Trial 37 finished with value: 0.8017664738290418 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 645, 'max_depth': 13}. Best is trial 34 with value: 0.8033752050515769.
[I 2026-01-22 09:53:14,077] Trial 38 finished with value: 0.8028670100327371 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 488, 'max_depth': 19}. Best is trial 34 with value: 0.8033752050515769.
[I 2026-01-22 09:53:18,158] Trial 39 finished with value: 0.7825522956846463 and parameters: {'model': 'XGB', 'top_k': 10, 'n_estimators': 572, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 34 with value: 0.8033752050515769.
[I 2026-01-22 09:53:24,769] Trial 40 finished with value: 0.7838233688990226 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 435, 'lr': 0.032894255032331704, 'max_depth': 2}. Best is trial 34 with value: 0.8033752050515769.
[I 2026-01-22 09:53:36,950] Trial 41 finished with value: 0.8029663919501854 and parameters: {'model': 'RF', 'top_k': 8, 'n_estimators': 678, 'max_depth': 18}. Best is trial 34 with value: 0.8033752050515769.
[I 2026-01-22 09:53:49,608] Trial 42 finished with value: 0.8035528471295695 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 678, 'max_depth': 16}. Best is trial 42 with value: 0.8035528471295695.
[I 2026-01-22 09:54:01,346] Trial 43 finished with value: 0.7991963979484513 and parameters: {'model': 'RF', 'top_k': 7, 'n_estimators': 644, 'max_depth': 16}. Best is trial 42 with value: 0.8035528471295695.
[I 2026-01-22 09:54:13,883] Trial 44 finished with value: 0.8035138555901687 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 676, 'max_depth': 15}. Best is trial 42 with value: 0.8035528471295695.
[I 2026-01-22 09:54:25,537] Trial 45 finished with value: 0.8035273944653885 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 613, 'max_depth': 15}. Best is trial 42 with value: 0.8035528471295695.
[I 2026-01-22 09:54:37,267] Trial 46 finished with value: 0.8035297345852657 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 612, 'max_depth': 15}. Best is trial 42 with value: 0.8035528471295695.
[I 2026-01-22 09:54:40,992] Trial 47 finished with value: 0.7740892025648121 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 572, 'max_depth': 5, 'lr': 0.07481880725872753, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 42 with value: 0.8035528471295695.
[I 2026-01-22 09:54:51,519] Trial 48 finished with value: 0.8032002833326837 and parameters: {'model': 'RF', 'top_k': 9, 'n_estimators': 518, 'max_depth': 15}. Best is trial 42 with value: 0.8035528471295695.

[I 2026-01-22 09:54:59,512] A new study created in memory with name: no-name-f22b2ec5-5c1f-44cb-af47-31fee40a4025

[I 2026-01-22 09:54:59,504] Trial 49 finished with value: 0.7875848688070715 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 614, 'max_depth': 15}. Best is trial 42 with value: 0.8035528471295695.

🔍 Optimizing for Y Concentration

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 09:55:07,452] Trial 0 finished with value: 0.6815660697726955 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.6815660697726955.
[I 2026-01-22 09:55:16,609] Trial 1 finished with value: 0.7374878722829992 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.7374878722829992.
[I 2026-01-22 09:55:20,245] Trial 2 finished with value: 0.672020736292651 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.7374878722829992.
[I 2026-01-22 09:55:28,530] Trial 3 finished with value: 0.6982333384220614 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.7374878722829992.
[I 2026-01-22 09:55:31,969] Trial 4 finished with value: 0.6596334943053075 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.7374878722829992.
[I 2026-01-22 09:55:38,188] Trial 5 finished with value: 0.6584029860636678 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.7374878722829992.
[I 2026-01-22 09:55:50,225] Trial 6 finished with value: 0.7039926997193342 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.7374878722829992.
[I 2026-01-22 09:55:55,084] Trial 7 finished with value: 0.6725152959992751 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.7374878722829992.
[I 2026-01-22 09:55:58,620] Trial 8 finished with value: 0.6601211747058067 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.7374878722829992.
[I 2026-01-22 09:56:07,519] Trial 9 finished with value: 0.7366789929842962 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 1 with value: 0.7374878722829992.
[I 2026-01-22 09:56:15,543] Trial 10 finished with value: 0.6871767967555458 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 12}. Best is trial 1 with value: 0.7374878722829992.
[I 2026-01-22 09:56:24,885] Trial 11 finished with value: 0.7366350160095554 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 12}. Best is trial 1 with value: 0.7374878722829992.
[I 2026-01-22 09:56:34,279] Trial 12 finished with value: 0.7398907103472947 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 623, 'max_depth': 11}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:56:43,909] Trial 13 finished with value: 0.7371472666708458 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 682, 'max_depth': 10}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:56:52,516] Trial 14 finished with value: 0.7375229567537941 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 621, 'max_depth': 15}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:56:57,866] Trial 15 finished with value: 0.6677792397162954 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 232, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:57:04,720] Trial 16 finished with value: 0.7025690780209903 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 486, 'max_depth': 16}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:57:12,740] Trial 17 finished with value: 0.7264162982114903 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 467, 'max_depth': 18}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:57:22,366] Trial 18 finished with value: 0.73855024370367 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 619, 'max_depth': 14}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:57:28,123] Trial 19 finished with value: 0.6016019375719217 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 441, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:57:36,275] Trial 20 finished with value: 0.7276518952922667 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 547, 'max_depth': 13}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:57:45,863] Trial 21 finished with value: 0.7361718198927807 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 623, 'max_depth': 16}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:57:54,174] Trial 22 finished with value: 0.7390085414473722 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 579, 'max_depth': 14}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:58:03,164] Trial 23 finished with value: 0.7351158277299981 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 580, 'max_depth': 14}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:58:12,382] Trial 24 finished with value: 0.7382629231503194 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 659, 'max_depth': 10}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:58:20,640] Trial 25 finished with value: 0.738755486765977 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 589, 'max_depth': 17}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:58:29,429] Trial 26 finished with value: 0.7285763219910599 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 579, 'max_depth': 18}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:58:38,258] Trial 27 finished with value: 0.6635020834715389 and parameters: {'model': 'GB', 'top_k': 13, 'n_estimators': 476, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:58:52,192] Trial 28 finished with value: 0.7038328188747188 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 661, 'max_depth': 20}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:59:03,127] Trial 29 finished with value: 0.7012873736237937 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 514, 'max_depth': 17}. Best is trial 12 with value: 0.7398907103472947.
[I 2026-01-22 09:59:10,999] Trial 30 finished with value: 0.739958263285703 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 581, 'max_depth': 11}. Best is trial 30 with value: 0.739958263285703.
[I 2026-01-22 09:59:19,798] Trial 31 finished with value: 0.7400057638588668 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 576, 'max_depth': 11}. Best is trial 31 with value: 0.7400057638588668.
[I 2026-01-22 09:59:28,161] Trial 32 finished with value: 0.7364370791863578 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 524, 'max_depth': 11}. Best is trial 31 with value: 0.7400057638588668.
[I 2026-01-22 09:59:35,494] Trial 33 finished with value: 0.7379324912109282 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 566, 'max_depth': 9}. Best is trial 31 with value: 0.7400057638588668.
[I 2026-01-22 09:59:44,966] Trial 34 finished with value: 0.7399953957122447 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 651, 'max_depth': 11}. Best is trial 31 with value: 0.7400057638588668.
[I 2026-01-22 09:59:54,208] Trial 35 finished with value: 0.734057874247861 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 662, 'max_depth': 11}. Best is trial 31 with value: 0.7400057638588668.
[I 2026-01-22 09:59:57,764] Trial 36 finished with value: 0.6338091192902131 and parameters: {'model': 'XGB', 'top_k': 14, 'n_estimators': 561, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 31 with value: 0.7400057638588668.
[I 2026-01-22 10:00:10,395] Trial 37 finished with value: 0.6991531330719085 and parameters: {'model': 'RF', 'top_k': 12, 'n_estimators': 645, 'max_depth': 9}. Best is trial 31 with value: 0.7400057638588668.
[I 2026-01-22 10:00:20,285] Trial 38 finished with value: 0.7397220175905291 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 700, 'max_depth': 11}. Best is trial 31 with value: 0.7400057638588668.
[I 2026-01-22 10:00:23,892] Trial 39 finished with value: 0.6550882249776598 and parameters: {'model': 'XGB', 'top_k': 14, 'n_estimators': 522, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 31 with value: 0.7400057638588668.
[I 2026-01-22 10:00:31,826] Trial 40 finished with value: 0.6264559698608247 and parameters: {'model': 'GB', 'top_k': 13, 'n_estimators': 487, 'lr': 0.032894255032331704, 'max_depth': 3}. Best is trial 31 with value: 0.7400057638588668.
[I 2026-01-22 10:00:39,849] Trial 41 finished with value: 0.7402817003289162 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 606, 'max_depth': 11}. Best is trial 41 with value: 0.7402817003289162.
[I 2026-01-22 10:00:48,726] Trial 42 finished with value: 0.7375001570776389 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 604, 'max_depth': 10}. Best is trial 41 with value: 0.7402817003289162.
[I 2026-01-22 10:00:58,268] Trial 43 finished with value: 0.7388971299650468 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 640, 'max_depth': 13}. Best is trial 41 with value: 0.7402817003289162.
[I 2026-01-22 10:01:06,624] Trial 44 finished with value: 0.7382355464644821 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 605, 'max_depth': 9}. Best is trial 41 with value: 0.7402817003289162.
[I 2026-01-22 10:01:15,397] Trial 45 finished with value: 0.7365296887525397 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 639, 'max_depth': 12}. Best is trial 41 with value: 0.7402817003289162.
[I 2026-01-22 10:01:24,328] Trial 46 finished with value: 0.7340031613651521 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 612, 'max_depth': 11}. Best is trial 41 with value: 0.7402817003289162.
[I 2026-01-22 10:01:28,831] Trial 47 finished with value: 0.6717036514882795 and parameters: {'model': 'XGB', 'top_k': 15, 'n_estimators': 570, 'max_depth': 4, 'lr': 0.012035429732013193, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 41 with value: 0.7402817003289162.
[I 2026-01-22 10:01:40,342] Trial 48 finished with value: 0.6847211066693343 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 674, 'max_depth': 13}. Best is trial 41 with value: 0.7402817003289162.

[I 2026-01-22 10:01:48,925] A new study created in memory with name: no-name-6a9a69b7-c3fd-4d18-97f0-2d369544bc27

[I 2026-01-22 10:01:48,914] Trial 49 finished with value: 0.736236529088311 and parameters: {'model': 'ET', 'top_k': 10, 'n_estimators': 595, 'max_depth': 11}. Best is trial 41 with value: 0.7402817003289162.

🔍 Optimizing for Zr Concentration

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-22 10:01:56,007] Trial 0 finished with value: 0.4100912017485294 and parameters: {'model': 'RF', 'top_k': 6, 'n_estimators': 362, 'max_depth': 8}. Best is trial 0 with value: 0.4100912017485294.
[I 2026-01-22 10:02:05,191] Trial 1 finished with value: 0.4960280608115184 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 633, 'max_depth': 10}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:02:10,372] Trial 2 finished with value: 0.37831906821894074 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 387, 'max_depth': 5, 'lr': 0.022554447458683766, 'subsample': 0.7876433945605654, 'colsample': 0.8099085529881075}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:02:17,829] Trial 3 finished with value: 0.4334939239277779 and parameters: {'model': 'RF', 'top_k': 11, 'n_estimators': 318, 'max_depth': 15}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:02:21,727] Trial 4 finished with value: 0.33598201200400657 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 391, 'max_depth': 3, 'lr': 0.07158097238609412, 'subsample': 0.8320457481218804, 'colsample': 0.7366114704534336}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:02:28,062] Trial 5 finished with value: 0.360932411009706 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 293, 'lr': 0.05680612190600298, 'max_depth': 4}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:02:40,177] Trial 6 finished with value: 0.41567450359525066 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 539, 'max_depth': 19}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:02:43,851] Trial 7 finished with value: 0.3663993134179349 and parameters: {'model': 'XGB', 'top_k': 9, 'n_estimators': 381, 'max_depth': 6, 'lr': 0.04210779940242304, 'subsample': 0.7842803529062142, 'colsample': 0.8628088249474746}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:02:48,397] Trial 8 finished with value: 0.3608309073029747 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 359, 'max_depth': 3, 'lr': 0.08339152856093508, 'subsample': 0.9120572031542851, 'colsample': 0.9187021504122962}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:02:56,125] Trial 9 finished with value: 0.48377486308609907 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 549, 'max_depth': 12}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:03:04,936] Trial 10 finished with value: 0.3406767543574127 and parameters: {'model': 'ET', 'top_k': 5, 'n_estimators': 688, 'max_depth': 12}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:03:14,310] Trial 11 finished with value: 0.48263606680004845 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 599, 'max_depth': 12}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:03:22,653] Trial 12 finished with value: 0.48796209041709926 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 623, 'max_depth': 11}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:03:32,317] Trial 13 finished with value: 0.4957712771586805 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 682, 'max_depth': 10}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:03:42,093] Trial 14 finished with value: 0.4952991428769115 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 685, 'max_depth': 10}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:03:47,451] Trial 15 finished with value: 0.4621363969036051 and parameters: {'model': 'GB', 'top_k': 10, 'n_estimators': 434, 'lr': 0.017310164682715158, 'max_depth': 2}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:03:56,299] Trial 16 finished with value: 0.47034185449731236 and parameters: {'model': 'ET', 'top_k': 7, 'n_estimators': 635, 'max_depth': 15}. Best is trial 1 with value: 0.4960280608115184.
[I 2026-01-22 10:04:03,493] Trial 17 finished with value: 0.4963694935030059 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 467, 'max_depth': 9}. Best is trial 17 with value: 0.4963694935030059.
[I 2026-01-22 10:04:11,041] Trial 18 finished with value: 0.4953751018111102 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 466, 'max_depth': 18}. Best is trial 17 with value: 0.4963694935030059.
[I 2026-01-22 10:04:15,921] Trial 19 finished with value: 0.4182941959376203 and parameters: {'model': 'GB', 'top_k': 11, 'n_estimators': 204, 'lr': 0.09983831247079358, 'max_depth': 2}. Best is trial 17 with value: 0.4963694935030059.
[I 2026-01-22 10:04:23,154] Trial 20 finished with value: 0.4908165195315644 and parameters: {'model': 'ET', 'top_k': 8, 'n_estimators': 507, 'max_depth': 9}. Best is trial 17 with value: 0.4963694935030059.
[I 2026-01-22 10:04:32,918] Trial 21 finished with value: 0.4959463995027029 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 663, 'max_depth': 10}. Best is trial 17 with value: 0.4963694935030059.
[I 2026-01-22 10:04:41,687] Trial 22 finished with value: 0.48819048265984233 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 578, 'max_depth': 13}. Best is trial 17 with value: 0.4963694935030059.
[I 2026-01-22 10:04:50,223] Trial 23 finished with value: 0.4936768798246164 and parameters: {'model': 'ET', 'top_k': 15, 'n_estimators': 640, 'max_depth': 9}. Best is trial 17 with value: 0.4963694935030059.
[I 2026-01-22 10:04:58,196] Trial 24 finished with value: 0.5073983799383358 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 484, 'max_depth': 10}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:05:05,192] Trial 25 finished with value: 0.4893594734701886 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 474, 'max_depth': 14}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:05:13,197] Trial 26 finished with value: 0.4977172976615087 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 515, 'max_depth': 9}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:05:21,242] Trial 27 finished with value: 0.35283844502139133 and parameters: {'model': 'GB', 'top_k': 12, 'n_estimators': 427, 'lr': 0.0399204177340166, 'max_depth': 4}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:05:30,664] Trial 28 finished with value: 0.42751585037735895 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 509, 'max_depth': 9}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:05:40,427] Trial 29 finished with value: 0.42618978675331104 and parameters: {'model': 'RF', 'top_k': 10, 'n_estimators': 462, 'max_depth': 11}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:05:48,634] Trial 30 finished with value: 0.4973223550221082 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 535, 'max_depth': 9}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:05:55,660] Trial 31 finished with value: 0.49746457744526634 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 531, 'max_depth': 9}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:06:04,095] Trial 32 finished with value: 0.49403731345999324 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 542, 'max_depth': 11}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:06:12,096] Trial 33 finished with value: 0.49795176731555435 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 517, 'max_depth': 9}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:06:19,460] Trial 34 finished with value: 0.4941706478196132 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 493, 'max_depth': 17}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:06:28,083] Trial 35 finished with value: 0.5009090503414438 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 573, 'max_depth': 10}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:06:31,690] Trial 36 finished with value: 0.3595393872105722 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 491, 'max_depth': 5, 'lr': 0.09905151299789039, 'subsample': 0.991865748444196, 'colsample': 0.9923658041427219}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:06:44,320] Trial 37 finished with value: 0.4192725957180475 and parameters: {'model': 'RF', 'top_k': 14, 'n_estimators': 582, 'max_depth': 11}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:06:53,137] Trial 38 finished with value: 0.49256648591987345 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 571, 'max_depth': 13}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:06:56,952] Trial 39 finished with value: 0.33430028987264093 and parameters: {'model': 'XGB', 'top_k': 13, 'n_estimators': 521, 'max_depth': 5, 'lr': 0.060509466754130076, 'subsample': 0.7012771932739541, 'colsample': 0.7071307127829614}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:07:03,724] Trial 40 finished with value: 0.39473081096832313 and parameters: {'model': 'GB', 'top_k': 9, 'n_estimators': 446, 'lr': 0.032894255032331704, 'max_depth': 3}. Best is trial 24 with value: 0.5073983799383358.
[I 2026-01-22 10:07:11,082] Trial 41 finished with value: 0.5089985510716882 and parameters: {'model': 'ET', 'top_k': 12, 'n_estimators': 558, 'max_depth': 10}. Best is trial 41 with value: 0.5089985510716882.
[I 2026-01-22 10:07:19,602] Trial 42 finished with value: 0.500667173569806 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 559, 'max_depth': 10}. Best is trial 41 with value: 0.5089985510716882.
[I 2026-01-22 10:07:28,358] Trial 43 finished with value: 0.4966307949881511 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 559, 'max_depth': 10}. Best is trial 41 with value: 0.5089985510716882.
[I 2026-01-22 10:07:36,359] Trial 44 finished with value: 0.4868923552321083 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 601, 'max_depth': 11}. Best is trial 41 with value: 0.5089985510716882.
[I 2026-01-22 10:07:45,524] Trial 45 finished with value: 0.4854571984328476 and parameters: {'model': 'ET', 'top_k': 13, 'n_estimators': 601, 'max_depth': 12}. Best is trial 41 with value: 0.5089985510716882.
[I 2026-01-22 10:07:54,489] Trial 46 finished with value: 0.49881867612920877 and parameters: {'model': 'ET', 'top_k': 14, 'n_estimators': 612, 'max_depth': 10}. Best is trial 41 with value: 0.5089985510716882.
[I 2026-01-22 10:07:59,363] Trial 47 finished with value: 0.3739214793216855 and parameters: {'model': 'XGB', 'top_k': 14, 'n_estimators': 555, 'max_depth': 4, 'lr': 0.012035429732013193, 'subsample': 0.9912993861734267, 'colsample': 0.9974252137598633}. Best is trial 41 with value: 0.5089985510716882.
[I 2026-01-22 10:08:09,117] Trial 48 finished with value: 0.490773422365493 and parameters: {'model': 'ET', 'top_k': 11, 'n_estimators': 655, 'max_depth': 13}. Best is trial 41 with value: 0.5089985510716882.
[I 2026-01-22 10:08:22,893] Trial 49 finished with value: 0.41843733797287436 and parameters: {'model': 'RF', 'top_k': 13, 'n_estimators': 619, 'max_depth': 20}. Best is trial 41 with value: 0.5089985510716882.

In [ ]:
results_df = pd.DataFrame(results)
results_df

,Target,Best_CV_R2,Best_Params
0,Mg,0.508343,"{'model': 'RF', 'top_k': 6, 'n_estimators': 36..."
1,Al,0.662198,"{'model': 'ET', 'top_k': 10, 'n_estimators': 4..."
2,Si,0.328139,"{'model': 'RF', 'top_k': 12, 'n_estimators': 6..."
3,P,0.611973,"{'model': 'ET', 'top_k': 14, 'n_estimators': 5..."
4,K FC,0.525634,"{'model': 'ET', 'top_k': 7, 'n_estimators': 62..."
5,Ca FC,0.690469,"{'model': 'GB', 'top_k': 5, 'n_estimators': 40..."
6,Ti FC,0.366443,"{'model': 'ET', 'top_k': 12, 'n_estimators': 5..."
7,Cr Concentration,0.310817,"{'model': 'ET', 'top_k': 12, 'n_estimators': 3..."
8,Mn FC,0.584346,"{'model': 'GB', 'top_k': 7, 'n_estimators': 25..."
9,Fe FC,0.483213,"{'model': 'ET', 'top_k': 10, 'n_estimators': 5..."
10,Ni Concentration,0.320565,"{'model': 'ET', 'top_k': 15, 'n_estimators': 6..."
11,Cu FC,0.673553,"{'model': 'ET', 'top_k': 12, 'n_estimators': 4..."
12,Zn FC,0.715560,"{'model': 'ET', 'top_k': 14, 'n_estimators': 5..."
13,Rb Concentration,0.259171,"{'model': 'ET', 'top_k': 9, 'n_estimators': 48..."
14,Sr Concentration,0.803553,"{'model': 'RF', 'top_k': 9, 'n_estimators': 67..."
15,Y Concentration,0.740282,"{'model': 'ET', 'top_k': 15, 'n_estimators': 6..."
16,Zr Concentration,0.508999,"{'model': 'ET', 'top_k': 12, 'n_estimators': 5..."

In [ ]:
results_df.to_csv("Part2_Elemental_Results.csv", index=False)